namespace MimosBabySpa.Application.Identity;

public static class PermissionCatalog
{
    public static readonly (string Module, string Action, string Resource, string Description)[] All =
    {
        ("Users", "Read", "users.read", "Ver listado de usuarios"),
        ("Users", "Create", "users.create", "Crear nuevos usuarios"),
        ("Users", "Update", "users.update", "Actualizar usuarios"),
        ("Users", "Delete", "users.delete", "Desactivar usuarios"),
        ("Users", "AssignRole", "users.assign_role", "Asignar roles a usuarios"),
        ("Users", "RemoveRole", "users.remove_role", "Remover roles de usuarios"),
        ("Roles", "Read", "roles.read", "Ver roles"),
        ("Roles", "Create", "roles.create", "Crear roles"),
        ("Roles", "Update", "roles.update", "Actualizar roles"),
        ("Roles", "Delete", "roles.delete", "Desactivar roles"),
        ("Roles", "AssignPermissions", "roles.assign_permissions", "Asignar permisos a roles"),
        ("Permissions", "Read", "permissions.read", "Ver permisos del sistema"),
        ("Tenants", "Read", "tenants.read", "Ver tenants"),
        ("Tenants", "Create", "tenants.create", "Crear tenants"),
        ("Tenants", "Update", "tenants.update", "Actualizar tenants"),
        ("Businesses", "Read", "businesses.read", "Ver negocios"),
        ("Businesses", "Create", "businesses.create", "Crear negocios"),
        ("Businesses", "Update", "businesses.update", "Actualizar negocios"),
        ("Businesses", "Delete", "businesses.delete", "Eliminar negocios"),
        ("Services", "Read", "services.read", "Ver servicios"),
        ("Services", "Create", "services.create", "Crear servicios"),
        ("Services", "Update", "services.update", "Actualizar servicios"),
        ("Services", "Delete", "services.delete", "Eliminar servicios"),
        ("Products", "Read", "products.read", "Ver productos"),
        ("Products", "Update", "products.update", "Activar o inactivar productos"),
        ("Promotions", "Read", "promotions.read", "Ver promociones"),
        ("Promotions", "Create", "promotions.create", "Crear promociones"),
        ("Promotions", "Update", "promotions.update", "Actualizar promociones"),
        ("Promotions", "Delete", "promotions.delete", "Desactivar promociones"),
        ("Employees", "Read", "employees.read", "Ver empleados"),
        ("Employees", "Create", "employees.create", "Crear empleados"),
        ("Employees", "Update", "employees.update", "Actualizar empleados"),
        ("Employees", "Delete", "employees.delete", "Eliminar empleados"),
        ("Reservations", "Read", "reservations.read", "Ver reservas"),
        ("Reservations", "Create", "reservations.create", "Crear reservas"),
        ("Reservations", "Update", "reservations.update", "Actualizar reservas"),
        ("Reservations", "Cancel", "reservations.cancel", "Cancelar reservas"),
        ("Reservations", "Export", "reservations.export", "Exportar reservas"),
        ("Leads", "Read", "leads.read", "Ver leads"),
        ("Leads", "Create", "leads.create", "Crear leads"),
        ("Leads", "Update", "leads.update", "Actualizar leads"),
        ("Leads", "Export", "leads.export", "Exportar leads"),
        ("Conversations", "Read", "conversations.read", "Ver conversaciones"),
        ("Orders", "Read", "orders.read", "Ver pedidos"),
        ("Payments", "Read", "payments.read", "Ver transacciones de pago"),
        ("Payments", "ConfirmManual", "payments.confirm_manual", "Confirmar pagos manualmente"),
        ("BusinessConfig", "Read", "business_config.read", "Ver configuración"),
        ("BusinessConfig", "Update", "business_config.update", "Actualizar configuración"),
        ("AuditLogs", "Read", "audit_logs.read", "Ver logs de auditoría"),
        ("Dashboard", "Read", "dashboard.read", "Ver dashboard"),
    };
}

