"use client";

import {useMemo,useState,type ComponentProps} from "react";
import {usePathname} from "next/navigation";
import {useQuery} from "@tanstack/react-query";
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {ArrowDownRight,ArrowUpRight,CalendarRange,Download,FileText,PackageSearch,RefreshCw,RotateCcw,Search,TrendingUp,Users} from "lucide-react";
import {salesReportingApi,type SalesBreakdownRow,type SalesDimension,type SalesDocumentRow,type SalesReportFilter} from "@/services/api/sales-reporting";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Input as BaseInput} from "@/components/ui/input";
import {DatePicker} from "@/components/ui/date-picker";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Badge} from "@/components/ui/badge";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {PageError} from "@/components/ui/page-error";
import {PageLoading} from "@/components/ui/page-loading";
import {ReportViewer} from "@/components/reports/report-viewer";

const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const number=new Intl.NumberFormat("es-CO",{maximumFractionDigits:2});
const iso=(date:Date)=>date.toISOString().slice(0,10);
const now=new Date(),initialFrom=iso(new Date(now.getFullYear(),0,1)),initialTo=iso(now);
const labels:Record<SalesDimension,string>={customer:"Cliente",seller:"Vendedor",supplier:"Proveedor",product:"Producto",category:"Categoría",warehouse:"Sede",day:"Día",hour:"Hora",month:"Mes","payment-method":"Forma de pago",tax:"Impuesto"};
const dimensions:SalesDimension[]=["customer","seller","supplier","product","category","warehouse","month","payment-method","tax"];

function Input(props:ComponentProps<typeof BaseInput>){
  if(props.type!=="date")return <BaseInput {...props}/>;
  const {value,onChange,disabled,className}=props;
  return <DatePicker value={String(value??"")} disabled={disabled} className={className}
    onChange={next=>onChange?.({target:{value:next},currentTarget:{value:next}} as never)}/>;
}

export default function SalesAnalyticsPage(){
  const pathname=usePathname();
  const profile=pathname.includes("supplier-impact")?{title:"Impacto por proveedor",description:"Venta, devolución, costo y utilidad atribuida al proveedor fijado al facturar.",dimension:"supplier" as SalesDimension}:pathname.includes("customers")?{title:"Clientes y cobertura",description:"Clientes que explican la venta neta, con trazabilidad hasta cada comprobante.",dimension:"customer" as SalesDimension}:pathname.includes("sellers")?{title:"Desempeño de vendedores",description:"Resultados comerciales por vendedor, con venta neta, devoluciones, costo y utilidad.",dimension:"seller" as SalesDimension}:{title:"Ventas",description:"De la venta neta de toda la empresa al producto y comprobante que explica cada cifra.",dimension:"product" as SalesDimension};
  const [from,setFrom]=useState(initialFrom),[to,setTo]=useState(initialTo);
  const [documentType,setDocumentType]=useState<"all"|"SalesInvoice"|"SalesReceipt">("all");
  const [customerId,setCustomer]=useState("all"),[sellerId,setSeller]=useState("all"),[supplierId,setSupplier]=useState("all"),[productId,setProduct]=useState("all"),[categoryId,setCategory]=useState("all"),[warehouseId,setWarehouse]=useState("all");
  const [dimension,setDimension]=useState<SalesDimension>(profile.dimension),[page,setPage]=useState(1),[search,setSearch]=useState(""),[detailId,setDetailId]=useState<string|null>(null),[exporting,setExporting]=useState(false);
  const [exportRows,setExportRows]=useState<SalesDocumentRow[]|null>(null);
  const filter=useMemo<SalesReportFilter>(()=>({from,to,customerId:empty(customerId),sellerId:empty(sellerId),supplierId:empty(supplierId),productId:empty(productId),categoryId:empty(categoryId),warehouseId:empty(warehouseId),documentType:documentType==="all"?undefined:documentType}),[from,to,customerId,sellerId,supplierId,productId,categoryId,warehouseId,documentType]);
  const baseFilter=useMemo<SalesReportFilter>(()=>({from,to,documentType:documentType==="all"?undefined:documentType}),[from,to,documentType]);
  const previous=useMemo(()=>({from:shiftYear(from,-1),to:shiftYear(to,-1)}),[from,to]);
  const summary=useQuery({queryKey:["sales-report-summary",filter,previous],queryFn:()=>salesReportingApi.summary(filter,previous)});
  const breakdown=useQuery({queryKey:["sales-report-breakdown",filter,dimension],queryFn:()=>salesReportingApi.breakdown(filter,dimension,100)});
  const documents=useQuery({queryKey:["sales-report-documents",filter,page,search],queryFn:()=>salesReportingApi.documents(filter,page,25,search||undefined)});
  const sellerOrders=useQuery({queryKey:["sales-report-seller-orders",from,to],queryFn:()=>salesReportingApi.sellerOrders(from,to),enabled:pathname.includes("sellers")});
  const options=useQuery({queryKey:["sales-report-options",baseFilter],queryFn:async()=>{const values=await Promise.all((["customer","seller","supplier","product","category","warehouse"] as SalesDimension[]).map(item=>salesReportingApi.breakdown(baseFilter,item,500)));return Object.fromEntries((["customer","seller","supplier","product","category","warehouse"] as SalesDimension[]).map((key,index)=>[key,values[index]])) as Record<string,SalesBreakdownRow[]>;}});
  const detail=useQuery({queryKey:["sales-report-document",detailId],queryFn:()=>salesReportingApi.document(detailId!),enabled:Boolean(detailId)});
  if(summary.isLoading)return <PageLoading/>;
  if(summary.isError)return <PageError onRetry={()=>void summary.refetch()}/>;
  const totals=summary.data!.current,change=summary.data!.netSalesChangePercent;
  const paymentAttributionUnavailable=Boolean(filter.supplierId||filter.productId||filter.categoryId);
  const reset=()=>{setCustomer("all");setSeller("all");setSupplier("all");setProduct("all");setCategory("all");setWarehouse("all");setDocumentType("all");setPage(1)};
  const selectBreakdown=(row:SalesBreakdownRow)=>{if(!isUuid(row.key))return;({customer:setCustomer,seller:setSeller,supplier:setSupplier,product:setProduct,category:setCategory,warehouse:setWarehouse} as Partial<Record<SalesDimension,(v:string)=>void>>)[dimension]?.(row.key);setPage(1)};
  const exportReport=async()=>{setExporting(true);try{const rows:SalesDocumentRow[]=[];let currentPage=1,total=0;do{const batch=await salesReportingApi.documents(filter,currentPage,200,search||undefined);rows.push(...batch.items);total=batch.totalCount;currentPage+=1}while(rows.length<total);setExportRows(rows)}finally{setExporting(false)}};
  const sellerOrdersCard=pathname.includes("sellers")?<Card className="rounded-3xl"><CardHeader><CardTitle>Pedidos por vendedor</CardTitle><CardDescription>Pedidos capturados, clientes atendidos, facturación, valor y revisión de inventario desde reporting.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead><tr><th className="p-3 text-left">Vendedor</th><th>Pedidos</th><th>Clientes</th><th>Confirmados</th><th>Facturados</th><th>En revisión</th><th className="pr-3 text-right">Valor</th></tr></thead><tbody>{(sellerOrders.data??[]).map(row=><tr key={row.sellerId} className="border-t text-center"><td className="p-3 text-left font-medium">{row.sellerName}</td><td>{row.orderCount}</td><td>{row.customerCount}</td><td>{row.confirmedCount}</td><td>{row.invoicedCount}</td><td>{row.reviewCount}</td><td className="pr-3 text-right font-semibold">{money.format(row.orderAmount)}</td></tr>)}</tbody></table>{!sellerOrders.isLoading&&!sellerOrders.data?.length&&<p className="p-8 text-center text-sm text-muted-foreground">Sin pedidos proyectados para el período.</p>}</CardContent></Card>:null;
  if(exportRows)return <ReportViewer onClose={()=>setExportRows(null)} title="Ventas y devoluciones" description={`${from} a ${to} · cifras netas con devolución`} fileName={`ventas-${from}-${to}`} rows={exportRows.map(documentRow)} columns={documentColumns}/>;
  return <div className="space-y-6">
    <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-cyan-950 to-teal-700 p-6 text-white shadow-xl">
      <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-200">Motor de reporting comercial</p><h1 className="mt-2 text-3xl font-black tracking-tight">{profile.title}</h1><p className="mt-2 max-w-3xl text-sm text-cyan-50/80">{profile.description} Incluye devoluciones, costo reconocido y rentabilidad.</p></div><div className="flex flex-wrap gap-2"><Badge className="border-white/20 bg-white/10 text-white" variant="outline">Actualizado {summary.data?.projectedThrough?new Date(summary.data.projectedThrough).toLocaleString("es-CO"):"sin proyecciones"}</Badge><Button className="bg-white text-slate-950 hover:bg-cyan-50" onClick={()=>void exportReport()} disabled={exporting}><Download className="mr-2 h-4 w-4"/>{exporting?"Preparando…":"Exportar detalle"}</Button></div></div>
    </header>
    <Card className="rounded-3xl"><CardContent className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-5"><Filter label="Desde"><Input type="date" value={from} onChange={event=>{setFrom(event.target.value);setPage(1)}}/></Filter><Filter label="Hasta"><Input type="date" value={to} onChange={event=>{setTo(event.target.value);setPage(1)}}/></Filter><Picker label="Documento" value={documentType} set={value=>{setDocumentType(value as typeof documentType);setPage(1)}} rows={[{key:"all",label:"Ventas y recibos"},{key:"SalesInvoice",label:"Facturas"},{key:"SalesReceipt",label:"Recibos"}]}/><div className="flex items-end"><Button variant="outline" className="w-full" onClick={reset}><RefreshCw className="mr-2 h-4 w-4"/>Limpiar filtros</Button></div><div className="flex items-end text-xs text-muted-foreground"><CalendarRange className="mr-2 h-4 w-4"/>Compara automáticamente con el mismo rango del año anterior.</div></CardContent></Card>
    <div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><Metric title="Venta bruta" value={money.format(totals.grossSales)} detail={`${totals.documentCount.toLocaleString("es-CO")} documentos`} icon={TrendingUp}/><Metric title="Devoluciones" value={money.format(totals.returns)} detail={`${number.format(totals.unitsReturned)} unidades`} icon={RotateCcw} tone="amber"/><Metric title="Venta neta" value={money.format(totals.netTotalSales)} detail={change===null?"Sin base comparable":`${change>=0?"+":""}${number.format(change)}% vs. año anterior`} icon={change!==null&&change<0?ArrowDownRight:ArrowUpRight} tone="teal"/><Metric title="Utilidad bruta" value={money.format(totals.grossProfit)} detail={`${number.format(totals.grossMarginPercent)}% margen`} icon={PackageSearch}/><Metric title="Impuestos netos" value={money.format(totals.netTax)} detail={`Base ${money.format(totals.netUntaxedSales)}`} icon={FileText}/><Metric title="Recaudado" value={paymentAttributionUnavailable?"No atribuible":money.format(totals.collected)} detail={paymentAttributionUnavailable?"El pago pertenece al documento, no a una línea":`Crédito ${money.format(totals.creditSales)}`} icon={Users}/></div>
    {sellerOrdersCard}
    <Card className="rounded-3xl"><CardHeader><CardTitle>Evolución de venta neta</CardTitle><CardDescription>Ventas, devoluciones y utilidad día a día. Haz clic en un punto para ver sus documentos.</CardDescription></CardHeader><CardContent><div className="h-[340px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={summary.data?.trend??[]} onClick={state=>{const label=state?.activeLabel;if(typeof label==="string"){setFrom(label.slice(0,10));setTo(label.slice(0,10));setPage(1)}}}><defs><linearGradient id="sales" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#0f766e" stopOpacity={.45}/><stop offset="95%" stopColor="#0f766e" stopOpacity={.03}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="period" tickFormatter={shortDate}/><YAxis tickFormatter={compactMoney}/><Tooltip formatter={(value,name)=>[money.format(Number(value)),name==="netSales"?"Venta neta":name==="returns"?"Devoluciones":"Utilidad"]} labelFormatter={value=>new Date(String(value)+"T00:00:00").toLocaleDateString("es-CO")}/><Legend/><Area type="monotone" dataKey="netSales" name="Venta neta" stroke="#0f766e" fill="url(#sales)" strokeWidth={3}/><Area type="monotone" dataKey="returns" name="Devoluciones" stroke="#f59e0b" fill="transparent" strokeWidth={2}/><Area type="monotone" dataKey="grossProfit" name="Utilidad" stroke="#2563eb" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></CardContent></Card>
    <Card className="rounded-3xl"><CardHeader><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><CardTitle>Explorar y comparar</CardTitle><CardDescription>Agrupa la misma cifra por cualquier dimensión. Selecciona una barra para filtrar hasta sus comprobantes.</CardDescription></div><Select value={dimension} onValueChange={value=>setDimension(value as SalesDimension)}><SelectTrigger className="w-60"><SelectValue/></SelectTrigger><SelectContent>{dimensions.map(value=><SelectItem key={value} value={value}>{labels[value]}</SelectItem>)}</SelectContent></Select></div></CardHeader><CardContent><div className="h-[360px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={(breakdown.data??[]).slice(0,15)} layout="vertical" margin={{left:30}} onClick={state=>{const index=state?.activeTooltipIndex;if(typeof index==="number"){const row=breakdown.data?.[index];if(row)selectBreakdown(row)}}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tickFormatter={compactMoney}/><YAxis type="category" dataKey="label" width={145} tick={{fontSize:11}}/><Tooltip formatter={value=>money.format(Number(value))}/><Bar dataKey="netSales" name="Venta neta" fill="#0f766e" radius={[0,7,7,0]} cursor="pointer"/></BarChart></ResponsiveContainer></div></CardContent></Card>
    <Card className="rounded-3xl"><CardHeader><CardTitle>Filtros de negocio</CardTitle><CardDescription>Combínalos libremente; los totales, gráficas, rankings y comprobantes responden al mismo contexto.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Picker label="Cliente" value={customerId} set={v=>{setCustomer(v);setPage(1)}} rows={withAll(options.data?.customer)}/><Picker label="Vendedor" value={sellerId} set={v=>{setSeller(v);setPage(1)}} rows={withAll(options.data?.seller)}/><Picker label="Proveedor" value={supplierId} set={v=>{setSupplier(v);setPage(1)}} rows={withAll(options.data?.supplier)}/><Picker label="Producto" value={productId} set={v=>{setProduct(v);setPage(1)}} rows={withAll(options.data?.product)}/><Picker label="Categoría" value={categoryId} set={v=>{setCategory(v);setPage(1)}} rows={withAll(options.data?.category)}/><Picker label="Sede" value={warehouseId} set={v=>{setWarehouse(v);setPage(1)}} rows={withAll(options.data?.warehouse)}/></CardContent></Card>
    <Card className="overflow-hidden rounded-3xl"><CardHeader><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><CardTitle>Comprobantes que explican el resultado</CardTitle><CardDescription>{documents.data?.totalCount??0} ventas en el contexto actual. Abre una fila para ver venta, devolución, producto, impuesto y costo.</CardDescription></div><div className="relative w-full lg:w-80"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Factura, cliente, vendedor o producto" value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}}/></div></div></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-muted/50 text-left"><tr><th className="p-3">Fecha</th><th>Documento</th><th>Cliente</th><th>Vendedor</th><th className="text-right">Venta</th><th className="text-right">Devuelto</th><th className="pr-4 text-right">Neto</th></tr></thead><tbody>{(documents.data?.items??[]).map(row=><tr key={row.documentId} className="cursor-pointer border-t hover:bg-muted/40" onClick={()=>setDetailId(row.documentId)}><td className="whitespace-nowrap p-3">{new Date(row.issuedAt).toLocaleDateString("es-CO")}</td><td><strong>{row.documentNumber}</strong><small className="block text-muted-foreground">{row.documentType==="SalesInvoice"?"Factura":"Recibo"}</small></td><td>{row.customerName}</td><td>{row.sellerName}</td><td className="text-right">{money.format(row.totalAmount)}</td><td className="text-right text-amber-700">{money.format(row.returnedTotalAmount)}</td><td className="pr-4 text-right font-bold">{money.format(row.netTotalAmount)}</td></tr>)}</tbody></table>{documents.isLoading&&<p className="p-10 text-center text-muted-foreground">Cargando detalle…</p>}{!documents.isLoading&&!documents.data?.items.length&&<p className="p-10 text-center text-muted-foreground">No hay ventas proyectadas para estos filtros.</p>}</div><div className="flex items-center justify-between border-t p-4"><span className="text-sm text-muted-foreground">Página {page} de {Math.max(1,Math.ceil((documents.data?.totalCount??0)/25))}</span><div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(value=>value-1)}>Anterior</Button><Button variant="outline" disabled={page*25>=(documents.data?.totalCount??0)} onClick={()=>setPage(value=>value+1)}>Siguiente</Button></div></div></CardContent></Card>
    <Dialog open={Boolean(detailId)} onOpenChange={open=>!open&&setDetailId(null)}><DialogContent className="max-h-[92vh] max-w-6xl overflow-auto"><DialogHeader><DialogTitle>{detail.data?.document.documentNumber??"Detalle de venta"}</DialogTitle><DialogDescription>Composición completa desde la proyección de reporting; los valores negativos corresponden a devoluciones.</DialogDescription></DialogHeader>{detail.isLoading?<p className="p-10 text-center">Cargando…</p>:detail.data&&<><div className="grid gap-3 sm:grid-cols-4"><Mini label="Cliente" value={detail.data.document.customerName}/><Mini label="Vendedor" value={detail.data.document.sellerName}/><Mini label="Venta" value={money.format(detail.data.document.totalAmount)}/><Mini label="Venta neta" value={money.format(detail.data.document.netTotalAmount)}/></div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted"><tr><th className="p-3 text-left">Movimiento</th><th className="text-left">Producto</th><th className="text-right">Cantidad</th><th className="text-right">Base</th><th className="text-right">Impuesto</th><th className="text-right">Total</th><th className="pr-3 text-right">Costo</th></tr></thead><tbody>{detail.data.lines.map(line=><tr key={line.factId} className="border-t"><td className="p-3"><Badge variant={line.movementType==="Return"?"outline":"secondary"}>{line.movementType==="Return"?"Devolución":"Venta"}</Badge></td><td><strong>{line.productName}</strong><small className="block text-muted-foreground">{line.productCode} · {line.categoryName??"Sin categoría"}</small></td><td className="text-right">{number.format(line.quantity)}</td><td className="text-right">{money.format(line.untaxedAmount)}</td><td className="text-right">{money.format(line.taxAmount)}</td><td className="text-right font-semibold">{money.format(line.totalAmount)}</td><td className="pr-3 text-right">{money.format(line.recognizedCostAmount)}</td></tr>)}</tbody></table></div></>}</DialogContent></Dialog>
  </div>;
}

function Metric({title,value,detail,icon:Icon,tone="slate"}:{title:string;value:string;detail:string;icon:typeof TrendingUp;tone?:"slate"|"amber"|"teal"}){const colors={slate:"bg-slate-950 text-white",amber:"bg-amber-50 text-amber-950 border-amber-200",teal:"bg-teal-50 text-teal-950 border-teal-200"};return <Card className={`rounded-2xl ${colors[tone]}`}><CardContent className="p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wide opacity-70">{title}</span><Icon className="h-5 w-5 opacity-70"/></div><strong className="mt-3 block text-2xl tracking-tight">{value}</strong><small className="mt-1 block opacity-70">{detail}</small></CardContent></Card>}
function Filter({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1.5 text-sm"><span className="font-medium">{label}</span>{children}</label>}
function Picker({label,value,set,rows}:{label:string;value:string;set:(value:string)=>void;rows:Array<{key:string;label:string}>}){return <Filter label={label}><Select value={value} onValueChange={set}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{rows.map(row=><SelectItem key={row.key} value={row.key}>{row.label}</SelectItem>)}</SelectContent></Select></Filter>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-muted/20 p-3"><small className="text-muted-foreground">{label}</small><strong className="block truncate">{value}</strong></div>}
function empty(value:string){return value==="all"?undefined:value}
function withAll(rows?:SalesBreakdownRow[]){return [{key:"all",label:"Todos"},...(rows??[]).map(row=>({key:row.key,label:row.label}))]}
function shiftYear(value:string,amount:number){const date=new Date(`${value}T12:00:00`);date.setFullYear(date.getFullYear()+amount);return iso(date)}
function shortDate(value:string){return new Date(`${value}T00:00:00`).toLocaleDateString("es-CO",{day:"2-digit",month:"short"})}
function compactMoney(value:number){return new Intl.NumberFormat("es-CO",{notation:"compact",maximumFractionDigits:1}).format(value)}
function isUuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
function documentRow(row:SalesDocumentRow){return {date:new Date(row.issuedAt).toLocaleDateString("es-CO"),document:row.documentNumber,type:row.documentType==="SalesInvoice"?"Factura":"Recibo",customer:row.customerName,seller:row.sellerName,warehouse:row.warehouseName,sale:row.totalAmount,returns:row.returnedTotalAmount,net:row.netTotalAmount,profit:row.grossProfit}}
const documentColumns=[{key:"date",label:"Fecha"},{key:"document",label:"Documento"},{key:"type",label:"Tipo"},{key:"customer",label:"Cliente"},{key:"seller",label:"Vendedor"},{key:"warehouse",label:"Sede"},{key:"sale",label:"Venta",align:"right" as const,format:(value:string|number|null|undefined)=>money.format(Number(value))},{key:"returns",label:"Devuelto",align:"right" as const,format:(value:string|number|null|undefined)=>money.format(Number(value))},{key:"net",label:"Neto",align:"right" as const,format:(value:string|number|null|undefined)=>money.format(Number(value))},{key:"profit",label:"Utilidad",align:"right" as const,format:(value:string|number|null|undefined)=>money.format(Number(value))}];
