"use client";

import {useState,type FormEvent,type ReactNode} from "react";
import {useMutation} from "@tanstack/react-query";
import {Landmark,Plus,Trash2} from "lucide-react";
import {toast} from "sonner";
import {accountingApi,type AccountingAccount,type AccountingCostCenter,type BankAccount} from "@/services/api/accounting";
import {PartySelect} from "@/components/parties/party-role-select";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {DatePicker} from "@/components/ui/date-picker";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {useReferenceOptions} from "@/hooks/use-reference-options";

type Line={id:string;accountId:string;partyId:string|null;costCenterId:string|null;description:string;debit:string;credit:string};
type Balance={id:string;label:string};
const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const emptyLine=(description=""):Line=>({id:crypto.randomUUID(),accountId:"",partyId:null,costCenterId:null,description,debit:"",credit:""});

export function ManualDocumentsSection({businessId,accounts,banks,mapped,centers,payables,receivables,refresh}:{businessId:string;accounts:AccountingAccount[];banks:BankAccount[];mapped:Map<string,string>;centers:AccountingCostCenter[];payables:Array<{payableId:string;supplierName:string;documentNumber:string;outstandingAmount:number}>;receivables:Array<{receivableId:string;customerName:string;documentNumber:string;outstandingAmount:number}>;refresh:()=>Promise<unknown>}){
  const subledgerKinds=useReferenceOptions("accounting-subledger-kind"),directions=useReferenceOptions("accounting-adjustment-direction"),concepts=useReferenceOptions("accounting-manual-concept");
  const today=new Date().toISOString().slice(0,10),[kind,setKind]=useState<"Payable"|"Receivable">("Payable"),[subledger,setSubledger]=useState(""),[direction,setDirection]=useState<"Increase"|"Decrease">("Increase"),[amount,setAmount]=useState(""),[counterpart,setCounterpart]=useState(""),[date,setDate]=useState(today),[concept,setConcept]=useState("ACCOUNT_ADJUSTMENT"),[description,setDescription]=useState(""),[adjustmentId,setAdjustmentId]=useState(()=>crypto.randomUUID());
  const [voucherDate,setVoucherDate]=useState(today),[voucherConcept,setVoucherConcept]=useState("MANUAL_VOUCHER"),[voucherDescription,setVoucherDescription]=useState(""),[lines,setLines]=useState<Line[]>([emptyLine(),emptyLine()]),[bankId,setBankId]=useState(banks.find(value=>value.isPrimary)?.bankAccountId??""),[voucherId,setVoucherId]=useState(()=>crypto.randomUUID());
  const adjustment=useMutation({mutationFn:()=>accountingApi.confirmAdjustment({adjustmentId,businessId,subledgerKind:kind,subledgerId:subledger,direction,amount:Number(amount),counterpartAccountId:counterpart,costCenterId:null,occurredAt:`${date}T12:00:00-05:00`,conceptCode:concept,description}),onSuccess:async()=>{setAdjustmentId(crypto.randomUUID());setAmount("");setDescription("");await refresh();toast.success("Nota de cartera aceptada y enviada al motor contable")},onError:showError});
  const normalized=lines.map(line=>({...line,debit:Number(line.debit||0),credit:Number(line.credit||0)})),debit=normalized.reduce((sum,line)=>sum+line.debit,0),credit=normalized.reduce((sum,line)=>sum+line.credit,0),balanced=debit>0&&Math.abs(debit-credit)<.0001,valid=normalized.length>=2&&normalized.every(line=>{const account=accounts.find(value=>value.accountId===line.accountId);return Boolean(account&&line.description.trim()&&(line.debit>0)!==(line.credit>0)&&(!account.requiresParty||line.partyId))});
  const voucher=useMutation({mutationFn:()=>accountingApi.confirmVoucher({voucherId,businessId,occurredAt:`${voucherDate}T12:00:00-05:00`,conceptCode:voucherConcept,description:voucherDescription,lines:normalized.map(line=>({accountId:line.accountId,partyId:line.partyId,costCenterId:line.costCenterId,description:line.description.trim(),debit:line.debit,credit:line.credit}))}),onSuccess:async()=>{setVoucherId(crypto.randomUUID());setVoucherDescription("");setLines([emptyLine(),emptyLine()]);await refresh();toast.success("Comprobante balanceado aceptado y enviado al motor contable")},onError:showError});
  const balances:Balance[]=kind==="Payable"?payables.map(item=>({id:item.payableId,label:`${item.supplierName} · ${item.documentNumber} · ${money.format(item.outstandingAmount)}`})):receivables.map(item=>({id:item.receivableId,label:`${item.customerName} · ${item.documentNumber} · ${money.format(item.outstandingAmount)}`}));
  const update=(id:string,change:Partial<Line>)=>setLines(current=>current.map(line=>line.id===id?{...line,...change}:line));
  const addPreset=(accountId:string|undefined,label:string,side:"debit"|"credit")=>{if(!accountId){toast.error(`Configura primero la cuenta automática de ${label.toLocaleLowerCase("es-CO")}.`);return}setLines(current=>{const index=current.findIndex(line=>!line.accountId&&!line.debit&&!line.credit);const preset={...emptyLine(voucherDescription||label),accountId,[side]:"0"};return index<0?[...current,preset]:current.map((line,lineIndex)=>lineIndex===index?preset:line)})};
  return <div className="grid gap-5 xl:grid-cols-2"><Card className="rounded-3xl"><CardHeader><CardTitle>Nota débito o crédito de cartera</CardTitle><p className="text-sm text-muted-foreground">Modifica CxC/CxP y genera el asiento de control en una sola operación. Una disminución nunca puede dejar saldo negativo.</p></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={event=>submit(event,adjustment.mutate)}><Field label="Auxiliar"><Select value={kind} onValueChange={value=>{setKind(value as typeof kind);setSubledger("")}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{(subledgerKinds.data??[]).map(item=><SelectItem key={item.code} value={item.code}>{item.label}</SelectItem>)}</SelectContent></Select></Field><Field label="Efecto"><Select value={direction} onValueChange={value=>setDirection(value as typeof direction)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{(directions.data??[]).map(item=><SelectItem key={item.code} value={item.code}>{item.label}</SelectItem>)}</SelectContent></Select></Field><div className="sm:col-span-2"><Field label="Documento y tercero"><Select value={subledger} onValueChange={setSubledger}><SelectTrigger><SelectValue placeholder="Seleccionar saldo"/></SelectTrigger><SelectContent>{balances.map(item=><SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select></Field></div><Field label="Cuenta contrapartida"><AccountSelect value={counterpart} accounts={accounts} onChange={setCounterpart}/></Field><Field label="Valor"><Input type="number" min="0.01" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} required/></Field><Field label="Fecha"><DatePicker value={date} onChange={setDate}/></Field><Field label="Concepto"><Select value={concept} onValueChange={setConcept}><SelectTrigger><SelectValue placeholder="Seleccionar concepto"/></SelectTrigger><SelectContent>{(concepts.data??[]).map(item=><SelectItem key={item.code} value={item.code}>{item.label}</SelectItem>)}</SelectContent></Select></Field><div className="sm:col-span-2"><Field label="Descripción contable"><Input value={description} maxLength={500} onChange={event=>setDescription(event.target.value)} required/></Field></div><Button className="sm:col-span-2" disabled={adjustment.isPending||!subledger||!counterpart||!concept}>Confirmar nota</Button></form></CardContent></Card>
  <Card className="overflow-hidden rounded-3xl xl:col-span-2"><CardHeader><CardTitle>Comprobante manual de varias partidas</CardTitle><p className="text-sm text-muted-foreground">Permite liquidar tarjetas por el bruto, registrar el banco por el neto y separar comisiones, impuestos o retenciones soportadas. También sirve para consignar efectivo sin volver a reconocer la venta.</p></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><Field label="Fecha"><DatePicker value={voucherDate} onChange={setVoucherDate}/></Field><Field label="Concepto"><Select value={voucherConcept} onValueChange={setVoucherConcept}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{(concepts.data??[]).map(item=><SelectItem key={item.code} value={item.code}>{item.label}</SelectItem>)}</SelectContent></Select></Field><Field label="Descripción"><Input value={voucherDescription} onChange={event=>setVoucherDescription(event.target.value)} maxLength={500}/></Field></div><div className="flex flex-wrap items-end gap-2"><Field label="Cuenta receptora"><Select value={bankId} onValueChange={setBankId}><SelectTrigger className="w-64"><SelectValue placeholder="Seleccionar banco"/></SelectTrigger><SelectContent>{banks.map(bank=><SelectItem key={bank.bankAccountId} value={bank.bankAccountId}>{bank.displayName} · {bank.accountingAccountCode}</SelectItem>)}</SelectContent></Select></Field><Button variant="outline" onClick={()=>addPreset(banks.find(bank=>bank.bankAccountId===bankId)?.accountingAccountId,"Banco", "debit")}><Landmark className="mr-2 h-4 w-4"/>Agregar banco</Button><Button variant="outline" onClick={()=>addPreset(mapped.get("DebitCardClearing"),"Tarjeta débito por liquidar","credit")}>Agregar tarjeta débito</Button><Button variant="outline" onClick={()=>addPreset(mapped.get("CreditCardClearing"),"Tarjeta crédito por liquidar","credit")}>Agregar tarjeta crédito</Button><Button variant="outline" onClick={()=>addPreset(mapped.get("Cash"),"Caja","credit")}>Agregar caja</Button><Button variant="outline" onClick={()=>setLines(current=>[...current,emptyLine(voucherDescription)])}><Plus className="mr-2 h-4 w-4"/>Agregar partida</Button></div>
  <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-muted/50"><tr><th className="p-2 text-left">Cuenta</th><th className="text-left">Tercero</th><th className="text-left">Centro de costo</th><th className="text-left">Descripción</th><th className="text-right">Débito</th><th className="text-right">Crédito</th><th/></tr></thead><tbody>{lines.map(line=>{const account=accounts.find(value=>value.accountId===line.accountId);return <tr key={line.id} className="border-t align-top"><td className="p-2"><AccountSelect value={line.accountId} accounts={accounts} onChange={accountId=>update(line.id,{accountId,partyId:accounts.find(value=>value.accountId===accountId)?.requiresParty?line.partyId:null})}/>{account?.requiresParty&&<small className="text-amber-700">Exige tercero</small>}</td><td className="p-2"><PartySelect value={line.partyId??"none"} leadingOptions={[{value:"none",label:"Sin tercero"}]} placeholder="Buscar tercero" onChange={value=>update(line.id,{partyId:value==="none"?null:value})}/></td><td className="p-2"><Select value={line.costCenterId??"none"} onValueChange={value=>update(line.id,{costCenterId:value==="none"?null:value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Automático</SelectItem>{centers.filter(value=>value.isActive).map(center=><SelectItem key={center.costCenterId} value={center.costCenterId}>{center.code} · {center.name}</SelectItem>)}</SelectContent></Select></td><td className="p-2"><Input value={line.description} maxLength={500} onChange={event=>update(line.id,{description:event.target.value})}/></td><td className="p-2"><Input className="text-right" type="number" min="0" step="0.01" value={line.debit} onChange={event=>update(line.id,{debit:event.target.value,credit:event.target.value?"":line.credit})}/></td><td className="p-2"><Input className="text-right" type="number" min="0" step="0.01" value={line.credit} onChange={event=>update(line.id,{credit:event.target.value,debit:event.target.value?"":line.debit})}/></td><td className="p-2"><Button size="icon" variant="ghost" disabled={lines.length<=2} aria-label="Eliminar partida" onClick={()=>setLines(current=>current.filter(value=>value.id!==line.id))}><Trash2 className="h-4 w-4"/></Button></td></tr>})}</tbody><tfoot className="border-t-2 bg-muted/30 font-bold"><tr><td className="p-3" colSpan={4}>Totales {balanced&&<span className="ml-2 text-emerald-700">· Cuadrado</span>}</td><td className="text-right">{money.format(debit)}</td><td className="text-right">{money.format(credit)}</td><td/></tr></tfoot></table></div><Button className="w-full" disabled={voucher.isPending||!voucherConcept||!voucherDescription.trim()||!valid||!balanced} onClick={()=>voucher.mutate()}>Confirmar comprobante cuadrado</Button></CardContent></Card></div>;
}

function AccountSelect({value,accounts,onChange}:{value:string;accounts:Array<{accountId:string;code:string;name:string}>;onChange:(value:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder="Seleccionar cuenta"/></SelectTrigger><SelectContent>{accounts.map(item=><SelectItem key={item.accountId} value={item.accountId}>{item.code} · {item.name}</SelectItem>)}</SelectContent></Select>}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function submit(event:FormEvent,mutate:()=>void){event.preventDefault();mutate()}
function showError(error:unknown){toast.error(error instanceof Error?error.message:"No fue posible completar la operación")}
