"use client";

import {useMemo,useState,type FormEvent,type ReactNode} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {AlertTriangle,BookOpen,Building2,CalendarRange,CheckCircle2,ChevronRight,Landmark,Loader2,RefreshCw,Settings2,TableProperties} from "lucide-react";
import {toast} from "sonner";
import {accountingApi} from "@/services/api/accounting";
import {useTenantContextStore} from "@/stores/tenant-context-store";
import {useBusinessContextStore} from "@/stores/business-context-store";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";

const accountTypes:Record<string,string>={Asset:"Activo",Liability:"Pasivo",Equity:"Patrimonio",Revenue:"Ingreso",Expense:"Gasto",ContraRevenue:"Contraingreso"};
type Section="setup"|"puc"|"centers"|"periods"|"balance";
const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const year=new Date().getFullYear(),yearStart=`${year}-01-01`,yearEnd=`${year}-12-31`;

export default function AccountingConfigurationPage(){
  const tenantId=useTenantContextStore(state=>state.selectedTenantId),businessId=useBusinessContextStore(state=>state.selectedBusinessId),queryClient=useQueryClient();
  const key=["accounting",tenantId,businessId],enabled=Boolean(tenantId&&businessId);
  const accounts=useQuery({queryKey:[...key,"accounts"],queryFn:accountingApi.accounts,enabled});
  const centers=useQuery({queryKey:[...key,"centers"],queryFn:accountingApi.costCenters,enabled});
  const periods=useQuery({queryKey:[...key,"periods"],queryFn:accountingApi.periods,enabled});
  const mappings=useQuery({queryKey:[...key,"mappings"],queryFn:accountingApi.mappings,enabled});
  const definitions=useQuery({queryKey:[...key,"category-definitions"],queryFn:accountingApi.categoryDefinitions,enabled});
  const [section,setSection]=useState<Section>("setup"),[scope,setScope]=useState<"tenant"|"business">("tenant"),[from,setFrom]=useState(yearStart),[to,setTo]=useState(yearEnd);
  const balance=useQuery({queryKey:[...key,"trial-balance",from,to],queryFn:()=>accountingApi.trialBalance(from,to),enabled:enabled&&section==="balance"});
  const refresh=async()=>queryClient.invalidateQueries({queryKey:key});
  const defaults=useMutation({mutationFn:accountingApi.ensureDefaults,onSuccess:async result=>{await refresh();toast.success(result.isReady?"Contabilidad Auraly configurada":"Configuración aplicada; revisa los pendientes")},onError:showError});
  const mapping=useMutation({mutationFn:({category,accountId}:{category:string;accountId:string})=>accountingApi.setMapping({tenantId:tenantId!,businessId:scope==="business"?businessId:null,category,accountId,effectiveFrom:"2000-01-01",effectiveTo:null}),onSuccess:async()=>{await refresh();toast.success("Cuenta automática actualizada")},onError:showError});
  const accountRows=accounts.data??[],postingAccounts=accountRows.filter(item=>item.isActive&&item.allowsPosting);
  const activeMappings=useMemo(()=>{const result=new Map<string,string>();for(const item of [...(mappings.data??[])].sort((a,b)=>Number(Boolean(a.businessId))-Number(Boolean(b.businessId))))result.set(item.category,item.accountId);return result},[mappings.data]);
  const categoryRows=definitions.data??[],requiredCategories=categoryRows.filter(item=>item.isRequired),today=new Date().toISOString().slice(0,10),mappedCount=requiredCategories.filter(item=>activeMappings.has(item.category)).length,hasCenter=(centers.data??[]).some(item=>item.isActive&&item.isDefault),hasPeriod=(periods.data??[]).some(item=>item.status==="Open"&&item.startsOn<=today&&item.endsOn>=today);
  const ready=categoryRows.length>0&&mappedCount===requiredCategories.length&&hasCenter&&hasPeriod;
  if(!tenantId||!businessId)return <EmptyContext/>;
  return <div className="space-y-5">
    <header className="overflow-hidden rounded-3xl bg-gradient-to-r from-slate-950 via-cyan-950 to-teal-700 p-6 text-white shadow-lg"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-200">Motor contable Auraly</p><h1 className="mt-2 text-3xl font-black">Contabilidad clara y automática</h1><p className="mt-2 max-w-2xl text-sm text-cyan-50/80">Configura una vez el PUC y revisa cómo ventas, compras, inventario, devoluciones y caja acumulan sus movimientos.</p></div><Button className="h-12 bg-white text-slate-950 hover:bg-cyan-50" disabled={defaults.isPending} onClick={()=>defaults.mutate()}>{defaults.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Settings2 className="mr-2 h-4 w-4"/>}{ready?"Verificar configuración":"Configurar Auraly"}</Button></div></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatusCard label="Estado" value={ready?"Lista para contabilizar":"Requiere atención"} ok={ready}/><StatusCard label="PUC activo" value={`${accountRows.filter(x=>x.isActive).length} cuentas`} ok={accountRows.length>=requiredCategories.length}/><StatusCard label="Cuentas automáticas" value={`${mappedCount}/${requiredCategories.length} conceptos`} ok={requiredCategories.length>0&&mappedCount===requiredCategories.length}/><StatusCard label="Periodo actual" value={hasPeriod?"Abierto":"Sin periodo abierto"} ok={hasPeriod}/></div>
    <nav className="flex gap-1 overflow-x-auto rounded-2xl border bg-card p-1"><Nav active={section==="setup"} icon={Settings2} onClick={()=>setSection("setup")}>Automatización</Nav><Nav active={section==="puc"} icon={BookOpen} onClick={()=>setSection("puc")}>Plan de cuentas</Nav><Nav active={section==="centers"} icon={Building2} onClick={()=>setSection("centers")}>Centros de costo</Nav><Nav active={section==="periods"} icon={CalendarRange} onClick={()=>setSection("periods")}>Periodos</Nav><Nav active={section==="balance"} icon={TableProperties} onClick={()=>setSection("balance")}>Balance de comprobación</Nav></nav>
    {section==="setup"&&(
      <AutomationSection categories={categoryRows} accounts={postingAccounts} mapped={activeMappings} mappedCount={mappedCount} scope={scope} setScope={setScope} pending={mapping.isPending} onMap={(category,accountId)=>mapping.mutate({category,accountId})}/>
    )}
    {section==="puc"&&(
      <AccountsSection tenantId={tenantId} rows={accountRows} refresh={refresh}/>
    )}
    {section==="centers"&&(
      <CentersSection businessId={businessId} rows={centers.data??[]} refresh={refresh}/>
    )}
    {section==="periods"&&(
      <PeriodsSection tenantId={tenantId} rows={periods.data??[]} refresh={refresh}/>
    )}
    {section==="balance"&&(
      <BalanceSection from={from} to={to} setFrom={setFrom} setTo={setTo} rows={balance.data??[]} loading={balance.isFetching} refresh={()=>void balance.refetch()}/>
    )}
  </div>
}

function AutomationSection({categories,accounts,mapped,mappedCount,scope,setScope,pending,onMap}:{categories:Array<{category:string;displayName:string;isRequired:boolean}>;accounts:Array<{accountId:string;code:string;name:string}>;mapped:Map<string,string>;mappedCount:number;scope:"tenant"|"business";setScope:(value:"tenant"|"business")=>void;pending:boolean;onMap:(category:string,accountId:string)=>void}){const requiredCount=categories.filter(item=>item.isRequired).length;return <Card className="overflow-hidden rounded-3xl"><CardHeader className="border-b bg-muted/30"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>Cuentas automáticas</CardTitle><p className="mt-1 text-sm text-muted-foreground">Cada concepto debe apuntar a una cuenta contabilizable. {mappedCount}/{requiredCount} completos.</p></div><Select value={scope} onValueChange={value=>setScope(value as "tenant"|"business")}><SelectTrigger className="w-56"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="tenant">Regla general de la empresa</SelectItem><SelectItem value="business">Excepción para esta sede</SelectItem></SelectContent></Select></div></CardHeader><CardContent className="p-0"><div className="grid lg:grid-cols-2">{categories.map(item=><div key={item.category} className="grid grid-cols-[minmax(0,1fr)_minmax(13rem,1.2fr)] items-center gap-3 border-b p-4 lg:odd:border-r"><div><strong className="text-sm">{item.displayName}</strong><small className="block text-muted-foreground">{item.category}</small></div><Select value={mapped.get(item.category)??""} disabled={pending||!accounts.length} onValueChange={accountId=>onMap(item.category,accountId)}><SelectTrigger className={mapped.has(item.category)?"":"border-amber-400 bg-amber-50"}><SelectValue placeholder="Seleccionar cuenta"/></SelectTrigger><SelectContent>{accounts.map(account=><SelectItem key={account.accountId} value={account.accountId}>{account.code} · {account.name}</SelectItem>)}</SelectContent></Select></div>)}</div></CardContent></Card>}

function AccountsSection({tenantId,rows,refresh}:{tenantId:string;rows:Array<{accountId:string;code:string;name:string;accountType:string;allowsPosting:boolean;requiresParty:boolean;isActive:boolean}>;refresh:()=>Promise<unknown>}){const [code,setCode]=useState(""),[name,setName]=useState(""),[type,setType]=useState("Asset"),[party,setParty]=useState(false);const mutation=useMutation({mutationFn:()=>accountingApi.createAccount({accountId:crypto.randomUUID(),tenantId,code,name,accountType:type,allowsPosting:true,requiresParty:party}),onSuccess:async()=>{setCode("");setName("");await refresh();toast.success("Cuenta creada")},onError:showError});return <div className="grid gap-5 xl:grid-cols-[23rem_1fr]"><Card className="h-fit rounded-3xl"><CardHeader><CardTitle>Nueva cuenta auxiliar</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={event=>submit(event,mutation.mutate)}><Field label="Código PUC"><Input value={code} onChange={event=>setCode(event.target.value)} required/></Field><Field label="Nombre"><Input value={name} onChange={event=>setName(event.target.value)} required/></Field><Field label="Naturaleza"><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(accountTypes).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={party} onChange={event=>setParty(event.target.checked)}/> Exige tercero</label><Button className="w-full" disabled={mutation.isPending}>Crear cuenta</Button></form></CardContent></Card><Card className="overflow-hidden rounded-3xl"><CardHeader><CardTitle>Plan Único de Cuentas operativo</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50 text-left"><tr><th className="p-3">Código</th><th>Cuenta</th><th>Naturaleza</th><th>Tercero</th><th>Estado</th></tr></thead><tbody>{rows.map(row=><tr key={row.accountId} className="border-t"><td className="p-3 font-mono font-semibold">{row.code}</td><td>{row.name}</td><td>{accountTypes[row.accountType]??row.accountType}</td><td>{row.requiresParty?"Sí":"No"}</td><td><Badge variant={row.isActive?"secondary":"outline"}>{row.isActive?"Activa":"Inactiva"}</Badge></td></tr>)}</tbody></table></div></CardContent></Card></div>}

function CentersSection({businessId,rows,refresh}:{businessId:string;rows:Array<{costCenterId:string;code:string;name:string;isDefault:boolean;isActive:boolean}>;refresh:()=>Promise<unknown>}){const [code,setCode]=useState(""),[name,setName]=useState(""),[isDefault,setDefault]=useState(false);const mutation=useMutation({mutationFn:()=>accountingApi.createCostCenter({costCenterId:crypto.randomUUID(),businessId,code,name,parentCostCenterId:null,isDefault}),onSuccess:async()=>{setCode("");setName("");await refresh();toast.success("Centro de costo creado")},onError:showError});return <div className="grid gap-5 lg:grid-cols-[24rem_1fr]"><Card className="h-fit rounded-3xl"><CardHeader><CardTitle>Nuevo centro de costo</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={event=>submit(event,mutation.mutate)}><Field label="Código"><Input value={code} onChange={event=>setCode(event.target.value)} required/></Field><Field label="Nombre"><Input value={name} onChange={event=>setName(event.target.value)} required/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={isDefault} onChange={event=>setDefault(event.target.checked)}/> Centro predeterminado</label><Button className="w-full" disabled={mutation.isPending}>Crear centro</Button></form></CardContent></Card><SummaryCards title="Centros configurados" empty="No hay centros de costo." values={rows.map(row=>({title:`${row.code} · ${row.name}`,detail:row.isDefault?"Predeterminado":"Centro adicional",ok:row.isActive}))}/></div>}

function PeriodsSection({tenantId,rows,refresh}:{tenantId:string;rows:Array<{periodId:string;name:string;startsOn:string;endsOn:string;status:string}>;refresh:()=>Promise<unknown>}){const [name,setName]=useState(String(year)),[starts,setStarts]=useState(yearStart),[ends,setEnds]=useState(yearEnd);const create=useMutation({mutationFn:()=>accountingApi.createPeriod({periodId:crypto.randomUUID(),tenantId,startsOn:starts,endsOn:ends,name}),onSuccess:async()=>{await refresh();toast.success("Periodo creado")},onError:showError});const close=useMutation({mutationFn:accountingApi.closePeriod,onSuccess:async()=>{await refresh();toast.success("Periodo cerrado")},onError:showError});return <div className="grid gap-5 lg:grid-cols-[24rem_1fr]"><Card className="h-fit rounded-3xl"><CardHeader><CardTitle>Nuevo periodo</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={event=>submit(event,create.mutate)}><Field label="Nombre"><Input value={name} onChange={event=>setName(event.target.value)} required/></Field><Field label="Desde"><Input type="date" value={starts} onChange={event=>setStarts(event.target.value)} required/></Field><Field label="Hasta"><Input type="date" value={ends} onChange={event=>setEnds(event.target.value)} required/></Field><Button className="w-full" disabled={create.isPending}>Crear periodo</Button></form></CardContent></Card><Card className="rounded-3xl"><CardHeader><CardTitle>Periodos contables</CardTitle></CardHeader><CardContent className="space-y-2">{rows.map(row=><div key={row.periodId} className="flex items-center gap-3 rounded-2xl border p-4"><CalendarRange className="h-5 w-5 text-teal-700"/><div className="min-w-0 flex-1"><strong>{row.name}</strong><small className="block text-muted-foreground">{row.startsOn} a {row.endsOn}</small></div><Badge variant={row.status==="Open"?"secondary":"outline"}>{row.status==="Open"?"Abierto":"Cerrado"}</Badge>{row.status==="Open"&&<Button size="sm" variant="outline" disabled={close.isPending} onClick={()=>close.mutate(row.periodId)}>Cerrar</Button>}</div>)}{!rows.length&&<p className="text-sm text-muted-foreground">No hay periodos.</p>}</CardContent></Card></div>}

function BalanceSection({from,to,setFrom,setTo,rows,loading,refresh}:{from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void;rows:Array<{accountCode:string;accountName:string;debit:number;credit:number;balance:number}>;loading:boolean;refresh:()=>void}){
  const [selected,setSelected]=useState<(typeof rows)[number]|null>(null);
  const movements=useQuery({queryKey:["account-movements",selected?.accountCode,from,to],queryFn:()=>accountingApi.accountMovements(selected!.accountCode,from,to),enabled:Boolean(selected)});
  const totals=rows.reduce((value,row)=>({debit:value.debit+row.debit,credit:value.credit+row.credit}),{debit:0,credit:0});
  return <>
    <Card className="overflow-hidden rounded-3xl"><CardHeader className="border-b"><div className="flex flex-col gap-3 lg:flex-row lg:items-end"><div className="flex-1"><CardTitle>Balance de comprobación</CardTitle><p className="mt-1 text-sm text-muted-foreground">Saldos reales de los documentos contabilizados en el periodo. Selecciona una cuenta para ver sus movimientos.</p></div><Field label="Desde"><Input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></Field><Field label="Hasta"><Input type="date" value={to} onChange={event=>setTo(event.target.value)}/></Field><Button variant="outline" onClick={refresh} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>Actualizar</Button></div></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50"><tr><th className="p-3 text-left">Cuenta</th><th className="text-left">Nombre</th><th className="text-right">Débito</th><th className="text-right">Crédito</th><th className="pr-4 text-right">Saldo</th><th className="w-10"/></tr></thead><tbody>{rows.map(row=><tr key={row.accountCode} tabIndex={0} role="button" onClick={()=>setSelected(row)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setSelected(row)}}} className="cursor-pointer border-t outline-none transition-colors hover:bg-muted/50 focus-visible:bg-muted/50"><td className="p-3 font-mono font-semibold">{row.accountCode}</td><td>{row.accountName}</td><td className="text-right">{money.format(row.debit)}</td><td className="text-right">{money.format(row.credit)}</td><td className="pr-4 text-right font-semibold">{money.format(row.balance)}</td><td><ChevronRight className="h-4 w-4 text-muted-foreground"/></td></tr>)}</tbody><tfoot className="border-t-2 bg-muted/30 font-bold"><tr><td className="p-3" colSpan={2}>Totales</td><td className="text-right">{money.format(totals.debit)}</td><td className="text-right">{money.format(totals.credit)}</td><td className="pr-4 text-right">{money.format(totals.debit-totals.credit)}</td><td/></tr></tfoot></table>{!loading&&!rows.length&&<p className="p-10 text-center text-muted-foreground">No hay movimientos contabilizados en este rango.</p>}</div></CardContent></Card>
    <Dialog open={Boolean(selected)} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="max-w-6xl"><DialogHeader><DialogTitle>{selected?.accountCode} · {selected?.accountName}</DialogTitle><DialogDescription>Movimientos contabilizados del {from} al {to}.</DialogDescription></DialogHeader><div className="max-h-[65vh] overflow-auto rounded-xl border"><table className="w-full min-w-[850px] text-sm"><thead className="sticky top-0 bg-muted"><tr><th className="p-3 text-left">Fecha</th><th className="text-left">Asiento</th><th className="text-left">Documento</th><th className="text-left">Descripción</th><th className="text-right">Débito</th><th className="text-right">Crédito</th><th className="pr-3 text-right">Saldo</th></tr></thead><tbody>{(movements.data??[]).map(item=><tr key={`${item.entryId}-${item.description}`} className="border-t"><td className="whitespace-nowrap p-3">{new Date(item.occurredAt).toLocaleDateString("es-CO")}</td><td className="font-mono">{item.entryNumber}</td><td><span className="block">{item.sourceDocumentType}</span><small className="text-muted-foreground">{item.sourceDocumentId.slice(0,8)}</small></td><td>{item.description}</td><td className="text-right">{money.format(item.debit)}</td><td className="text-right">{money.format(item.credit)}</td><td className="pr-3 text-right font-semibold">{money.format(item.balance)}</td></tr>)}</tbody></table>{movements.isLoading&&<p className="p-10 text-center text-muted-foreground">Cargando movimientos…</p>}{!movements.isLoading&&!movements.data?.length&&<p className="p-10 text-center text-muted-foreground">No hay movimientos para esta cuenta en el rango.</p>}</div></DialogContent></Dialog>
  </>
}

function StatusCard({label,value,ok}:{label:string;value:string;ok:boolean}){return <Card className="rounded-2xl"><CardContent className="flex items-center gap-3 p-4">{ok?<CheckCircle2 className="h-8 w-8 text-emerald-600"/>:<AlertTriangle className="h-8 w-8 text-amber-600"/>}<div><small className="text-muted-foreground">{label}</small><strong className="block text-sm">{value}</strong></div></CardContent></Card>}
function Nav({active,icon:Icon,onClick,children}:{active:boolean;icon:typeof Landmark;onClick:()=>void;children:ReactNode}){return <button type="button" onClick={onClick} className={`flex shrink-0 items-center rounded-xl px-4 py-2.5 text-sm font-semibold ${active?"bg-slate-950 text-white shadow":"text-muted-foreground hover:bg-muted"}`}><Icon className="mr-2 h-4 w-4"/>{children}</button>}
function SummaryCards({title,values,empty}:{title:string;values:Array<{title:string;detail:string;ok:boolean}>;empty:string}){return <Card className="rounded-3xl"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{values.map(value=><div key={value.title} className="rounded-2xl border p-4"><strong className="text-sm">{value.title}</strong><small className="mt-1 block text-muted-foreground">{value.detail}</small></div>)}{!values.length&&<p className="text-sm text-muted-foreground">{empty}</p>}</CardContent></Card>}
function EmptyContext(){return <div className="rounded-3xl border border-dashed p-12 text-center"><Landmark className="mx-auto h-12 w-12 text-teal-700"/><h1 className="mt-4 text-xl font-bold">Selecciona una empresa y una sede</h1><p className="mt-2 text-sm text-muted-foreground">La configuración contable se aplica dentro de ese contexto.</p></div>}
function submit(event:FormEvent,mutate:()=>void){event.preventDefault();mutate()}
function showError(error:unknown){toast.error(error instanceof Error?error.message:"No fue posible completar la operación")}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
