namespace MimosBabySpa.Application.Identity.DTOs;

public record OrderDto(
    Guid OrderId,
    Guid BusinessId,
    Guid? AgentId,
    Guid? ConversationId,
    Guid? IntegrationConnectionId,
    Guid? PaymentTransactionId,
    string Source,
    string FulfillmentMode,
    string Status,
    string? CustomerName,
    string? CustomerEmail,
    string? CustomerPhone,
    string? CustomerDocument,
    string? DeliveryAddress,
    string? Notes,
    string Currency,
    decimal Subtotal,
    decimal DiscountTotal,
    decimal TaxTotal,
    decimal Total,
    bool CustomerConfirmed,
    string? ExternalOrderId,
    string? ExternalDocumentNumber,
    string? ExternalStatus,
    string? CustomAttributesJson,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    IReadOnlyList<OrderItemDto> Items);

public record OrderItemDto(
    Guid OrderItemId,
    Guid OrderId,
    Guid BusinessId,
    Guid? ProductId,
    Guid? IntegrationConnectionId,
    string? ExternalProductId,
    string? Sku,
    string ProductName,
    string? Description,
    decimal Quantity,
    decimal UnitPrice,
    decimal DiscountAmount,
    decimal TaxAmount,
    decimal LineTotal,
    DateTime CreatedAt,
    DateTime? UpdatedAt);

public record OrderSummaryDto(
    int TotalOrders,
    decimal TotalAmount,
    int DraftCount,
    int AwaitingPaymentCount,
    int ConfirmedCount,
    int SyncedCount,
    int CancelledCount);
