<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Auraly.BuildingBlocks.Application\Auraly.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Auraly.Contracts.Authorization\Auraly.Contracts.Authorization.csproj" />
    <ProjectReference Include="..\Auraly.Domain.Authorization\Auraly.Domain.Authorization.csproj" />
  </ItemGroup>
</Project>
