"use client";
import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { AgentSettings, MessageSequence } from "@/types/agent-settings";
type Props={sequences:NonNullable<AgentSettings["messageSequences"]>;onChange:(v:NonNullable<AgentSettings["messageSequences"]>)=>void};
export function WhatsAppTemplateGallery({sequences,onChange}:Props){const names=Object.keys(sequences);const add=()=>{const name=`mensaje_${names.length+1}`;onChange({...sequences,[name]:{messages:[{type:"text",body:""}]}})};return <Card><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle>Plantillas de mensajes</CardTitle><CardDescription>Mensajes que el asistente envía automáticamente. Cada tarjeta muestra la vista previa para WhatsApp.</CardDescription></div><Button type="button" size="sm" onClick={add}><Plus className="mr-1 h-4 w-4"/>Nueva plantilla</Button></CardHeader><CardContent>{names.length===0?<div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Aún no hay plantillas. Crea confirmaciones, recordatorios o mensajes posteriores a una compra.</div>:<div className="grid gap-4 lg:grid-cols-2">{names.map(name=>{const sequence=sequences[name];const body=sequence.messages?.[0]?.body??"";const update=(next:MessageSequence)=>onChange({...sequences,[name]:next});const rename=(nextName:string)=>{const copy={...sequences};delete copy[name];copy[nextName]=sequence;onChange(copy)};return <div key={name} className="overflow-hidden rounded-xl border bg-[#efeae2] dark:bg-muted/50"><div className="flex items-center justify-between border-b bg-card px-3 py-2"><Input className="h-8 max-w-[230px] border-0 bg-transparent px-0 font-medium shadow-none" value={name} onChange={e=>rename(e.target.value)}/><Button type="button" variant="ghost" size="icon" onClick={()=>{const copy={...sequences};delete copy[name];onChange(copy)}}><Trash2 className="h-4 w-4 text-destructive"/></Button></div><div className="p-4"><div className="max-w-[85%] rounded-lg rounded-tl-none bg-white p-3 text-sm shadow-sm dark:bg-card"><p className="whitespace-pre-wrap">{body||"Escribe el contenido de este mensaje"}</p><p className="mt-2 text-right text-[10px] text-muted-foreground">Vista previa · WhatsApp</p></div></div><div className="space-y-2 border-t bg-card p-3"><Label className="text-xs">Contenido</Label><Textarea className="min-h-24" value={body} onChange={e=>update({messages:[{...sequence.messages?.[0],type:"text",body:e.target.value}]})} placeholder="Escribe el mensaje que recibirá el cliente"/></div></div>})}</div>}</CardContent></Card>}