<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auraly.Contracts.Expenses\Auraly.Contracts.Expenses.csproj" />
    <ProjectReference Include="..\Auraly.Domain.Expenses\Auraly.Domain.Expenses.csproj" />
    <ProjectReference Include="..\..\DocumentProcessing\Auraly.Application.DocumentProcessing\Auraly.Application.DocumentProcessing.csproj" />
    <ProjectReference Include="..\..\Taxation\Auraly.Commerce.Taxation.Application\Auraly.Commerce.Taxation.Application.csproj" />
  </ItemGroup>
</Project>
