import type { SalesRouteDetail,SalesRouteVisit } from "@/services/api/routes";
import type { SellerCatalogItem,SellerOrderRequest,SellerOrderResult } from "@/services/api/seller-orders";

const DB="auraly-sales-pwa",VERSION=2,CATALOG="seller-catalog",DRAFTS="seller-order-drafts",OUTBOX="seller-order-outbox";
type Draft={key:string;request:SellerOrderRequest;quantities:Record<string,number>;updatedAt:string};
type Queued={id:string;request:SellerOrderRequest;route:SalesRouteDetail;visitDate:string;queuedAt:string;attempts:number};
function open(){return new Promise<IDBDatabase>((resolve,reject)=>{const value=indexedDB.open(DB,VERSION);value.onupgradeneeded=()=>{const db=value.result;if(!db.objectStoreNames.contains(CATALOG))db.createObjectStore(CATALOG,{keyPath:"key"});if(!db.objectStoreNames.contains(DRAFTS))db.createObjectStore(DRAFTS,{keyPath:"key"});if(!db.objectStoreNames.contains(OUTBOX))db.createObjectStore(OUTBOX,{keyPath:"id"});if(!db.objectStoreNames.contains("daily-route-snapshots"))db.createObjectStore("daily-route-snapshots",{keyPath:"key"});if(!db.objectStoreNames.contains("route-visit-outbox"))db.createObjectStore("route-visit-outbox",{keyPath:"idempotencyKey"})};value.onsuccess=()=>resolve(value.result);value.onerror=()=>reject(value.error)})}
async function tx<T>(store:string,mode:IDBTransactionMode,action:(value:IDBObjectStore)=>IDBRequest<T>){const db=await open();try{return await new Promise<T>((resolve,reject)=>{const result=action(db.transaction(store,mode).objectStore(store));result.onsuccess=()=>resolve(result.result);result.onerror=()=>reject(result.error)})}finally{db.close()}}
const catalogKey=(businessId:string,warehouseId:string,customerId:string)=>`${businessId}:${warehouseId}:${customerId}`;
export async function saveSellerCatalog(businessId:string,warehouseId:string,customerId:string,items:SellerCatalogItem[]){const existing=await loadSellerCatalog(businessId,warehouseId,customerId);const merged=new Map(existing.map(item=>[item.productId,item]));for(const item of items)merged.set(item.productId,item);await tx(CATALOG,"readwrite",store=>store.put({key:catalogKey(businessId,warehouseId,customerId),items:[...merged.values()],updatedAt:new Date().toISOString()}))}
export async function loadSellerCatalog(businessId:string,warehouseId:string,customerId:string){return (await tx(CATALOG,"readonly",store=>store.get(catalogKey(businessId,warehouseId,customerId))) as {items:SellerCatalogItem[]}|undefined)?.items??[]}
export async function saveSellerDraft(key:string,request:SellerOrderRequest,quantities:Record<string,number>){await tx(DRAFTS,"readwrite",store=>store.put({key,request,quantities,updatedAt:new Date().toISOString()} satisfies Draft))}
export async function loadSellerDraft(key:string){return await tx(DRAFTS,"readonly",store=>store.get(key)) as Draft|undefined}
export async function removeSellerDraft(key:string){await tx(DRAFTS,"readwrite",store=>store.delete(key))}
export async function queueSellerOrder(request:SellerOrderRequest,route:SalesRouteDetail,visitDate:string){await tx(OUTBOX,"readwrite",store=>store.put({id:request.idempotencyKey,request:{...request,capturedOffline:true},route,visitDate,queuedAt:new Date().toISOString(),attempts:0} satisfies Queued));return{orderId:`local-${request.idempotencyKey}`,orderNumber:"Pendiente de sincronizar",status:"Confirmed",total:0,requiresReview:false,warnings:[]} satisfies SellerOrderResult}
export async function pendingSellerOrders(){return await tx(OUTBOX,"readonly",store=>store.getAll()) as Queued[]}
export async function flushSellerOrderOutbox(upload:(request:SellerOrderRequest)=>Promise<SellerOrderResult>,recordVisit:(routeId:string,request:{routeStopId:string;visitDate:string;status:"Visited";skipReason:null;orderId:string;occurredAt:string;idempotencyKey:string})=>Promise<SalesRouteVisit>){if(typeof navigator==="undefined"||!navigator.onLine)return{uploaded:0,pending:(await pendingSellerOrders()).length};let uploaded=0;for(const value of(await pendingSellerOrders()).sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt))){try{const result=await upload(value.request);if(value.request.routeStopId)await recordVisit(value.route.routeId,{routeStopId:value.request.routeStopId,visitDate:value.visitDate,status:"Visited",skipReason:null,orderId:result.orderId,occurredAt:new Date().toISOString(),idempotencyKey:`visit-${value.id}`});await tx(OUTBOX,"readwrite",store=>store.delete(value.id));uploaded++}catch{await tx(OUTBOX,"readwrite",store=>store.put({...value,attempts:value.attempts+1}));break}}return{uploaded,pending:(await pendingSellerOrders()).length}}
