import type { SalesRouteDetail,SalesRouteVisit } from "@/services/api/routes";
import type { SellerCatalogItem,SellerOrderRequest,SellerOrderResult } from "@/services/api/seller-orders";
import { openSalesOfflineDatabase } from "@/lib/sales-offline-database";

const CATALOG="seller-catalog",DRAFTS="seller-order-drafts",OUTBOX="seller-order-outbox",PREPARATIONS="seller-offline-preparations";
type Draft={key:string;request:SellerOrderRequest;quantities:Record<string,number>;updatedAt:string};
type Queued={id:string;request:SellerOrderRequest;route:SalesRouteDetail|null;visitDate:string;queuedAt:string;attempts:number};
async function tx<T>(store:string,mode:IDBTransactionMode,action:(value:IDBObjectStore)=>IDBRequest<T>){const db=await openSalesOfflineDatabase();try{return await new Promise<T>((resolve,reject)=>{const result=action(db.transaction(store,mode).objectStore(store));result.onsuccess=()=>resolve(result.result);result.onerror=()=>reject(result.error)})}finally{db.close()}}
const catalogKey=(businessId:string,warehouseId:string,customerId:string)=>`${businessId}:${warehouseId}:${customerId}`;
export async function saveSellerCatalog(businessId:string,warehouseId:string,customerId:string,items:SellerCatalogItem[]){const existing=await loadSellerCatalog(businessId,warehouseId,customerId);const merged=new Map(existing.map(item=>[item.productId,item]));for(const item of items)merged.set(item.productId,item);await tx(CATALOG,"readwrite",store=>store.put({key:catalogKey(businessId,warehouseId,customerId),items:[...merged.values()],updatedAt:new Date().toISOString()}))}
export async function loadSellerCatalog(businessId:string,warehouseId:string,customerId:string){return (await tx(CATALOG,"readonly",store=>store.get(catalogKey(businessId,warehouseId,customerId))) as {items:SellerCatalogItem[]}|undefined)?.items??[]}
export async function saveSellerDraft(key:string,request:SellerOrderRequest,quantities:Record<string,number>){await tx(DRAFTS,"readwrite",store=>store.put({key,request,quantities,updatedAt:new Date().toISOString()} satisfies Draft))}
export async function loadSellerDraft(key:string){return await tx(DRAFTS,"readonly",store=>store.get(key)) as Draft|undefined}
export async function removeSellerDraft(key:string){await tx(DRAFTS,"readwrite",store=>store.delete(key))}
export async function queueSellerOrder(request:SellerOrderRequest,route:SalesRouteDetail|null,visitDate:string){await tx(OUTBOX,"readwrite",store=>store.put({id:request.idempotencyKey,request:{...request,capturedOffline:true},route,visitDate,queuedAt:new Date().toISOString(),attempts:0} satisfies Queued));return{orderId:`local-${request.idempotencyKey}`,orderNumber:"Pendiente de sincronizar",status:"Confirmed",total:0,requiresReview:false,warnings:[]} satisfies SellerOrderResult}
export async function pendingSellerOrders(){return await tx(OUTBOX,"readonly",store=>store.getAll()) as Queued[]}
export async function flushSellerOrderOutbox(upload:(request:SellerOrderRequest)=>Promise<SellerOrderResult>,recordVisit:(routeId:string,request:{routeStopId:string;visitDate:string;status:"Visited";skipReason:null;orderId:string;occurredAt:string;idempotencyKey:string})=>Promise<SalesRouteVisit>){if(typeof navigator==="undefined"||!navigator.onLine)return{uploaded:0,pending:(await pendingSellerOrders()).length,reviews:[] as SellerOrderResult[]};let uploaded=0;const reviews:SellerOrderResult[]=[];for(const value of(await pendingSellerOrders()).sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt))){try{const result=await upload(value.request);if(result.requiresReview)reviews.push(result);if(value.request.routeStopId&&value.route)await recordVisit(value.route.routeId,{routeStopId:value.request.routeStopId,visitDate:value.visitDate,status:"Visited",skipReason:null,orderId:result.orderId,occurredAt:new Date().toISOString(),idempotencyKey:`visit-${value.id}`});await tx(OUTBOX,"readwrite",store=>store.delete(value.id));uploaded++}catch{await tx(OUTBOX,"readwrite",store=>store.put({...value,attempts:value.attempts+1}));break}}return{uploaded,pending:(await pendingSellerOrders()).length,reviews}}

export type SellerOfflinePreparation={key:string;businessId:string;businessName:string;warehouseId:string;warehouseCode:string;warehouseName:string;warehouseAllowsNegativeStockSales:boolean;date:string;preparedAt:string;routeCount:number;customerCount:number;catalogEntryCount:number};
export const sellerOfflinePreparationKey=(businessId:string,warehouseId:string,date:string)=>`${businessId}:${warehouseId}:${date}`;
export async function saveSellerOfflinePreparation(value:SellerOfflinePreparation){await tx(PREPARATIONS,"readwrite",store=>store.put(value))}
export async function loadSellerOfflinePreparation(businessId:string,warehouseId:string,date:string){return await tx(PREPARATIONS,"readonly",store=>store.get(sellerOfflinePreparationKey(businessId,warehouseId,date))) as SellerOfflinePreparation|undefined}
export async function loadLatestSellerOfflinePreparation(businessId:string,date:string){const values=await tx(PREPARATIONS,"readonly",store=>store.getAll()) as SellerOfflinePreparation[];return values.filter(value=>value.businessId===businessId&&value.date===date).sort((left,right)=>right.preparedAt.localeCompare(left.preparedAt))[0]}
