import type { SalesRouteDetail,SalesRouteVisit } from "@/services/api/routes";
import type { SellerCatalogItem,SellerOrderRequest,SellerOrderResult } from "@/services/api/seller-orders";
import { openSalesOfflineDatabase } from "@/lib/sales-offline-database";
import { sellerLocalModeKey, sellerOfflinePreparationKey } from "@/lib/seller-offline-scope";

export { sellerOfflinePreparationKey } from "@/lib/seller-offline-scope";

const CATALOG="seller-catalog",DRAFTS="seller-order-drafts",OUTBOX="seller-order-outbox",SNAPSHOTS="seller-order-snapshots",PREPARATIONS="seller-offline-preparations";
type Draft={key:string;request:SellerOrderRequest;quantities:Record<string,number>;updatedAt:string};
type Queued={id:string;userId:string;request:SellerOrderRequest;route:SalesRouteDetail|null;visitDate:string;queuedAt:string;attempts:number};
export type SellerOrderSnapshot={idempotencyKey:string;userId:string;orderId:string;orderNumber:string;businessId:string;warehouseId:string;routeId:string|null;customerName:string;total:number;lineCount:number;operationalDate:string;createdAt:string;status:string;synchronized:boolean};
async function tx<T>(store:string,mode:IDBTransactionMode,action:(value:IDBObjectStore)=>IDBRequest<T>){const db=await openSalesOfflineDatabase();try{return await new Promise<T>((resolve,reject)=>{const result=action(db.transaction(store,mode).objectStore(store));result.onsuccess=()=>resolve(result.result);result.onerror=()=>reject(result.error)})}finally{db.close()}}
const catalogKey=(businessId:string,warehouseId:string,customerId:string,version?:string)=>`${businessId}:${warehouseId}:${customerId}${version?`:${version}`:""}`;
const activeCatalogKey=(businessId:string,warehouseId:string)=>`${businessId}:${warehouseId}:active-version`;
async function activeCatalogVersion(businessId:string,warehouseId:string){return (await tx(CATALOG,"readonly",store=>store.get(activeCatalogKey(businessId,warehouseId))) as {version?:string}|undefined)?.version}
export async function saveSellerCatalog(businessId:string,warehouseId:string,customerId:string,items:SellerCatalogItem[]){const existing=await loadSellerCatalog(businessId,warehouseId,customerId),version=await activeCatalogVersion(businessId,warehouseId);const merged=new Map(existing.map(item=>[item.productId,item]));for(const item of items)merged.set(item.productId,item);await tx(CATALOG,"readwrite",store=>store.put({key:catalogKey(businessId,warehouseId,customerId,version),items:[...merged.values()],updatedAt:new Date().toISOString()}))}
export async function replaceSellerCatalog(businessId:string,warehouseId:string,customerId:string,version:string,items:SellerCatalogItem[]){await tx(CATALOG,"readwrite",store=>store.put({key:catalogKey(businessId,warehouseId,customerId,version),items,updatedAt:new Date().toISOString()}))}
export async function activateSellerCatalogVersion(businessId:string,warehouseId:string,version:string){await tx(CATALOG,"readwrite",store=>store.put({key:activeCatalogKey(businessId,warehouseId),version,updatedAt:new Date().toISOString()}));const prefix=`${businessId}:${warehouseId}:`,keepSuffix=`:${version}`,values=await tx(CATALOG,"readonly",store=>store.getAll()) as Array<{key:string}>;for(const value of values)if(value.key.startsWith(prefix)&&value.key!==activeCatalogKey(businessId,warehouseId)&&!value.key.endsWith(keepSuffix))await tx(CATALOG,"readwrite",store=>store.delete(value.key))}
export async function loadSellerCatalog(businessId:string,warehouseId:string,customerId:string){const version=await activeCatalogVersion(businessId,warehouseId);return (await tx(CATALOG,"readonly",store=>store.get(catalogKey(businessId,warehouseId,customerId,version))) as {items:SellerCatalogItem[]}|undefined)?.items??[]}
export async function saveSellerDraft(key:string,request:SellerOrderRequest,quantities:Record<string,number>){await tx(DRAFTS,"readwrite",store=>store.put({key,request,quantities,updatedAt:new Date().toISOString()} satisfies Draft))}
export async function loadSellerDraft(key:string){return await tx(DRAFTS,"readonly",store=>store.get(key)) as Draft|undefined}
export async function removeSellerDraft(key:string){await tx(DRAFTS,"readwrite",store=>store.delete(key))}
export async function saveSellerOrderSnapshot(value:SellerOrderSnapshot){await tx(SNAPSHOTS,"readwrite",store=>store.put(value))}
export async function loadSellerOrderSnapshots(userId:string,businessId:string,warehouseId:string,operationalDate:string){const values=await tx(SNAPSHOTS,"readonly",store=>store.getAll()) as SellerOrderSnapshot[];const scoped=values.filter(value=>value.userId===userId&&value.businessId===businessId&&value.warehouseId===warehouseId&&value.operationalDate===operationalDate).sort((left,right)=>right.createdAt.localeCompare(left.createdAt));return [...new Map(scoped.map(value=>[value.orderId,value])).values()]}
export async function queueSellerOrder(userId:string,request:SellerOrderRequest,route:SalesRouteDetail|null,visitDate:string){await tx(OUTBOX,"readwrite",store=>store.put({id:request.idempotencyKey,userId,request:{...request,capturedOffline:true},route,visitDate,queuedAt:new Date().toISOString(),attempts:0} satisfies Queued));return{orderId:`local-${request.idempotencyKey}`,orderNumber:"Pendiente de sincronizar",status:"Confirmed",total:0,requiresReview:false,warnings:[]} satisfies SellerOrderResult}
export async function pendingSellerOrders(userId:string){const values=await tx(OUTBOX,"readonly",store=>store.getAll()) as Queued[];return values.filter(value=>value.userId===userId)}
export async function flushSellerOrderOutbox(userId:string,upload:(request:SellerOrderRequest)=>Promise<SellerOrderResult>,recordVisit:(routeId:string,request:{routeStopId:string;visitDate:string;status:"Visited";skipReason:null;orderId:string;occurredAt:string;idempotencyKey:string})=>Promise<SalesRouteVisit>){if(typeof navigator==="undefined"||!navigator.onLine)return{uploaded:0,pending:(await pendingSellerOrders(userId)).length,reviews:[] as SellerOrderResult[]};let uploaded=0;const reviews:SellerOrderResult[]=[];for(const value of(await pendingSellerOrders(userId)).sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt))){try{const result=await upload(value.request);if(result.requiresReview)reviews.push(result);if(value.request.routeStopId&&value.route)await recordVisit(value.route.routeId,{routeStopId:value.request.routeStopId,visitDate:value.visitDate,status:"Visited",skipReason:null,orderId:result.orderId,occurredAt:new Date().toISOString(),idempotencyKey:`visit-${value.id}`});const snapshot=await tx(SNAPSHOTS,"readonly",store=>store.get(value.id)) as SellerOrderSnapshot|undefined;if(snapshot)await saveSellerOrderSnapshot({...snapshot,orderId:result.orderId,orderNumber:result.orderNumber,total:result.total,status:result.status,synchronized:true});await tx(OUTBOX,"readwrite",store=>store.delete(value.id));uploaded++}catch{await tx(OUTBOX,"readwrite",store=>store.put({...value,attempts:value.attempts+1}));break}}return{uploaded,pending:(await pendingSellerOrders(userId)).length,reviews}}

export type SellerOfflinePreparation={key:string;userId:string;businessId:string;businessName:string;warehouseId:string;warehouseCode:string;warehouseName:string;warehouseAllowsNegativeStockSales:boolean;date:string;preparedAt:string;routeCount:number;customerCount:number;catalogEntryCount:number;orderCount:number};
export async function saveSellerOfflinePreparation(value:SellerOfflinePreparation){await tx(PREPARATIONS,"readwrite",store=>store.put(value))}
export async function loadSellerOfflinePreparation(userId:string,businessId:string,warehouseId:string){return await tx(PREPARATIONS,"readonly",store=>store.get(sellerOfflinePreparationKey(userId,businessId,warehouseId))) as SellerOfflinePreparation|undefined}
export async function loadLatestSellerOfflinePreparation(userId:string){const values=await tx(PREPARATIONS,"readonly",store=>store.getAll()) as SellerOfflinePreparation[];return values.filter(value=>value.userId===userId).sort((left,right)=>right.preparedAt.localeCompare(left.preparedAt))[0]}
export function isSellerLocalModeEnabled(userId:string,businessId:string,warehouseId:string){try{return window.localStorage.getItem(sellerLocalModeKey(userId,businessId,warehouseId))==="1"}catch{return false}}
export function setSellerLocalMode(userId:string,businessId:string,warehouseId:string,enabled:boolean){try{const key=sellerLocalModeKey(userId,businessId,warehouseId);if(enabled)window.localStorage.setItem(key,"1");else window.localStorage.removeItem(key)}catch{/* IndexedDB preparation remains available even when localStorage is restricted. */}}
