"use client";

import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowLeft, ArrowUp, Banknote, Camera, Check, ChevronRight, CircleDollarSign, Map, MapPin, PackageCheck, PackageX, Plus, ReceiptText, Route, Search, ShieldCheck, Trash2, Truck, XCircle } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { RouteLocationMap } from "@/components/maps/route-location-map";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { dispatchesApi, type DeliveryDocument, type DeliveryResultInput, type DispatchExecution, type DispatchListItem, type DispatchPage } from "@/services/api/dispatches";

const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const executionKey=(id:string)=>["dispatches","execution",id] as const;
const deliveriesKey=["dispatches","my-deliveries"] as const;

export function TransportDispatchApp({canExecute=false}:{canExecute?:boolean}){
  const [selected,setSelected]=useState<DispatchListItem|null>(null);
  const query=useQuery({queryKey:deliveriesKey,queryFn:()=>dispatchesApi.page({page:1,pageSize:50}),refetchOnMount:"always"});
  if(selected)return <DispatchExecutionWorkspace dispatch={selected} canExecute={canExecute} onBack={()=>{setSelected(null);void query.refetch()}}/>;
  return <div className="mx-auto max-w-5xl space-y-5 pb-24">
    <section className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-teal-950 to-teal-700 p-6 text-white shadow-xl md:p-8">
      <div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-teal-200">Centro de entregas</p><h1 className="mt-1 text-3xl font-black tracking-tight">Mis despachos</h1><p className="mt-2 max-w-xl text-sm text-teal-50/80">Facturas, clientes, recaudos y novedades en un solo recorrido.</p></div><span className="rounded-2xl bg-white/10 p-3"><Truck className="h-7 w-7"/></span></div>
      <div className="mt-6 grid grid-cols-3 gap-2"><HeroMetric label="Asignados" value={query.data?.items.length??0}/><HeroMetric label="En ruta" value={query.data?.items.filter(x=>x.status==="InDelivery").length??0}/><HeroMetric label="Por liquidar" value={query.data?.items.filter(x=>x.status==="PendingSettlement").length??0}/></div>
    </section>
    {query.isLoading&&<div className="grid gap-3 md:grid-cols-2">{[0,1].map(item=><div key={item} className="h-48 animate-pulse rounded-3xl border bg-muted/50"/>)}</div>}
    {query.isError&&<div className="rounded-3xl border border-red-200 bg-red-50 p-6 text-center text-red-900"><strong className="block">No pudimos cargar tus despachos</strong><p className="mt-1 text-sm">Revisa la conexión y vuelve a intentarlo.</p><Button className="mt-4" variant="outline" onClick={()=>query.refetch()}>Reintentar</Button></div>}
    <div className="grid gap-3 md:grid-cols-2">{query.data?.items.map(item=><button key={item.dispatchId} onClick={()=>setSelected(item)} className="group rounded-3xl border bg-card p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-teal-300 hover:shadow-lg"><div className="flex items-center justify-between gap-3"><span className="rounded-xl bg-teal-50 p-2 text-teal-700"><Route className="h-5 w-5"/></span><DispatchBadge status={item.status}/></div><h2 className="mt-4 text-xl font-black">{item.dispatchNumber}</h2><p className="mt-1 text-sm text-muted-foreground">{item.scheduledDate} · {item.vehiclePlate??"Sin placa"}</p><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-sm font-semibold">{item.documentCount} entregas</span><ChevronRight className="h-5 w-5 transition group-hover:translate-x-1"/></div></button>)}</div>
    {!query.isLoading&&!query.data?.items.length&&<div className="rounded-3xl border border-dashed p-12 text-center"><PackageCheck className="mx-auto h-10 w-10 text-teal-600"/><h2 className="mt-3 font-bold">No tienes despachos asignados</h2><p className="mt-1 text-sm text-muted-foreground">Los nuevos despachos aparecerán automáticamente.</p></div>}
  </div>;
}

export function DispatchExecutionWorkspace({dispatch,canExecute,onBack}:{dispatch:DispatchListItem;canExecute:boolean;onBack:()=>void}){
  const cache=useQueryClient();const query=useQuery({queryKey:executionKey(dispatch.dispatchId),queryFn:()=>dispatchesApi.execution(dispatch.dispatchId)});
  const [tab,setTab]=useState<"list"|"map"|"expenses">("list"),[active,setActive]=useState<DeliveryDocument|null>(null),[expenseOpen,setExpenseOpen]=useState(false);
  const data=query.data;const completed=data?.documents.filter(x=>x.deliveryStatus!=="Pending").length??0;const total=data?.documents.length??0;
  const deliveryEnabled=canExecute&&(data?.status==="Released"||data?.status==="InDelivery");
  const awaitingRelease=!!data&&["Draft","Prepared","InVerification","Verified"].includes(data.status);
  const applyUpdate=(updated:DispatchExecution)=>{cache.setQueryData(executionKey(updated.dispatchId),updated);cache.setQueryData<DispatchPage>(deliveriesKey,current=>current?{...current,items:current.items.map(item=>item.dispatchId===updated.dispatchId?{...item,status:updated.status,updatedAt:new Date().toISOString()}:item)}:current);void cache.invalidateQueries({queryKey:deliveriesKey,refetchType:"inactive"})};
  const move=async(documentId:string,direction:-1|1)=>{if(!data)return;const ids=data.documents.map(x=>x.dispatchSourceDocumentId),index=ids.indexOf(documentId),target=index+direction;if(target<0||target>=ids.length)return;[ids[index],ids[target]]=[ids[target],ids[index]];try{applyUpdate(await dispatchesApi.reorder(data.dispatchId,ids,dispatch.rowVersion))}catch(error){toast.error(errorMessage(error,"No fue posible cambiar el orden."))}};
  return <div className="mx-auto max-w-6xl space-y-4 pb-28">
    <section className="sticky top-0 z-20 -mx-4 -mt-4 border-b bg-background px-4 pb-4 pt-4 shadow-sm md:static md:mx-0 md:mt-0 md:rounded-3xl md:border md:p-5 md:shadow-none">
      <div className="flex items-center gap-3"><Button size="icon" variant="ghost" onClick={onBack}><ArrowLeft className="h-5 w-5"/></Button><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h1 className="truncate text-xl font-black">{data?.dispatchNumber??dispatch.dispatchNumber}</h1><DispatchBadge status={data?.status??dispatch.status}/></div><p className="truncate text-xs text-muted-foreground">{data?.driverName??dispatch.driverName} · {data?.vehiclePlate??"Sin placa"}</p></div><span className="text-right"><strong className="block text-lg">{completed}/{total}</strong><small className="text-muted-foreground">entregas</small></span></div>
      <div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-teal-500 transition-all" style={{width:`${total?completed/total*100:0}%`}}/></div>
      <div className="mt-4 grid grid-cols-3 gap-1 rounded-2xl bg-muted p-1"><Tab active={tab==="list"} onClick={()=>setTab("list")} icon={ReceiptText}>Lista</Tab><Tab active={tab==="map"} onClick={()=>setTab("map")} icon={Map}>Mapa</Tab><Tab active={tab==="expenses"} onClick={()=>setTab("expenses")} icon={CircleDollarSign}>Gastos</Tab></div>
    </section>
    {query.isLoading&&<div className="space-y-3"><div className="h-36 animate-pulse rounded-3xl bg-muted/60"/><div className="h-36 animate-pulse rounded-3xl bg-muted/60"/></div>}
    {query.isError&&<div className="rounded-3xl border border-red-200 bg-red-50 p-6 text-center text-red-900"><strong className="block">No pudimos abrir este despacho</strong><p className="mt-1 text-sm">La información guardada no está disponible todavía.</p><Button className="mt-4" variant="outline" onClick={()=>query.refetch()}>Reintentar</Button></div>}
    {awaitingRelease&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong className="block">Este despacho todavía no está liberado</strong>Termina la verificación y pulsa “Liberar despacho”. Las entregas se habilitarán cuando quede listo para salir.</div>}
    {data&&tab==="list"&&<div className="space-y-3">{data.documents.map((document,index)=><DeliveryCard key={document.dispatchSourceDocumentId} document={document} index={index} total={data.documents.length} enabled={deliveryEnabled} onOpen={()=>deliveryEnabled&&setActive(document)} onMove={direction=>move(document.dispatchSourceDocumentId,direction)}/>)}</div>}
    {data&&tab==="map"&&<DispatchMap data={data} onOpen={document=>deliveryEnabled&&setActive(document)}/>}
    {data&&tab==="expenses"&&<DispatchExpensesPanel data={data} onExpense={canExecute&&!["PendingSettlement","SettlementProcessing","SettlementAttention","Closed","Cancelled"].includes(data.status)?()=>setExpenseOpen(true):undefined}/>}
    {data&&completed===total&&total>0&&!data.settlement&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-950"><strong className="block">Recorrido completo</strong><small>Entrega el recaudo, consignaciones, devoluciones y soportes en la empresa. El receptor realizará el cierre desde Despachos.</small></div>}
    {active&&data&&<DeliveryDialog dispatchId={data.dispatchId} document={active} onClose={()=>setActive(null)} onSaved={updated=>{setActive(null);applyUpdate(updated)}}/>}
    {expenseOpen&&data&&<ExpenseDialog dispatchId={data.dispatchId} onClose={()=>setExpenseOpen(false)} onSaved={updated=>{setExpenseOpen(false);applyUpdate(updated)}}/>}
  </div>;
}

function DeliveryCard({document,index,total,enabled,onOpen,onMove}:{document:DeliveryDocument;index:number;total:number;enabled:boolean;onOpen:()=>void;onMove:(direction:-1|1)=>void}){
  const done=document.deliveryStatus!=="Pending";
  return <Card className={`overflow-hidden rounded-3xl transition ${done?"border-emerald-200 bg-emerald-50/30":enabled?"hover:border-teal-300 hover:shadow-md":"opacity-75"}`}><CardContent className="p-0"><div className="flex gap-3 p-4"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl font-black ${done?"bg-emerald-500 text-white":"bg-slate-900 text-white"}`}>{done?<Check className="h-5 w-5"/>:index+1}</span><button disabled={!enabled} onClick={onOpen} className="min-w-0 flex-1 text-left disabled:cursor-not-allowed"><div className="flex items-start justify-between gap-2"><span><strong className="block truncate text-base">{document.customerName}</strong><small className="text-muted-foreground">{document.documentNumber} · {money.format(document.documentTotal)}</small></span><DeliveryBadge status={document.deliveryStatus}/></div><p className="mt-2 flex items-start gap-1 text-sm text-muted-foreground"><MapPin className="mt-0.5 h-4 w-4 shrink-0"/>{document.deliveryAddress??"Ubicación pendiente"}</p></button></div><div className="flex border-t bg-background/70"><Button variant="ghost" className="flex-1 rounded-none" disabled={!enabled||index===0||done} onClick={()=>onMove(-1)}><ArrowUp className="mr-1 h-4 w-4"/>Subir</Button><Button variant="ghost" className="flex-1 rounded-none" disabled={!enabled||index===total-1||done} onClick={()=>onMove(1)}><ArrowDown className="mr-1 h-4 w-4"/>Bajar</Button><Button variant="ghost" disabled={!enabled} className="flex-1 rounded-none text-teal-700" onClick={onOpen}>{done?"Ver":enabled?"Entregar":"Pendiente"}<ChevronRight className="ml-1 h-4 w-4"/></Button></div></CardContent></Card>;
}

function DispatchMap({data,onOpen}:{data:DispatchExecution;onOpen:(document:DeliveryDocument)=>void}){
  const stops=data.documents.map((document,index)=>({routeStopId:document.dispatchSourceDocumentId,sequence:index+1,customerName:document.customerName,siteName:document.documentNumber,addressLine:document.deliveryAddress??"Dirección pendiente",cityName:"",googleMapsUrl:null,latitude:document.destinationLatitude,longitude:document.destinationLongitude,document}));
  return <RouteLocationMap stops={stops} onOpen={stop=>onOpen(stop.document)} statusOf={stop=>stop.document.deliveryStatus==="NotDelivered"?"skipped":stop.document.deliveryStatus==="Pending"?"pending":"visited"}/>;
}
function DeliveryDialog({dispatchId,document,onClose,onSaved}:{dispatchId:string;document:DeliveryDocument;onClose:()=>void;onSaved:(updated:DispatchExecution)=>void}){
  const [status,setStatus]=useState<"Delivered"|"NotDelivered">(document.deliveryStatus==="NotDelivered"?"NotDelivered":"Delivered");
  const [paymentMethod,setPaymentMethod]=useState<"Cash"|"Deposit"|null>(document.creditAmount>0?null:"Cash");
  const [reason,setReason]=useState(document.reason??""),[notes,setNotes]=useState(document.notes??"");
  const [depositProof,setDepositProof]=useState<File|null>(null),[signedProof,setSignedProof]=useState<File|null>(null),[returns,setReturns]=useState<Record<number,string>>({});
  const [returnsOpen,setReturnsOpen]=useState(false);
  const reasons=useQuery({queryKey:["dispatches","reasons","NotDelivered"],queryFn:()=>dispatchesApi.reasons("NotDelivered")});
  const returnedTotal=document.lines.reduce((sum,line)=>sum+line.lineTotal/line.quantity*Number(returns[line.originalLineNumber]||0),0);
  const net=Math.max(0,document.documentTotal-returnedTotal);
  const immediateAmount=document.creditAmount>0?Math.max(0,net-document.creditAmount):net;
  const selectedReturns=Object.values(returns).filter(value=>Number(value)>0).length;
  const deliveryStatus=status==="NotDelivered"?"NotDelivered":selectedReturns>0?"PartiallyDelivered":"Delivered";
  useEffect(()=>{if(status==="NotDelivered"&&!reason&&reasons.data?.[0])setReason(reasons.data[0].name)},[status,reason,reasons.data]);
  const mutation=useMutation({mutationFn:async()=>{
    const returnInputs=document.lines.flatMap(line=>{const quantity=Number(returns[line.originalLineNumber]||0);return quantity>0?[{originalLineNumber:line.originalLineNumber,quantity,inventoryDisposition:"Sellable" as const,reasonCode:"CustomerReturn",reasonDescription:"Devuelto durante la entrega"}]:[]});
    let depositUrl:string|null=null,signedUrl:string|null=null;
    if(depositProof)depositUrl=(await dispatchesApi.uploadEvidence(dispatchId,depositProof)).url;
    if(signedProof)signedUrl=(await dispatchesApi.uploadEvidence(dispatchId,signedProof)).url;
    const payments:DeliveryResultInput["payments"]=[];
    if(deliveryStatus!=="NotDelivered"){
      const application=document.creditAmount>0?"CreditAdvance":"InvoicePayment";
      if(paymentMethod&&immediateAmount>0)payments.push({applicationType:application,paymentMethod,amount:immediateAmount,reference:null,evidenceUrl:paymentMethod==="Deposit"?depositUrl:null});
      if(document.creditAmount>0)payments.push({applicationType:"CreditDocument",paymentMethod:null,amount:0,reference:null,evidenceUrl:signedUrl});
    }
    const position=await currentPosition();
    return dispatchesApi.recordDelivery(dispatchId,{dispatchSourceDocumentId:document.dispatchSourceDocumentId,deliveryStatus,reason:deliveryStatus==="PartiallyDelivered"?"Devolución registrada durante la entrega":reason||null,notes:notes||null,latitude:position?.latitude??null,longitude:position?.longitude??null,occurredAt:new Date().toISOString(),idempotencyKey:crypto.randomUUID(),payments,returns:returnInputs});
  },onSuccess:updated=>{toast.success("Resultado de entrega guardado");onSaved(updated)},onError:error=>toast.error(errorMessage(error,"No fue posible guardar la entrega."))});
  const paymentRequired=deliveryStatus!=="NotDelivered"&&immediateAmount>0;
  const invalid=status==="NotDelivered"&&!reason.trim()||paymentRequired&&!paymentMethod||document.creditAmount>0&&deliveryStatus!=="NotDelivered"&&!signedProof;
  return <>
    <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[96dvh] max-w-3xl overflow-y-auto rounded-3xl">
      <DialogHeader><DialogTitle>Confirmar entrega</DialogTitle><DialogDescription>{document.customerName} · {document.documentNumber}</DialogDescription></DialogHeader>
      <div className="space-y-5">
        <section className="grid grid-cols-3 gap-2 rounded-2xl bg-slate-950 p-4 text-center text-white"><MiniMoney label="Factura" value={document.documentTotal}/><MiniMoney label="Devolución" value={returnedTotal}/><MiniMoney label="A recibir" value={net}/></section>
        <Field label="¿Cómo terminó la visita?"><div className="grid grid-cols-2 gap-3"><DeliveryResultButton active={status==="Delivered"} icon={PackageCheck} title="Entregado" onClick={()=>{setStatus("Delivered");setReason("")}}/><DeliveryResultButton active={status==="NotDelivered"} icon={XCircle} title="No se entregó" onClick={()=>setStatus("NotDelivered")}/></div></Field>
        {status==="NotDelivered"&&<Field label="Motivo"><Select value={reason} onValueChange={setReason}><SelectTrigger className="h-12 rounded-xl"><SelectValue placeholder={reasons.isLoading?"Cargando motivos…":"Selecciona el motivo"}/></SelectTrigger><SelectContent>{reasons.data?.map(item=><SelectItem key={item.dispatchReasonId} value={item.name}>{item.name}</SelectItem>)}</SelectContent></Select>{reasons.isError&&<p className="text-xs text-red-700">No fue posible cargar los motivos de no entrega.</p>}</Field>}
        {deliveryStatus!=="NotDelivered"&&<>
          <section className="flex items-center justify-between gap-3 rounded-2xl border p-4"><span><strong className="block">Devolución de productos</strong><small className="text-muted-foreground">{selectedReturns?`${selectedReturns} producto(s) · ${money.format(returnedTotal)}`:"La entrega no tiene devoluciones"}</small></span><Button type="button" variant={selectedReturns?"secondary":"outline"} onClick={()=>setReturnsOpen(true)}>{selectedReturns?<><PackageX className="mr-2 h-4 w-4"/>Editar</>:<><Plus className="mr-2 h-4 w-4"/>Agregar devolución</>}</Button></section>
          {immediateAmount>0?<Field label={`Pago recibido · ${money.format(immediateAmount)}`}><div className="grid grid-cols-2 gap-3"><PaymentButton active={paymentMethod==="Cash"} icon={Banknote} title="Efectivo" onClick={()=>{setPaymentMethod("Cash");setDepositProof(null)}}/><PaymentButton active={paymentMethod==="Deposit"} icon={ReceiptText} title="Consignación" onClick={()=>setPaymentMethod("Deposit")}/></div></Field>:<div className="rounded-2xl border bg-muted/30 p-4 text-sm"><strong className="block">Venta a crédito</strong>No se registra recaudo en esta entrega.</div>}
          {paymentMethod==="Deposit"&&immediateAmount>0&&<div><PhotoInput label="Foto de la consignación (opcional)" file={depositProof} onChange={setDepositProof}/><p className="mt-1 text-center text-xs text-muted-foreground">Puedes confirmar la entrega sin adjuntar una foto.</p></div>}
          {document.creditAmount>0&&<PhotoInput label="Factura firmada por el cliente" file={signedProof} onChange={setSignedProof}/>}
        </>}
        <Field label="Observaciones"><Textarea rows={2} className="min-h-20 resize-y" value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Novedades de la entrega (opcional)" maxLength={500}/></Field>
      </div>
      <DialogFooter><Button variant="outline" onClick={onClose}>Cancelar</Button><Button className="bg-teal-600 hover:bg-teal-700" disabled={mutation.isPending||invalid} onClick={()=>mutation.mutate()}>{mutation.isPending?"Guardando…":"Confirmar entrega"}</Button></DialogFooter>
    </DialogContent></Dialog>
    <ReturnsDialog document={document} open={returnsOpen} values={returns} onClose={()=>setReturnsOpen(false)} onSave={values=>{setReturns(values);setReturnsOpen(false)}}/>
  </>;
}

function ReturnsDialog({document,open,values,onClose,onSave}:{document:DeliveryDocument;open:boolean;values:Record<number,string>;onClose:()=>void;onSave:(values:Record<number,string>)=>void}){
  const [draft,setDraft]=useState(values);
  const [search,setSearch]=useState("");
  useEffect(()=>{if(open){setDraft(values);setSearch("")}},[open,values]);
  const selected=Object.values(draft).filter(value=>Number(value)>0).length;
  const amount=document.lines.reduce((sum,line)=>sum+line.lineTotal/line.quantity*Number(draft[line.originalLineNumber]||0),0);
  const normalizedSearch=search.trim().toLocaleLowerCase("es");
  const visibleLines=document.lines.filter(line=>Number(draft[line.originalLineNumber]||0)>0||!normalizedSearch||`${line.productCode} ${line.description}`.toLocaleLowerCase("es").includes(normalizedSearch));
  return <Dialog open={open} onOpenChange={value=>!value&&onClose()}><DialogContent className="max-h-[92dvh] max-w-2xl overflow-y-auto rounded-3xl"><DialogHeader><DialogTitle>Agregar productos devueltos</DialogTitle><DialogDescription>Busca y registra únicamente lo que el cliente devuelve.</DialogDescription></DialogHeader><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar por código o nombre"/></label><div className="space-y-2">{visibleLines.map(line=><div key={line.originalLineNumber} className="grid grid-cols-[minmax(0,1fr)_6rem] items-center gap-3 rounded-2xl border p-3"><span className="min-w-0"><strong className="block truncate text-sm">{line.productCode} · {line.description}</strong><small className="text-muted-foreground">Facturado: {line.quantity} · {money.format(line.lineTotal)}</small></span><Input aria-label={`Cantidad devuelta de ${line.description}`} inputMode="decimal" type="number" min="0" max={line.quantity} step="any" value={draft[line.originalLineNumber]??""} onChange={event=>setDraft(current=>({...current,[line.originalLineNumber]:event.target.value}))} placeholder="0"/></div>)}{visibleLines.length===0&&<p className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">No hay productos que coincidan con la búsqueda.</p>}</div><div className="flex items-center justify-between rounded-2xl bg-muted p-3"><span><small className="block text-muted-foreground">Devolución seleccionada</small><strong>{selected} producto(s) · {money.format(amount)}</strong></span>{selected>0&&<Button variant="ghost" size="sm" onClick={()=>setDraft({})}><Trash2 className="mr-1 h-4 w-4"/>Limpiar</Button>}</div><DialogFooter><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={()=>onSave(draft)}>Aplicar devolución</Button></DialogFooter></DialogContent></Dialog>;
}

function PaymentButton({active,icon:Icon,title,onClick}:{active:boolean;icon:typeof Banknote;title:string;onClick:()=>void}){return <button type="button" onClick={onClick} className={`flex h-16 items-center justify-center gap-2 rounded-2xl border-2 font-bold transition ${active?"border-teal-500 bg-teal-50 text-teal-800":"border-border bg-background hover:border-teal-300"}`}><Icon className="h-5 w-5"/>{title}{active&&<Check className="h-4 w-4"/>}</button>}
function DeliveryResultButton({active,icon:Icon,title,onClick}:{active:boolean;icon:typeof PackageCheck;title:string;onClick:()=>void}){return <button type="button" onClick={onClick} className={`flex min-h-20 flex-col items-center justify-center gap-2 rounded-2xl border-2 p-3 text-center text-sm font-bold transition ${active?"border-teal-500 bg-teal-50 text-teal-800":"border-border bg-background hover:border-teal-300"}`}><Icon className="h-6 w-6"/><span>{title}</span></button>}

function DispatchExpensesPanel({data,onExpense}:{data:DispatchExecution;onExpense?:()=>void}){
  return <div className="space-y-3"><div className="flex items-center justify-between gap-3"><span><h2 className="font-black">Gastos del recorrido</h2><p className="text-xs text-muted-foreground">{onExpense?"Regístralos en el momento en que ocurren.":"Consulta los gastos reportados por el transportador."}</p></span>{onExpense&&<Button onClick={onExpense}><Plus className="mr-2 h-4 w-4"/>Registrar gasto</Button>}</div>{data.expenses.length===0?<div className="rounded-3xl border border-dashed p-8 text-center"><ReceiptText className="mx-auto h-9 w-9 text-teal-600"/><strong className="mt-3 block">Sin gastos registrados</strong><p className="mt-1 text-sm text-muted-foreground">Peajes, parqueaderos y otros gastos aparecerán aquí.</p></div>:data.expenses.map(expense=><div key={expense.expenseId} className="flex items-center justify-between gap-3 rounded-2xl border bg-card p-4"><span><strong className="block">{expense.category} · {money.format(expense.amount)}</strong>{expense.description&&<small className="text-muted-foreground">{expense.description}</small>}</span><Badge variant={expense.approvalStatus==="Approved"?"default":expense.approvalStatus==="Rejected"?"destructive":"secondary"}>{expense.approvalStatus==="Pending"?"Pendiente":expense.approvalStatus==="Approved"?"Aprobado":"Rechazado"}</Badge></div>)}</div>;
}

export function DispatchSettlementPanel({data,onChanged}:{data:DispatchExecution;onChanged:(updated:DispatchExecution)=>void}){
  const summary=data.settlement;
  const cashCollected=data.documents.flatMap(item=>item.payments).filter(item=>item.paymentMethod==="Cash").reduce((sum,item)=>sum+item.amount,0);
  const depositsCollected=data.documents.flatMap(item=>item.payments).filter(item=>item.paymentMethod==="Deposit").reduce((sum,item)=>sum+item.amount,0);
  const returnsTotal=data.documents.reduce((documentSum,document)=>documentSum+document.returns.reduce((returnSum,item)=>{const line=document.lines.find(line=>line.originalLineNumber===item.originalLineNumber);return returnSum+(line?line.lineTotal/line.quantity*item.quantity:0)},0),0);
  const expectedCash=summary?.expectedCash??cashCollected;
  const [cash,setCash]=useState(String(expectedCash));
  const [notes,setNotes]=useState("");
  const [reviewing,setReviewing]=useState<string|null>(null);
  const [action,setAction]=useState<"close"|"settle"|null>(null);
  const [actionError,setActionError]=useState<string|null>(null);
  const difference=Number(cash||0)-expectedCash;
  useEffect(()=>setCash(String(expectedCash)),[expectedCash]);
  const close=async()=>{setAction("close");setActionError(null);try{const updated=await dispatchesApi.closeRoute(data.dispatchId,Number(cash||0),difference===0?null:notes);toast.success("Recorrido cerrado y enviado a liquidación");onChanged(updated)}catch(error){const message=errorMessage(error,"No fue posible cerrar el recorrido.");setActionError(message);toast.error(message)}finally{setAction(null)}};
  const settle=async()=>{setAction("settle");setActionError(null);try{const updated=await dispatchesApi.settle(data.dispatchId,Number(cash||0),difference===0?notes||null:notes);toast.success("Liquidación enviada. El estado se actualizará automáticamente.");onChanged(updated)}catch(error){const message=errorMessage(error,"No fue posible aceptar la liquidación.");setActionError(message);toast.error(message)}finally{setAction(null)}};
  const review=async(expenseId:string,decision:"Approved"|"Rejected",amount:number)=>{setReviewing(expenseId);try{const updated=await dispatchesApi.reviewExpense(data.dispatchId,expenseId,{decision,approvedAmount:decision==="Approved"?amount:null,notes:null,idempotencyKey:crypto.randomUUID()});toast.success(decision==="Approved"?"Gasto aprobado":"Gasto rechazado");onChanged(updated)}catch(error){toast.error(errorMessage(error,"No fue posible revisar el gasto."))}finally{setReviewing(null)}};
  const pending=data.documents.filter(item=>item.deliveryStatus==="Pending").length;
  const processing=summary?.status==="Processing"||data.status==="SettlementProcessing";
  const cashLocked=processing||data.status==="SettlementAttention"||data.status==="Closed";
  return <div className="space-y-4">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <MoneyCard icon={Banknote} label="Efectivo recaudado" value={summary?.grossCash??cashCollected}/>
      <MoneyCard icon={ReceiptText} label="Consignaciones" value={summary?.depositTotal??depositsCollected}/>
      <MoneyCard icon={PackageCheck} label="Devoluciones" value={summary?.returnTotal??returnsTotal}/>
      <MoneyCard icon={CircleDollarSign} label="Gastos aprobados" value={summary?.approvedCashExpenses??0}/>
    </div>
    <Card className="overflow-hidden rounded-3xl"><CardContent className="space-y-5 p-5">
      <div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Cuadre comercial obligatorio</p><p className={`text-3xl font-black ${(summary?.balanceDifference??0)===0?"text-emerald-600":"text-red-600"}`}>{money.format(summary?.balanceDifference??0)}</p></div><span className={`rounded-2xl p-3 ${(summary?.balanceDifference??0)===0?"bg-emerald-50 text-emerald-600":"bg-red-50 text-red-600"}`}><ShieldCheck className="h-7 w-7"/></span></div>
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Efectivo físico recibido"><Input inputMode="numeric" value={cash} disabled={cashLocked} onChange={event=>setCash(event.target.value)} className="h-12 text-lg font-bold"/></Field><div className={`rounded-2xl border p-3 ${difference>0?"border-emerald-200 bg-emerald-50":difference<0?"border-red-200 bg-red-50":"bg-muted/50"}`}><small>{difference>0?"Sobrante":difference<0?"Faltante":"Diferencia"}</small><strong className="block text-xl">{money.format(Math.abs(difference))}</strong></div></div>
      {difference!==0&&<Field label="Explicación obligatoria"><Input value={notes} onChange={event=>setNotes(event.target.value)} placeholder={difference>0?"¿Por qué sobró efectivo?":"¿Por qué faltó efectivo?"}/></Field>}
      <div>{!summary&&<Button className="h-12 w-full bg-teal-600 hover:bg-teal-700" disabled={action!==null||pending>0||difference!==0&&!notes.trim()} onClick={close}>{action==="close"?"Confirmando recepción…":"Confirmar recepción y cierre"}</Button>}{summary&&summary.status==="PendingReview"&&<Button className="h-12 w-full bg-teal-600 hover:bg-teal-700" disabled={action!==null||summary.balanceDifference!==0||data.expenses.some(item=>item.approvalStatus==="Pending")||difference!==0&&!notes.trim()} onClick={settle}>{action==="settle"?"Procesando…":"Aceptar liquidación"}</Button>}</div>
      {actionError&&<p role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-800">{actionError}</p>}
      {pending>0&&<p className="text-sm text-amber-700">Faltan {pending} entregas por registrar.</p>}
      {data.status==="SettlementAttention"&&<p className="rounded-2xl bg-red-50 p-3 text-sm font-medium text-red-800">La liquidación requiere atención. El motor conserva las mismas claves y seguirá reintentando sin duplicar documentos.</p>}
    </CardContent></Card>
    <section className="space-y-2"><h3 className="font-bold">Gastos presentados</h3>{data.expenses.length===0&&<div className="flex items-center gap-3 rounded-2xl border border-dashed bg-muted/20 p-4"><span className="rounded-2xl bg-teal-50 p-3 text-teal-700"><ReceiptText className="h-5 w-5"/></span><span><strong className="block text-sm">Sin gastos registrados</strong><small className="text-muted-foreground">El transportador no reportó gastos para este recorrido.</small></span></div>}{data.expenses.map(expense=><div key={expense.expenseId} className="flex flex-col gap-3 rounded-2xl border bg-card p-3 sm:flex-row sm:items-center sm:justify-between"><span><strong>{expense.category} · {money.format(expense.amount)}</strong>{expense.description&&<small className="block text-muted-foreground">{expense.description}</small>}{expense.evidenceUrl&&<a href={expense.evidenceUrl} target="_blank" rel="noreferrer" className="text-xs font-semibold text-teal-700">Ver soporte</a>}</span><div className="flex flex-wrap items-center gap-2"><Badge variant={expense.approvalStatus==="Approved"?"default":expense.approvalStatus==="Rejected"?"destructive":"secondary"}>{expense.approvalStatus==="Pending"?"Pendiente":expense.approvalStatus==="Approved"?"Aprobado":"Rechazado"}</Badge>{summary?.status==="PendingReview"&&expense.approvalStatus==="Pending"&&<><Button size="sm" variant="outline" disabled={reviewing===expense.expenseId} onClick={()=>review(expense.expenseId,"Rejected",expense.amount)}>Rechazar</Button><Button size="sm" disabled={reviewing===expense.expenseId} onClick={()=>review(expense.expenseId,"Approved",expense.amount)}>Aprobar</Button></>}</div></div>)}</section>
  </div>;
}

function ExpenseDialog({dispatchId,onClose,onSaved}:{dispatchId:string;onClose:()=>void;onSaved:(updated:DispatchExecution)=>void}){const [category,setCategory]=useState("Peaje"),[amount,setAmount]=useState(""),[description,setDescription]=useState(""),[proof,setProof]=useState<File|null>(null),[saving,setSaving]=useState(false);const save=async()=>{setSaving(true);try{const evidenceUrl=proof?(await dispatchesApi.uploadEvidence(dispatchId,proof)).url:null;const updated=await dispatchesApi.addExpense(dispatchId,{category,amount:Number(amount),description:description.trim()||null,evidenceUrl,idempotencyKey:crypto.randomUUID(),occurredAt:new Date().toISOString()});toast.success("Gasto enviado para aprobación");onSaved(updated)}catch(error){toast.error(errorMessage(error,"No fue posible guardar el gasto."))}finally{setSaving(false)}};return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[92dvh] overflow-y-auto rounded-3xl"><DialogHeader><DialogTitle>Otro gasto del despacho</DialogTitle><DialogDescription>El supervisor debe aprobarlo antes de liquidar.</DialogDescription></DialogHeader><div className="space-y-4"><Field label="Categoría"><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Peaje","Parqueadero","Combustible","Carga y descarga","Otro"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Valor"><Input inputMode="numeric" value={amount} onChange={event=>setAmount(event.target.value)}/></Field><Field label="Descripción (opcional)"><Input value={description} onChange={event=>setDescription(event.target.value)} placeholder="Agrega un detalle solo si hace falta"/></Field><PhotoInput label="Foto del soporte (opcional)" file={proof} onChange={setProof}/></div><DialogFooter><Button className="h-11 w-full sm:w-auto" variant="outline" onClick={onClose}>Cancelar</Button><Button className="h-11 w-full sm:w-auto" disabled={saving||Number(amount)<=0} onClick={save}>{saving?"Guardando…":"Guardar gasto"}</Button></DialogFooter></DialogContent></Dialog>}

function PhotoInput({label,file,onChange}:{label:string;file:File|null;onChange:(file:File|null)=>void}){return <label className="block cursor-pointer rounded-2xl border-2 border-dashed p-4 text-center transition hover:border-teal-400 hover:bg-teal-50/40"><Camera className="mx-auto h-6 w-6 text-teal-600"/><strong className="mt-1 block text-sm">{file?file.name:label}</strong><small className="text-muted-foreground">Tomar foto o elegir imagen</small><input className="sr-only" type="file" accept="image/*" capture="environment" onChange={event=>onChange(event.target.files?.[0]??null)}/></label>}
function HeroMetric({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-white/10 p-3 text-center backdrop-blur"><strong className="block text-2xl">{value}</strong><small className="text-teal-100">{label}</small></div>}
function Tab({active,onClick,icon:Icon,children}:{active:boolean;onClick:()=>void;icon:typeof Map;children:React.ReactNode}){return <button onClick={onClick} className={`flex items-center justify-center rounded-xl px-2 py-2 text-sm font-semibold transition ${active?"bg-background text-foreground shadow":"text-muted-foreground"}`}><Icon className="mr-1 h-4 w-4"/>{children}</button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function MiniMoney({label,value}:{label:string;value:number}){return <div><small className="text-slate-400">{label}</small><strong className="block text-sm sm:text-base">{money.format(value)}</strong></div>}
function MoneyCard({icon:Icon,label,value}:{icon:typeof Banknote;label:string;value:number}){return <Card className="rounded-3xl"><CardContent className="flex items-center gap-3 p-4"><span className="rounded-2xl bg-teal-50 p-3 text-teal-700"><Icon className="h-5 w-5"/></span><span><small className="text-muted-foreground">{label}</small><strong className="block text-lg">{money.format(value)}</strong></span></CardContent></Card>}
function DispatchBadge({status}:{status:string}){const labels:Record<string,string>={Released:"Listo para salir",InDelivery:"En ruta",PendingSettlement:"Por liquidar",SettlementProcessing:"Procesando",SettlementAttention:"Requiere atención",Closed:"Liquidado",Draft:"Borrador",Prepared:"Preparado",InVerification:"Verificando",Verified:"Verificado",Cancelled:"Cancelado"};return <Badge variant={status==="Closed"?"default":status==="SettlementAttention"||status==="Cancelled"?"destructive":"secondary"}>{labels[status]??status}</Badge>}
function DeliveryBadge({status}:{status:string}){const labels:Record<string,string>={Pending:"Pendiente",Delivered:"Entregado",PartiallyDelivered:"Parcial",NotDelivered:"No entregado"};return <Badge variant={status==="Delivered"?"default":status==="NotDelivered"?"destructive":"secondary"}>{labels[status]??status}</Badge>}
async function currentPosition(){if(typeof navigator==="undefined"||!navigator.geolocation)return null;return new Promise<{latitude:number;longitude:number}|null>(resolve=>navigator.geolocation.getCurrentPosition(value=>resolve({latitude:value.coords.latitude,longitude:value.coords.longitude}),()=>resolve(null),{enableHighAccuracy:true,timeout:7000,maximumAge:60000}))}
function errorMessage(error:unknown,fallback:string){return error&&typeof error==="object"&&"message" in error&&typeof error.message==="string"?error.message:fallback}
