import { apiClient, withPagedDefaults } from "./client";

export interface InventoryBalanceItem { warehouseId:string; warehouseCode:string; warehouseName:string; productId:string; productCode:string; productName:string; quantityOnHand:number; averageUnitCost:number|null; inventoryValue:number|null; updatedAt:string|null; }
export interface InventoryMovementItem { inventoryMovementId:string; warehouseId:string; warehouseName:string; productId:string; productCode:string; productName:string; documentId:string; documentType:string; documentNumber:string|null; movementType:string; quantityChange:number; quantityBefore:number; quantityAfter:number; recognizedUnitCost:number|null; valueChange:number|null; occurredAt:string; postedAt:string|null; }
export interface InventoryOperationItem { documentId:string; documentType:string; documentNumber:string|null; warehouseId:string; warehouseName:string; destinationWarehouseId:string|null; destinationWarehouseName:string|null; reasonCode:string; status:string; occurredAt:string; lineCount:number; totalValueChange:number|null; }
export interface InventoryOperationDetailLine { lineNumber:number; direction:string; productId:string; productCode:string; productName:string; quantity:number|null; systemQuantityAtBase:number|null; explicitUnitCost:number|null; allocationWeight:number|null; processedUnitCost:number|null; processedValue:number|null; }
export interface InventoryOperationDetail { documentId:string; documentType:string; documentNumber:string|null; warehouseId:string; warehouseName:string; destinationWarehouseId:string|null; destinationWarehouseName:string|null; reasonCode:string; reasonDescription:string; conversionType:string|null; baseInventorySequence:number|null; notes:string|null; status:string; occurredAt:string; createdAt:string; acceptedAt:string|null; processedAt:string|null; totalValueChange:number|null; lines:InventoryOperationDetailLine[]; }
export interface Page<T> { items:T[]; page:number; pageSize:number; totalCount:number; totalPages:number; }
export interface InventoryAcceptance { documentId:string; movementId:string; documentType:string; documentNumber:string; status:string; processingSequence:number; idempotentReplay:boolean; }
export interface InventoryProductItem { productId:string; productCode:string; reference:string|null; productName:string; unitCode:string; quantityOnHand:number; averageUnitCost:number|null; saleUnitPrice:number|null; }
export interface StockCountDraft { documentId:string; status:string; baseInventorySequence:number; lines:Array<{lineNumber:number;direction:string;productId:string;productCode:string;description:string;quantity:number;systemQuantityAtBase:number|null;explicitUnitCost:number|null;allocationWeight:number|null}>; }

export interface WarehouseMasterItem { warehouseId:string; code:string; name:string; allowNegativeStockSales:boolean; priceFormationCostBasis:string; isSystem:boolean; useForSales:boolean; useForGoodsReceipts:boolean; isInventoryVisible:boolean; isActive:boolean; }
export interface InventoryReasonItem { inventoryReasonId:string; operationType:string; code:string; name:string; isSystem:boolean; isActive:boolean; displayOrder:number; }

export const inventoryApi = {
  warehouses: () => apiClient.get<Array<{warehouseId:string;code:string;name:string}>>("/commerce/v1/inventory/warehouses"),
  warehouseMasters: () => apiClient.get<WarehouseMasterItem[]>("/commerce/v1/inventory/warehouse-masters"),
  saveWarehouse: (warehouseId:string|null, request:{name:string;allowNegativeStockSales:boolean;priceFormationCostBasis:string;useForSales:boolean;isActive:boolean}) => warehouseId ? apiClient.put<WarehouseMasterItem>(`/commerce/v1/inventory/warehouse-masters/${warehouseId}`,request) : apiClient.post<WarehouseMasterItem>("/commerce/v1/inventory/warehouse-masters",request),
  reasons: (params:{operationType?:string;includeInactive?:boolean;search?:string}={}) => apiClient.get<InventoryReasonItem[]>("/commerce/v1/inventory/reasons",params),
  saveReason: (inventoryReasonId:string|null, request:{operationType:string;name:string;isActive:boolean;displayOrder:number}) => inventoryReasonId ? apiClient.put<InventoryReasonItem>(`/commerce/v1/inventory/reasons/${inventoryReasonId}`,request) : apiClient.post<InventoryReasonItem>("/commerce/v1/inventory/reasons",request),
  products: (params:{warehouseId:string;search?:string;page?:number;pageSize?:number}) => apiClient.get<Page<InventoryProductItem>>("/commerce/v1/inventory/products",withPagedDefaults(params)),
  balances: (params:{warehouseId?:string;productId?:string;search?:string;onlyWithStock?:boolean;page?:number;pageSize?:number}) => apiClient.get<Page<InventoryBalanceItem>>("/commerce/v1/inventory/balances",withPagedDefaults(params)),
  movements: (params:{warehouseId?:string;productId?:string;search?:string;documentType?:string;movementType?:string;from?:string;to?:string;page?:number;pageSize?:number}) => apiClient.get<Page<InventoryMovementItem>>("/commerce/v1/inventory/movements",withPagedDefaults(params)),
  operations: (params:{warehouseId?:string;search?:string;documentType?:string;status?:string;from?:string;to?:string;page?:number;pageSize?:number}) => apiClient.get<Page<InventoryOperationItem>>("/commerce/v1/inventory/operations",withPagedDefaults(params)),
  operationDetail: (documentId:string) => apiClient.get<InventoryOperationDetail>(`/commerce/v1/inventory/operations/${documentId}`),
  confirmDamage: (request:{documentId:string;businessId:string;warehouseId:string;occurredAt:string;reasonCode:string;costCenterId:null;notes:string|null;lines:Array<{lineNumber:number;productId:string;quantity:number}>}) => apiClient.postIdempotent<InventoryAcceptance>("/commerce/v1/inventory-damages/confirm",request,`inventory-damage-${request.documentId}`),
  startCount: (request:{documentId:string;businessId:string;warehouseId:string;occurredAt:string;reasonCode:string;notes:string|null;productIds:string[]}) => apiClient.post<StockCountDraft>("/commerce/v1/stock-counts/start",request),
  confirmCount: (documentId:string,request:{businessId:string;lines:Array<{lineNumber:number;productId:string;countedQuantity:number}>}) => apiClient.postIdempotent<InventoryAcceptance>(`/commerce/v1/stock-counts/${documentId}/confirm`,request,`inventory-count-${documentId}`),
  confirmAdjustment: (request:{documentId:string;businessId:string;warehouseId:string;occurredAt:string;reasonCode:string;costCenterId:null;notes:string|null;lines:Array<{lineNumber:number;productId:string;quantityChange:number;explicitUnitCost:number|null}>}) => apiClient.postIdempotent<InventoryAcceptance>("/commerce/v1/inventory-adjustments/confirm",request,`inventory-adjustment-${request.documentId}`),
  confirmTransfer: (request:{documentId:string;businessId:string;sourceWarehouseId:string;destinationWarehouseId:string;occurredAt:string;reasonCode:string;notes:string|null;lines:Array<{lineNumber:number;productId:string;quantity:number}>}) => apiClient.postIdempotent<InventoryAcceptance>("/commerce/v1/warehouse-transfers/confirm",request,`inventory-transfer-${request.documentId}`),
  confirmConversion: (request:{documentId:string;businessId:string;warehouseId:string;occurredAt:string;conversionType:"SPLIT"|"MERGE";reasonCode:string;costCenterId:null;notes:string|null;lines:Array<{lineNumber:number;direction:"INPUT"|"OUTPUT";productId:string;quantity:number;allocationWeight:null}>}) => apiClient.postIdempotent<InventoryAcceptance>("/commerce/v1/product-conversions/confirm",request,`inventory-conversion-${request.documentId}`),
};
