import { apiClient, withPagedDefaults } from "./client";

export interface InventoryBalanceItem { warehouseId:string; warehouseCode:string; warehouseName:string; productId:string; productCode:string; productName:string; managesInventory:boolean; quantityOnHand:number; unitCost:number|null; averageUnitCost:number|null; inventoryValue:number|null; updatedAt:string|null; }
export interface InventoryMovementItem { inventoryMovementId:string; warehouseId:string; warehouseName:string; productId:string; productCode:string; productName:string; documentId:string; documentType:string; documentNumber:string|null; movementType:string; quantityChange:number; quantityBefore:number; quantityAfter:number; recognizedUnitCost:number|null; valueChange:number|null; occurredAt:string; postedAt:string|null; }
export interface InventoryOperationItem { documentId:string; documentType:string; documentNumber:string|null; warehouseId:string; warehouseName:string; destinationWarehouseId:string|null; destinationWarehouseName:string|null; reasonCode:string; status:string; occurredAt:string; lineCount:number; totalValueChange:number|null; conversionInputEquivalent:number|null; conversionOutputEquivalent:number|null; conversionLossQuantity:number|null; conversionLossPercent:number|null; conversionMaximumLossPercent:number|null; }
export interface InventoryOperationDetailLine { lineNumber:number; direction:string; productId:string; productCode:string; productName:string; quantity:number|null; preCountQuantity:number|null; systemQuantityAtBase:number|null; explicitUnitCost:number|null; allocationWeight:number|null; processedUnitCost:number|null; processedValue:number|null; conversionFactor:number|null; conversionEquivalentQuantity:number|null; dispatchedQuantity:number|null; receivedQuantity:number|null; }
export interface InventoryOperationDetail { documentId:string; documentType:string; documentNumber:string|null; warehouseId:string; warehouseName:string; destinationWarehouseId:string|null; destinationWarehouseName:string|null; reasonCode:string; reasonDescription:string; conversionType:string|null; baseInventorySequence:number|null; notes:string|null; status:string; occurredAt:string; createdAt:string; acceptedAt:string|null; processedAt:string|null; totalValueChange:number|null; lines:InventoryOperationDetailLine[]; conversionFamilyRootProductId:string|null; conversionInputEquivalent:number|null; conversionOutputEquivalent:number|null; conversionLossQuantity:number|null; conversionLossPercent:number|null; conversionMaximumLossPercent:number|null; }
export interface Page<T> { items:T[]; page:number; pageSize:number; totalCount:number; totalPages:number; }
export interface InventoryAcceptance { documentId:string; movementId:string; documentType:string; documentNumber:string; status:string; processingSequence:number; idempotentReplay:boolean; }
export interface WarehouseTransferPendingItem { transferId:string;documentNumber:string;sourceWarehouseId:string;sourceWarehouseName:string;destinationWarehouseId:string;destinationWarehouseName:string;status:string;dispatchedAt:string;lineCount:number;dispatchedQuantity:number;receivedQuantity:number;pendingQuantity:number;rowVersion:string; }
export interface WarehouseTransferDetailLine { lineNumber:number;productId:string;productCode:string;productName:string;dispatchedQuantity:number;receivedQuantity:number;pendingQuantity:number; }
export interface WarehouseTransferDetail { transferId:string;documentNumber:string;sourceWarehouseId:string;sourceWarehouseName:string;destinationWarehouseId:string;destinationWarehouseName:string;reasonCode:string;notes:string|null;status:string;dispatchedAt:string;receivedAt:string|null;rowVersion:string;lines:WarehouseTransferDetailLine[]; }
export interface InventoryProductItem { productId:string; productCode:string; reference:string|null; productName:string; unitCode:string; quantityOnHand:number; averageUnitCost:number|null; saleUnitPrice:number|null; productCategoryId?:string|null; productCategoryName?:string|null; familyRootProductId?:string; conversionFactor?:number; maximumLossPercent?:number; }
interface ProductConversionProductItem { productId:string; productCode:string; reference:string|null; productName:string; unitCode:string; quantityOnHand:number; familyRootProductId:string; conversionFactor:number; maximumLossPercent:number; }
export interface StockCountDraft { documentId:string; status:string; baseInventorySequence:number; lines:Array<{lineNumber:number;direction:string;productId:string;productCode:string;description:string;quantity:number;preCountQuantity:number|null;systemQuantityAtBase:number|null;explicitUnitCost:number|null;allocationWeight:number|null}>; }

export interface WarehouseMasterItem { warehouseId:string; code:string; name:string; allowNegativeStockSales:boolean; priceFormationCostBasis:string; isSystem:boolean; useForSales:boolean; useForGoodsReceipts:boolean; isInventoryVisible:boolean; isActive:boolean; }
export interface InventoryReasonItem { inventoryReasonId:string; operationType:string; code:string; name:string; isSystem:boolean; isActive:boolean; displayOrder:number; }
export interface InventoryPhysicalCountDraftLine { productId:string;productCode:string;productName:string;systemQuantity:number;initialQuantity:number|null;verificationQuantity:number|null;pendingReason:string|null;initialCountedAt:string|null;verifiedAt:string|null; }
export interface InventoryPhysicalCountDraft { draftId:string;name:string;ownerUserId:string;status:string;version:number;createdAt:string;updatedAt:string;captureStage:"Count"|"Recount";lines:InventoryPhysicalCountDraftLine[]; }
export interface InventoryPhysicalCountDetail { inventoryPhysicalCountId:string;warehouseId:string;warehouseName:string;scopeType:string;reasonCode:string;notes:string|null;baseInventorySequence:number;status:string;createdByUserId:string;createdAt:string;startedAt:string|null;reviewStartedAt:string|null;closedAt:string|null;finalInventoryOperationId:string|null;finalDocumentNumber:string|null;drafts:InventoryPhysicalCountDraft[]; }
export interface InventoryPhysicalCountItem { inventoryPhysicalCountId:string;warehouseId:string;warehouseName:string;scopeType:string;reasonCode:string;status:string;draftCount:number;productCount:number;initialCountedCount:number;verifiedCount:number;pendingCount:number;createdAt:string;finalDocumentNumber:string|null; }
export interface InventoryPhysicalCountDraftSummary { inventoryPhysicalCountId:string;draftId:string;name:string;warehouseId:string;warehouseName:string;scopeType:string;ownerUserId:string;status:string;version:number;productCount:number;countedProductCount:number;updatedAt:string; }
export type InventoryPhysicalCountDraftPage = Page<InventoryPhysicalCountDraftSummary>;
export interface InventoryReconciliationSource { draftId:string;draftName:string;ownerUserId:string;initialQuantity:number;verificationQuantity:number|null;finalQuantity:number; }
export interface InventoryReconciliationProduct { productId:string;productCode:string;productName:string;status:"Counted"|"Uncounted";proposedQuantity:number|null;systemQuantity:number;unitCost:number|null;averageUnitCost:number|null;sources:InventoryReconciliationSource[]; }
export interface InventoryReconciliationDetail { reconciliationId:string;inventoryPhysicalCountId:string;snapshotInventorySequence:number;status:string;createdAt:string;createdByUserId:string;isStale:boolean;countedApplicationStatus:string|null;countedDocumentId:string|null;countedDocumentNumber:string|null;uncountedApplicationStatus:string|null;uncountedDocumentId:string|null;uncountedDocumentNumber:string|null;drafts:Array<{draftId:string;name:string;ownerUserId:string;version:number;countedProducts:number;pendingProducts:number}>;products:InventoryReconciliationProduct[]; }

export const inventoryApi = {
  warehouses: () => apiClient.get<Array<{warehouseId:string;code:string;name:string}>>("/commerce/v1/inventory/warehouses"),
  warehouseMasters: () => apiClient.get<WarehouseMasterItem[]>("/commerce/v1/inventory/warehouse-masters"),
  saveWarehouse: (warehouseId:string|null, request:{name:string;allowNegativeStockSales:boolean;priceFormationCostBasis:string;useForSales:boolean;isActive:boolean}) => warehouseId ? apiClient.put<WarehouseMasterItem>(`/commerce/v1/inventory/warehouse-masters/${warehouseId}`,request) : apiClient.post<WarehouseMasterItem>("/commerce/v1/inventory/warehouse-masters",request),
  reasons: (params:{operationType?:string;includeInactive?:boolean;search?:string}={}) => apiClient.get<InventoryReasonItem[]>("/commerce/v1/inventory/reasons",params),
  businessReasons: (reasonType:string) => apiClient.get<InventoryReasonItem[]>("/commerce/v1/reasons",{reasonType}),
  saveReason: (inventoryReasonId:string|null, request:{operationType:string;name:string;isActive:boolean;displayOrder:number}) => inventoryReasonId ? apiClient.put<InventoryReasonItem>(`/commerce/v1/inventory/reasons/${inventoryReasonId}`,request) : apiClient.post<InventoryReasonItem>("/commerce/v1/inventory/reasons",request),
  products: (params:{warehouseId:string;productCategoryId?:string;search?:string;page?:number;pageSize?:number}) => apiClient.get<Page<InventoryProductItem>>("/commerce/v1/inventory/products",withPagedDefaults(params)),
  conversionProducts: async (params:{warehouseId:string;familyRootProductId?:string;search?:string;page?:number;pageSize?:number}) => {
    const page = await apiClient.get<Page<ProductConversionProductItem>>("/commerce/v1/inventory/conversion-products",withPagedDefaults(params));
    return { ...page, items: page.items.map((item): InventoryProductItem => ({ ...item, averageUnitCost: null, saleUnitPrice: null })) };
  },
  balances: (params:{warehouseId?:string;productId?:string;search?:string;onlyWithStock?:boolean;page?:number;pageSize?:number}) => apiClient.get<Page<InventoryBalanceItem>>("/commerce/v1/inventory/balances",withPagedDefaults(params)),
  movements: (params:{warehouseId?:string;productId?:string;search?:string;documentType?:string;movementType?:string;from?:string;to?:string;page?:number;pageSize?:number}) => apiClient.get<Page<InventoryMovementItem>>("/commerce/v1/inventory/movements",withPagedDefaults(params)),
  operations: (params:{warehouseId?:string;search?:string;documentType?:string;status?:string;from?:string;to?:string;reasonCode?:string;destinationWarehouseId?:string;supplierId?:string;purchaseEvidenceType?:string;page?:number;pageSize?:number}) => apiClient.get<Page<InventoryOperationItem>>("/commerce/v1/inventory/operations",withPagedDefaults(params)),
  operationDetail: (documentId:string) => apiClient.get<InventoryOperationDetail>(`/commerce/v1/inventory/operations/${documentId}`),
  physicalCounts: (params:{warehouseId?:string;search?:string;status?:string;page?:number;pageSize?:number}) => apiClient.get<Page<InventoryPhysicalCountItem>>("/commerce/v1/inventory/physical-counts",withPagedDefaults(params)),
  physicalCountDrafts: (params:{warehouseId?:string;search?:string;from?:string;to?:string;page?:number;pageSize?:number}) => apiClient.get<InventoryPhysicalCountDraftPage>("/commerce/v1/inventory/physical-count-drafts",withPagedDefaults(params)),
  physicalCount: (countId:string) => apiClient.get<InventoryPhysicalCountDetail>(`/commerce/v1/inventory/physical-counts/${countId}`),
  createPhysicalCount: (request:{inventoryPhysicalCountId:string;businessId:string;warehouseId:string;scopeType:"General"|"Partial";reasonCode:string;notes:string|null;initialDraftName:string;productIds:string[]}) => apiClient.post<InventoryPhysicalCountDetail>("/commerce/v1/inventory/physical-counts",request),
  createPhysicalCountDraft: (countId:string,request:{businessId:string;draftId:string;name:string;productIds:string[]}) => apiClient.post<InventoryPhysicalCountDetail>(`/commerce/v1/inventory/physical-counts/${countId}/drafts`,request),
  savePhysicalCountDraft: (countId:string,draftId:string,request:{businessId:string;version:number;name:string;lines:Array<{productId:string;initialQuantity:number|null;verificationQuantity:number|null;pendingReason:string|null}>;readyForReconciliation:boolean;captureStage:"Count"|"Recount"}) => apiClient.put<InventoryPhysicalCountDetail>(`/commerce/v1/inventory/physical-counts/${countId}/drafts/${draftId}`,request),
  reconciliation: (countId:string) => apiClient.get<InventoryReconciliationDetail>(`/commerce/v1/inventory/physical-counts/${countId}/reconciliation`),
  prepareReconciliation: (countId:string,request:{businessId:string;drafts:Array<{draftId:string;version:number}>}) => apiClient.post<InventoryReconciliationDetail>(`/commerce/v1/inventory/physical-counts/${countId}/reconciliations`,request),
  saveReconciliationDraft: (countId:string,reconciliationId:string,request:{businessId:string;section:"Counted"|"Uncounted";draftId:string;name:string}) => apiClient.post<InventoryPhysicalCountDetail>(`/commerce/v1/inventory/physical-counts/${countId}/reconciliations/${reconciliationId}/drafts`,request),
  applyReconciliation: (countId:string,reconciliationId:string,request:{businessId:string;section:"Counted"|"Uncounted"}) => apiClient.post<InventoryPhysicalCountDetail>(`/commerce/v1/inventory/physical-counts/${countId}/reconciliations/${reconciliationId}/apply`,request),
  confirmDamage: (request:{documentId:string;businessId:string;warehouseId:string;occurredAt:string;reasonCode:string;costCenterId:null;notes:string|null;lines:Array<{lineNumber:number;productId:string;quantity:number}>}) => apiClient.postIdempotent<InventoryAcceptance>("/commerce/v1/inventory-damages/confirm",request,`inventory-damage-${request.documentId}`),
  startCount: (request:{documentId:string;businessId:string;warehouseId:string;occurredAt:string;reasonCode:string;notes:string|null;lines:Array<{productId:string;preCountQuantity:number}>}) => apiClient.post<StockCountDraft>("/commerce/v1/stock-counts/start",request),
  confirmCount: (documentId:string,request:{businessId:string;lines:Array<{lineNumber:number;productId:string;countedQuantity:number}>}) => apiClient.postIdempotent<InventoryAcceptance>(`/commerce/v1/stock-counts/${documentId}/confirm`,request,`inventory-count-${documentId}`),
  applyCount: (request:{documentId:string;businessId:string;warehouseId:string;occurredAt:string;reasonCode:string;notes:string|null;lines:Array<{productId:string;initialQuantity:number;countedQuantity:number}>}) => apiClient.postIdempotent<InventoryAcceptance>("/commerce/v1/stock-counts/apply",request,`inventory-count-${request.documentId}`),
  confirmAdjustment: (request:{documentId:string;businessId:string;warehouseId:string;occurredAt:string;reasonCode:string;costCenterId:null;notes:string|null;lines:Array<{lineNumber:number;productId:string;quantityChange:number;explicitUnitCost:number|null}>}) => apiClient.postIdempotent<InventoryAcceptance>("/commerce/v1/inventory-adjustments/confirm",request,`inventory-adjustment-${request.documentId}`),
  dispatchTransfer: (request:{documentId:string;businessId:string;sourceWarehouseId:string;destinationWarehouseId:string;occurredAt:string;reasonCode:string;notes:string|null;lines:Array<{lineNumber:number;productId:string;dispatchedQuantity:number}>}) => apiClient.postIdempotent<InventoryAcceptance>("/commerce/v1/warehouse-transfers/dispatch",request,`inventory-transfer-dispatch-${request.documentId}`),
  pendingTransfers: (params:{destinationWarehouseId?:string;search?:string;page?:number;pageSize?:number}={}) => apiClient.get<Page<WarehouseTransferPendingItem>>("/commerce/v1/warehouse-transfers/pending",withPagedDefaults(params)),
  transfer: (transferId:string) => apiClient.get<WarehouseTransferDetail>(`/commerce/v1/warehouse-transfers/${transferId}`),
  receiveTransfer: (transferId:string,request:{receiptId:string;businessId:string;occurredAt:string;differenceReasonCode:string|null;notes:string|null;rowVersion:string;lines:Array<{lineNumber:number;productId:string;receivedQuantity:number}>}) => apiClient.postIdempotent<InventoryAcceptance>(`/commerce/v1/warehouse-transfers/${transferId}/receipts`,request,`inventory-transfer-receipt-${request.receiptId}`),
  confirmConversion: (request:{documentId:string;businessId:string;warehouseId:string;occurredAt:string;conversionType:"SPLIT"|"MERGE";reasonCode:string;costCenterId:null;notes:string|null;lines:Array<{lineNumber:number;direction:"INPUT"|"OUTPUT";productId:string;quantity:number;allocationWeight:null}>}) => apiClient.postIdempotent<InventoryAcceptance>("/commerce/v1/product-conversions/confirm",request,`inventory-conversion-${request.documentId}`),
};
