<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auraly.Contracts.Returns\Auraly.Contracts.Returns.csproj" />
    <ProjectReference Include="..\Auraly.Domain.Returns\Auraly.Domain.Returns.csproj" />
    <ProjectReference Include="..\..\DocumentProcessing\Auraly.Application.DocumentProcessing\Auraly.Application.DocumentProcessing.csproj" />
  </ItemGroup>
</Project>
