<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Authorization\Auraly.Contracts.Authorization\Auraly.Contracts.Authorization.csproj" />
    <ProjectReference Include="..\Auraly.Contracts.Cash\Auraly.Contracts.Cash.csproj" />
    <ProjectReference Include="..\Auraly.Domain.Cash\Auraly.Domain.Cash.csproj" />
  </ItemGroup>
</Project>
