"use client";

import { useMemo,useRef,useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { Plus,Search } from "lucide-react";
import { toast } from "sonner";
import { DataTable } from "@/components/tables/data-table";
import { PartyRoleSelect } from "@/components/parties/party-role-select";
import { SupplierProductPicker } from "@/components/products/supplier-product-picker";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useConfirmPurchaseOrder,usePurchaseOrders,useSavePurchaseOrder,useClosePurchaseOrder } from "@/hooks/use-purchase-orders";
import { useGoodsReceiptOptions } from "@/hooks/use-goods-receipts";
import { purchaseOrdersApi,type PurchaseOrderDetail,type PurchaseOrderLineRequest,type PurchaseOrderListItem,type PurchaseOrderStatus } from "@/services/api/purchase-orders";
import type { GoodsReceiptProduct } from "@/services/api/goods-receipts";
import { useBusinessContextStore } from "@/stores/business-context-store";
import { useAuthStore } from "@/stores/auth-store";
import { formatCurrency,formatDateTime } from "@/lib/utils";

type Draft={id:string;warehouseId:string;supplierId:string;orderedAt:string;expectedAt:string;notes:string;token:string|null;lines:PurchaseOrderLineRequest[]};
const labels:Record<PurchaseOrderStatus,string>={Draft:"Borrador",Open:"Abierta",PartiallyReceived:"Recibida parcialmente",Received:"Recibida",Closed:"Cerrada",Cancelled:"Cancelada"};

export default function PurchaseOrdersPage(){
  const businessId=useBusinessContextStore(s=>s.selectedBusinessId);const permissions=useAuthStore(s=>new Set(s.user?.permissions??[]));
  const [page,setPage]=useState(1),[search,setSearch]=useState(""),[status,setStatus]=useState<PurchaseOrderStatus|"all">("all");
  const [draft,setDraft]=useState<Draft>(),[detail,setDetail]=useState<PurchaseOrderDetail>();
  const list=usePurchaseOrders({page,pageSize:25,search:search||undefined,status:status==="all"?undefined:status});
  const columns=useMemo<ColumnDef<PurchaseOrderListItem>[]>(()=>[
    {accessorKey:"documentNumber",header:"Orden",cell:({row})=><div><b>{row.original.documentNumber??"Borrador sin numerar"}</b><p className="text-xs text-muted-foreground">{formatDateTime(row.original.orderedAt)}</p></div>},
    {accessorKey:"supplierName",header:"Proveedor",cell:({row})=>row.original.supplierName??"Por seleccionar"},
    {accessorKey:"warehouseName",header:"Bodega",cell:({row})=>row.original.warehouseName??"Por seleccionar"},
    {accessorKey:"grandTotal",header:"Total",cell:({row})=>formatCurrency(row.original.grandTotal)},
    {accessorKey:"fulfillmentPercent",header:"Cumplimiento",cell:({row})=>`${row.original.fulfillmentPercent.toFixed(1)} %`},
    {accessorKey:"status",header:"Estado",cell:({row})=><Badge variant="outline">{labels[row.original.status]}</Badge>},
  ],[]);
  const open=async(item:PurchaseOrderListItem)=>{try{const value=await purchaseOrdersApi.get(item.purchaseOrderId);if(value.status==="Draft"&&permissions.has("purchasing.purchase-orders.create"))setDraft(fromDetail(value));else setDetail(value);}catch{toast.error("No fue posible recuperar la orden.")}};
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Compras</p><h1 className="text-3xl font-semibold">Órdenes de compra</h1><p className="text-muted-foreground">Planea el abastecimiento con inventario, pedidos en camino y rotación persistida por bodega.</p></div>{permissions.has("purchasing.purchase-orders.create")&&<Button onClick={()=>setDraft(empty())}><Plus className="mr-2 h-4 w-4"/>Nueva orden</Button>}</header>
    <section className="grid gap-3 rounded-2xl border bg-card p-4 md:grid-cols-[1fr_15rem]"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Número o proveedor"/></div><Select value={status} onValueChange={v=>setStatus(v as PurchaseOrderStatus|"all")}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos los estados</SelectItem>{Object.entries(labels).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></section>
    <DataTable columns={columns} data={list.data?.items??[]} isLoading={list.isLoading} page={list.data?.page} pageSize={25} pageCount={list.data?.totalPages} totalItems={list.data?.totalCount} onPaginationChange={setPage} onRowClick={open} enableRowSelection={false}/>
    {draft&&businessId&&<OrderEditor draft={draft} businessId={businessId} onChange={setDraft} onClose={()=>setDraft(undefined)}/>} {detail&&<OrderDetail detail={detail} canClose={permissions.has("purchasing.purchase-orders.close")} onClose={()=>setDetail(undefined)} onRefresh={async()=>setDetail(await purchaseOrdersApi.get(detail.purchaseOrderId))}/>}</div>;
}

function OrderEditor({draft,businessId,onChange,onClose}:{draft:Draft;businessId:string;onChange:(v:Draft)=>void;onClose:()=>void}){
  const options=useGoodsReceiptOptions(),save=useSavePurchaseOrder(),confirm=useConfirmPurchaseOrder();
  const [includeUnassociated,setIncludeUnassociated]=useState(false);
  const productSearchRef=useRef<HTMLInputElement>(null),quantityRefs=useRef(new Map<string,HTMLInputElement>());
  const total=draft.lines.reduce((sum,x)=>sum+(x.orderedQuantity*x.unitCost-x.discountAmount)*(1+x.taxRate/100),0);
  const patch=(v:Partial<Draft>)=>onChange({...draft,...v});
  const focusQuantity=(productId:string)=>requestAnimationFrame(()=>requestAnimationFrame(()=>{const input=quantityRefs.current.get(productId);input?.focus();input?.select();input?.scrollIntoView({block:"nearest"})}));
  const add=(p:GoodsReceiptProduct)=>{const existing=draft.lines.find(x=>x.productId===p.productId);if(existing){focusQuantity(existing.productId);return}const line={lineId:crypto.randomUUID(),lineNumber:draft.lines.length+1,productId:p.productId,description:p.name,orderedQuantity:p.unitsPerPresentation,unitCost:p.latestUnitCost??0,discountAmount:0,taxCode:p.taxCode,taxRate:p.taxRate,taxTreatment:p.taxTreatment,presentationName:p.purchasePresentationName,presentationQuantity:1,unitsPerPresentation:p.unitsPerPresentation};patch({lines:[...draft.lines,line]});focusQuantity(line.productId)};
  const moveQuantity=(productId:string,offset:number)=>{const index=draft.lines.findIndex(x=>x.productId===productId);if(index<0||!draft.lines.length)return;const next=Math.min(Math.max(index+offset,0),draft.lines.length-1);quantityRefs.current.get(draft.lines[next].productId)?.focus()};
  const request=()=>({purchaseOrderId:draft.id,businessId,warehouseId:draft.warehouseId||null,supplierId:draft.supplierId||null,orderedAt:new Date(draft.orderedAt).toISOString(),expectedAt:draft.expectedAt?new Date(draft.expectedAt).toISOString():null,currencyCode:"COP",notes:draft.notes||null,lines:draft.lines,concurrencyToken:draft.token});
  const persist=async()=>{try{const result=await save.mutateAsync(request());onChange(fromDetail(result));toast.success("Borrador guardado");return result}catch{toast.error("No se pudo guardar el borrador");return null}};
  const finish=async()=>{if(!draft.warehouseId||!draft.supplierId||!draft.lines.length)return toast.error("Selecciona proveedor, bodega y productos.");let token=draft.token;if(!token){const saved=await persist();if(!saved)return;token=saved.concurrencyToken}try{await confirm.mutateAsync({...request(),warehouseId:draft.warehouseId,supplierId:draft.supplierId,draftConcurrencyToken:token});toast.success("Orden de compra confirmada");onClose()}catch{toast.error("No fue posible confirmar la orden")}};
  return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="flex max-h-[94dvh] max-w-6xl flex-col overflow-hidden p-0"><DialogHeader className="border-b px-6 py-5"><DialogTitle>{draft.token?"Editar borrador":"Nueva orden de compra"}</DialogTitle><DialogDescription>Las cantidades podrán diferir en la recepción; una orden confirmada conserva el plan original.</DialogDescription></DialogHeader><div className="space-y-5 overflow-y-auto p-6"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Proveedor"><PartyRoleSelect role="Supplier" value={draft.supplierId} onChange={value=>patch({supplierId:value,lines:[]})} placeholder="Buscar proveedor"/></Field><Field label="Bodega"><Select value={draft.warehouseId} onValueChange={v=>patch({warehouseId:v})}><SelectTrigger><SelectValue placeholder="Seleccionar"/></SelectTrigger><SelectContent>{(options.data?.warehouses??[]).map(w=><SelectItem key={w.warehouseId} value={w.warehouseId}>{w.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Fecha de orden"><Input type="datetime-local" value={draft.orderedAt} onChange={e=>patch({orderedAt:e.target.value})}/></Field><Field label="Entrega esperada"><Input type="datetime-local" value={draft.expectedAt} onChange={e=>patch({expectedAt:e.target.value})}/></Field></div>
    <div className="rounded-xl border p-4"><SupplierProductPicker ref={productSearchRef} supplierId={draft.supplierId||undefined} includeUnassociated={includeUnassociated} onIncludeUnassociatedChange={setIncludeUnassociated} onSelect={add}/></div>
    <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted/50"><tr><th className="p-3 text-left">Producto</th><th>Cantidad</th><th>Costo</th><th>Descuento</th><th>Total</th><th/></tr></thead><tbody>{draft.lines.map(line=><tr className="border-t" key={line.lineId}><td className="p-3">{line.description}</td><td className="p-2"><Input type="number" min="0.000001" value={line.presentationQuantity}
      ref={element=>{if(element)quantityRefs.current.set(line.productId,element);else quantityRefs.current.delete(line.productId)}}
      onChange={e=>{const presentationQuantity=Number(e.target.value);patch({lines:draft.lines.map(x=>x.lineId===line.lineId?{...x,presentationQuantity,orderedQuantity:presentationQuantity*x.unitsPerPresentation}:x)})}}
      onKeyDown={event=>{if(event.key==="ArrowDown"){event.preventDefault();moveQuantity(line.productId,1)}else if(event.key==="ArrowUp"){event.preventDefault();moveQuantity(line.productId,-1)}else if(event.key==="Enter"){event.preventDefault();productSearchRef.current?.focus();productSearchRef.current?.select()}}}/></td><td className="p-2"><Input type="number" min="0" value={line.unitCost} onChange={e=>patch({lines:draft.lines.map(x=>x.lineId===line.lineId?{...x,unitCost:Number(e.target.value)}:x)})}/></td><td className="p-2"><Input type="number" min="0" value={line.discountAmount} onChange={e=>patch({lines:draft.lines.map(x=>x.lineId===line.lineId?{...x,discountAmount:Number(e.target.value)}:x)})}/></td><td className="p-3 text-right">{formatCurrency((line.orderedQuantity*line.unitCost-line.discountAmount)*(1+line.taxRate/100))}</td><td><Button variant="ghost" onClick={()=>patch({lines:draft.lines.filter(x=>x.lineId!==line.lineId).map((x,i)=>({...x,lineNumber:i+1}))})}>Quitar</Button></td></tr>)}</tbody></table>{!draft.lines.length&&<p className="p-8 text-center text-muted-foreground">Selecciona productos para construir la orden.</p>}</div>
    <div className="grid gap-4 md:grid-cols-[1fr_18rem]"><Textarea value={draft.notes} onChange={e=>patch({notes:e.target.value})} placeholder="Observaciones"/><div className="rounded-xl bg-slate-950 p-5 text-white"><p className="text-sm text-slate-300">Total estimado</p><p className="mt-2 text-2xl font-semibold">{formatCurrency(total)}</p></div></div></div><DialogFooter className="border-t p-4"><Button variant="outline" onClick={onClose}>Cerrar</Button><Button variant="secondary" onClick={()=>void persist()} disabled={save.isPending}>Guardar borrador</Button><Button onClick={()=>void finish()} disabled={confirm.isPending}>Confirmar orden</Button></DialogFooter></DialogContent></Dialog>;
}

function OrderDetail({detail,canClose,onClose,onRefresh}:{detail:PurchaseOrderDetail;canClose:boolean;onClose:()=>void;onRefresh:()=>Promise<void>}){const close=useClosePurchaseOrder();const [reason,setReason]=useState("");const closable=detail.status==="Open"||detail.status==="PartiallyReceived";return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="max-w-6xl"><DialogHeader><DialogTitle>{detail.documentNumber??"Orden de compra"}</DialogTitle><DialogDescription>{detail.supplierName} · {detail.warehouseName} · {labels[detail.status]}</DialogDescription></DialogHeader><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr><th className="text-left">Producto</th><th>Ordenado</th><th>Recibido</th><th>Pendiente</th><th>Rotación 30 d</th><th>Rotación 90 d</th><th>Stock</th><th>En camino</th></tr></thead><tbody>{detail.lines.map(l=><tr className="border-t" key={l.lineId}><td className="py-3">{l.description}<p className="text-xs text-muted-foreground">Actualizada {l.rotationCalculatedAt?formatDateTime(l.rotationCalculatedAt):"sin ventas proyectadas"}</p></td><td className="text-center">{l.orderedQuantity}</td><td className="text-center">{l.receivedQuantity}</td><td className="text-center font-semibold">{l.remainingQuantity}</td><td className="text-center">{l.rotation30Days}</td><td className="text-center">{l.rotation90Days}</td><td className="text-center">{l.currentStock}</td><td className="text-center">{l.incomingQuantity}</td></tr>)}</tbody></table></div>{canClose&&closable&&<div className="space-y-2"><Label>Motivo para cerrar el saldo pendiente</Label><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ej. el proveedor no despachará el faltante"/><Button variant="destructive" disabled={!reason.trim()||close.isPending} onClick={async()=>{try{await close.mutateAsync({id:detail.purchaseOrderId,reason,token:detail.concurrencyToken!});toast.success("Saldo pendiente cerrado");await onRefresh()}catch{toast.error("No se pudo cerrar la orden")}}}>Cerrar saldo pendiente</Button></div>}<DialogFooter><Button variant="outline" onClick={onClose}>Cerrar</Button></DialogFooter></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function empty():Draft{const now=new Date(),expected=new Date();expected.setDate(expected.getDate()+7);const local=(d:Date)=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);return{id:crypto.randomUUID(),warehouseId:"",supplierId:"",orderedAt:local(now),expectedAt:local(expected),notes:"",token:null,lines:[]}}
function fromDetail(v:PurchaseOrderDetail):Draft{return{id:v.purchaseOrderId,warehouseId:v.warehouseId??"",supplierId:v.supplierId??"",orderedAt:v.orderedAt.slice(0,16),expectedAt:v.expectedAt?.slice(0,16)??"",notes:v.notes??"",token:v.concurrencyToken,lines:v.lines.map(l=>({lineId:l.lineId,lineNumber:l.lineNumber,productId:l.productId,description:l.description,orderedQuantity:l.orderedQuantity,unitCost:l.unitCost,discountAmount:l.discountAmount,taxCode:l.taxCode,taxRate:l.taxRate,taxTreatment:l.taxTreatment,presentationName:l.presentationName,presentationQuantity:l.presentationQuantity,unitsPerPresentation:l.unitsPerPresentation}))}}
