"use client";

import { useDeferredValue, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Boxes, ChevronDown, ChevronUp, History, Plus, RefreshCw, Search, SlidersHorizontal } from "lucide-react";
import { toast } from "sonner";
import { InventoryOperationWorkspace } from "@/components/inventory/inventory-operation-workspace";
import { PartyRoleSelect } from "@/components/parties/party-role-select";
import { InventoryPhysicalCountWorkspace, InventoryReconciliationDialog, type PhysicalCountDraftSelection } from "@/components/inventory/inventory-physical-count-workspace";
import { DataTablePagination } from "@/components/tables/data-table-pagination";
import { inventoryApi, type InventoryBalanceItem, type InventoryOperationDetail, type InventoryReconciliationDetail } from "@/services/api/inventory";
import { goodsReceiptsApi } from "@/services/api/goods-receipts";
import { useBusinessContextStore } from "@/stores/business-context-store";
import { useAuthStore } from "@/stores/auth-store";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { DatePicker } from "@/components/ui/date-picker";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { formatCurrency, formatDateTime } from "@/lib/utils";
import { defaultInventoryOperationKind } from "@/lib/inventory-operation-launch";

const fmt=(value:number)=>new Intl.NumberFormat("es-CO",{maximumFractionDigits:6}).format(value);
const documentLabels:Record<string,string>={StockCount:"Conteo físico",InventoryAdjustment:"Movimiento de mercancía",WarehouseTransfer:"Traslado",ProductConversion:"Conversión",Damage:"Avería",SalesInvoice:"Venta",GoodsReceipt:"Recepción"};
const movementLabels:Record<string,string>={GoodsReceipt:"Recepci\u00f3n de mercanc\u00eda",InventoryAdjustment:"Movimiento de mercanc\u00eda",StockCount:"Ajuste por conteo f\u00edsico",StockCountAdjustment:"Ajuste por conteo f\u00edsico",WarehouseTransfer:"Traslado entre bodegas",TransferOut:"Salida por traslado",TransferIn:"Entrada por traslado",ProductConversion:"Conversi\u00f3n de producto",ConversionInput:"Consumo por conversi\u00f3n",ConversionOutput:"Producci\u00f3n por conversi\u00f3n",Damage:"Salida por aver\u00eda",InventoryDamage:"Salida por aver\u00eda",SalesInvoice:"Venta",Sale:"Venta",SalesReturn:"Devoluci\u00f3n de venta"};
const statusLabels:Record<string,string>={Draft:"Borrador",Accepted:"En proceso",Processed:"Procesado",DispatchPending:"Confirmando salida",Dispatched:"Pendiente de entrada",ReceiptPending:"Confirmando entrada",PartiallyReceived:"Entrada parcial",Received:"Recibido",Confirmed:"Confirmado",Failed:"Con error"};
const reasonLabels:Record<string,string>={GOODS_RECEIPT:"Recepción de mercancía",PHYSICAL_COUNT:"Conteo físico",INVENTORY_VERIFICATION:"Verificación de existencias",INITIAL_BALANCE:"Saldo inicial",FOUND_SURPLUS:"Sobrante encontrado",WAREHOUSE_TRANSFER:"Traslado entre bodegas",DAMAGE:"Avería"};
const humanLabel=(value:string|null|undefined,labels:Record<string,string>)=>value ? labels[value]??value.replace(/([a-z])([A-Z])/g,"$1 $2") : "\u2014";
const dayBoundary=(value:string,next=false)=>{if(!value)return undefined;const date=new Date(`${value}T00:00:00`);if(next)date.setDate(date.getDate()+1);return date.toISOString()};
const localDateValue=()=>{const date=new Date();const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,10)};

export default function InventoryPage(){
 const businessId=useBusinessContextStore(s=>s.selectedBusinessId);
 const queryClient=useQueryClient();
 const permissions=new Set(useAuthStore(s=>s.user?.permissions??[]));
 const [search,setSearch]=useState(""); const deferredSearch=useDeferredValue(search.trim());
 const [warehouseId,setWarehouseId]=useState("all"); const [activeTab,setActiveTab]=useState("balances"); const [operationType,setOperationType]=useState("all");
 const [inventoryView,setInventoryView]=useState("documents");
 const [filtersExpanded,setFiltersExpanded]=useState(true); const [fromDate,setFromDate]=useState(localDateValue); const [toDate,setToDate]=useState(localDateValue); const [operationStatus,setOperationStatus]=useState("all");
 const [reasonCode,setReasonCode]=useState("all"); const [destinationWarehouseId,setDestinationWarehouseId]=useState("all"); const [supplierId,setSupplierId]=useState("all"); const [purchaseEvidenceType,setPurchaseEvidenceType]=useState("all");
 const [valuationBasis,setValuationBasis]=useState<"unit"|"average">("average");
 const [creatingOperation,setCreatingOperation]=useState(false);
 const [editingPhysicalCountDraft,setEditingPhysicalCountDraft]=useState<PhysicalCountDraftSelection>();
 const [reconciliationResult,setReconciliationResult]=useState<InventoryReconciliationDetail>();
 const [pageSize,setPageSize]=useState(20);
 const [pages,setPages]=useState({balances:1,movements:1,operations:1,conversions:1}); const [detail,setDetail]=useState<InventoryOperationDetail>(); const [detailLoading,setDetailLoading]=useState(false);
 const resetPages=()=>setPages({balances:1,movements:1,operations:1,conversions:1});
 const warehouseOptions=useQuery({queryKey:["inventory-warehouses",businessId],queryFn:()=>inventoryApi.warehouses(),enabled:!!businessId});
 const goodsReceiptOptions=useQuery({queryKey:["goods-receipt-options",businessId],queryFn:()=>goodsReceiptsApi.options(),enabled:!!businessId&&activeTab==="operations"&&operationType==="GoodsReceipt"});
 const reasonOptions=useQuery({queryKey:["inventory-operation-filter-reasons",businessId,operationType],queryFn:()=>inventoryApi.reasons({operationType}),enabled:!!businessId&&activeTab==="operations"&&!(["all","GoodsReceipt"].includes(operationType))});
 const balances=useQuery({queryKey:["inventory-balances",businessId,warehouseId,deferredSearch,pages.balances,pageSize],queryFn:()=>inventoryApi.balances({warehouseId:warehouseId==="all"?undefined:warehouseId,search:deferredSearch||undefined,page:pages.balances,pageSize}),enabled:!!businessId});
 const movements=useQuery({queryKey:["inventory-movements",businessId,warehouseId,deferredSearch,pages.movements,pageSize],queryFn:()=>inventoryApi.movements({warehouseId:warehouseId==="all"?undefined:warehouseId,search:deferredSearch||undefined,page:pages.movements,pageSize}),enabled:!!businessId});
 const operations=useQuery({queryKey:["inventory-operations",businessId,warehouseId,deferredSearch,operationType,fromDate,toDate,operationStatus,reasonCode,destinationWarehouseId,supplierId,purchaseEvidenceType,pages.operations,pageSize],queryFn:()=>inventoryApi.operations({warehouseId:warehouseId==="all"?undefined:warehouseId,search:deferredSearch||undefined,documentType:operationType==="all"?undefined:operationType,from:dayBoundary(fromDate),to:dayBoundary(toDate||localDateValue(),true),status:operationType!=="all"&&operationStatus!=="all"?operationStatus:undefined,reasonCode:operationType!=="all"&&operationType!=="GoodsReceipt"&&reasonCode!=="all"?reasonCode:undefined,destinationWarehouseId:operationType==="WarehouseTransfer"&&destinationWarehouseId!=="all"?destinationWarehouseId:undefined,supplierId:operationType==="GoodsReceipt"&&supplierId!=="all"?supplierId:undefined,purchaseEvidenceType:operationType==="GoodsReceipt"&&purchaseEvidenceType!=="all"?purchaseEvidenceType:undefined,page:pages.operations,pageSize}),enabled:!!businessId&&activeTab==="operations",refetchInterval:query=>query.state.data?.items.some(item=>["Accepted","DispatchPending","ReceiptPending"].includes(item.status))?2_000:false});
 const warehouses=(warehouseOptions.data??[]).map(x=>({id:x.warehouseId,name:x.name}));
 async function openOperationDetail(item?:{documentId:string}){
  if(!item)return;
  setDetail(undefined);
  setDetailLoading(true);
  try{setDetail(await queryClient.fetchQuery({queryKey:["inventory-operation-detail",businessId,item.documentId],queryFn:()=>inventoryApi.operationDetail(item.documentId),staleTime:60_000}));}
  catch{toast.error("No fue posible consultar el detalle del documento.");}
  finally{setDetailLoading(false)}
 }
 const changeTab=(value:string)=>{
  setActiveTab(value);
  if(value==="balances")void balances.refetch();
  else if(value==="movements")void movements.refetch();
  else if(value==="operations")void Promise.all([operations.refetch(),queryClient.invalidateQueries({queryKey:["inventory-physical-counts"]})]);
 };
 const changeOperationType=(value:string)=>{setOperationType(value);setOperationStatus("all");setReasonCode("all");setDestinationWarehouseId("all");setSupplierId("all");setPurchaseEvidenceType("all");setPages(current=>({...current,operations:1}))};
 const changeOperationFilter=(setter:(value:string)=>void,value:string)=>{setter(value);setPages(current=>({...current,operations:1}))};
 const standardOperationHistory=<><SimpleTable headers={["Fecha","Documento","Tipo","Bodega","Motivo","Estado","Líneas","Valor"]} rows={(operations.data?.items??[]).map(x=>[formatDateTime(x.occurredAt),x.documentNumber??"Borrador",documentLabels[x.documentType]??x.documentType,x.destinationWarehouseName?`${x.warehouseName} → ${x.destinationWarehouseName}`:x.warehouseName,humanLabel(x.reasonCode,reasonLabels),humanLabel(x.status,statusLabels),String(x.lineCount),x.totalValueChange==null?"Restringido":formatCurrency(x.totalValueChange)])} loading={operations.isLoading} onRowClick={index=>void openOperationDetail(operations.data?.items[index])}/><Pager page={pages.operations} pageSize={pageSize} total={operations.data?.totalPages??0} totalItems={operations.data?.totalCount??0} setPage={page=>setPages(current=>({...current,operations:page}))} setPageSize={setPageSize}/></>;
 const operationFilters=<Card><CardContent className="pt-6"><button type="button" className="flex w-full items-center justify-between gap-3 text-left" onClick={()=>setFiltersExpanded(value=>!value)} aria-expanded={filtersExpanded}><span className="flex items-center gap-2 font-medium"><SlidersHorizontal className="h-4 w-4"/>Filtros de {operationType==="all"?"todas las operaciones":documentLabels[operationType]?.toLocaleLowerCase("es-CO")??operationType}</span>{filtersExpanded?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{filtersExpanded&&<div className="mt-4 grid gap-3 border-t pt-4 sm:grid-cols-2 lg:grid-cols-4"><label className="space-y-1.5 text-sm"><span className="text-muted-foreground">Desde</span><DatePicker value={fromDate} max={toDate||localDateValue()} onChange={value=>changeOperationFilter(setFromDate,value)}/></label><label className="space-y-1.5 text-sm"><span className="text-muted-foreground">Hasta</span><DatePicker value={toDate} min={fromDate||undefined} onChange={value=>changeOperationFilter(setToDate,value)}/><span className="block text-xs text-muted-foreground">Si se deja vacío, se consulta hasta hoy.</span></label>{operationType!=="all"&&<FilterSelect label="Estado" value={operationStatus} onChange={value=>changeOperationFilter(setOperationStatus,value)} options={operationType==="WarehouseTransfer"?[["all","Todos los estados"],["DispatchPending","Confirmando salida"],["Dispatched","Pendiente de entrada"],["ReceiptPending","Confirmando entrada"],["PartiallyReceived","Entrada parcial"],["Received","Recibido"]]:[["all","Todos los estados"],["Accepted","En proceso"],["Processed","Procesado"],["Confirmed","Confirmado"],["Failed","Con error"]]}/>} {operationType!=="all"&&operationType!=="GoodsReceipt"&&<FilterSelect label="Motivo" value={reasonCode} onChange={value=>changeOperationFilter(setReasonCode,value)} options={[["all","Todos los motivos"],...(reasonOptions.data??[]).map(item=>[item.code,item.name])]}/>} {operationType==="WarehouseTransfer"&&<FilterSelect label="Bodega destino" value={destinationWarehouseId} onChange={value=>changeOperationFilter(setDestinationWarehouseId,value)} options={[["all","Todas las bodegas destino"],...warehouses.filter(item=>item.id!==warehouseId).map(item=>[item.id,item.name])]}/>} {operationType==="GoodsReceipt"&&<label className="space-y-1.5 text-sm"><span className="text-muted-foreground">Proveedor</span><PartyRoleSelect role="Supplier" value={supplierId} leadingOptions={[{value:"all",label:"Todos los proveedores"}]} placeholder="Buscar proveedor" onChange={value=>changeOperationFilter(setSupplierId,value)}/></label>} {operationType==="GoodsReceipt"&&<FilterSelect label="Tipo de documento" value={purchaseEvidenceType} onChange={value=>changeOperationFilter(setPurchaseEvidenceType,value)} options={[["all","Todos los documentos"],...(goodsReceiptOptions.data?.purchaseEvidenceTypes??[]).map(item=>[item.code,item.label])]}/>}</div>}</CardContent></Card>;
 if(!businessId)return <Empty text="Selecciona una sede para consultar su inventario."/>;
 return <div className="space-y-5 p-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-emerald-600">Operación y trazabilidad</p><h1 className="text-3xl font-bold tracking-tight">Inventario</h1><p className="text-muted-foreground">Existencias, kárdex y operaciones procesadas por el motor ordenado de Auraly.</p></div><div className="flex flex-wrap gap-2"><Button onClick={()=>{setEditingPhysicalCountDraft(undefined);setCreatingOperation(true)}}><Plus className="mr-2 h-4 w-4"/>Nueva operación</Button></div></header>
 <div className="grid gap-3 md:grid-cols-3"><Metric icon={Boxes} label="Productos por bodega" value={String(balances.data?.totalCount??0)}/><Metric icon={History} label="Movimientos filtrados" value={String(movements.data?.totalCount??0)}/><Metric icon={AlertTriangle} label="Operaciones" value={String(operations.data?.totalCount??0)}/></div>
 <Card><CardContent className="flex flex-col gap-3 pt-6 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>{setSearch(e.target.value);resetPages()}} placeholder="Producto, referencia, código, documento o motivo"/></div><Select value={warehouseId} onValueChange={v=>{setWarehouseId(v);resetPages()}}><SelectTrigger className="md:w-72"><SelectValue placeholder="Todas las bodegas"/></SelectTrigger><SelectContent><SelectItem value="all">Todas las bodegas</SelectItem>{warehouses.map(w=><SelectItem key={w.id} value={w.id}>{w.name}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>void Promise.all([balances.refetch(),movements.refetch(),operations.refetch(),queryClient.invalidateQueries({queryKey:["inventory-physical-counts"]})])} disabled={balances.isFetching||movements.isFetching||operations.isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${balances.isFetching||movements.isFetching||operations.isFetching?"animate-spin":""}`}/>Actualizar</Button></CardContent></Card>
 <Tabs value={activeTab} onValueChange={changeTab}><TabsList className="grid h-auto w-full grid-cols-3"><TabsTrigger value="balances">Existencias</TabsTrigger><TabsTrigger value="movements">Kárdex</TabsTrigger><TabsTrigger value="operations">Operaciones</TabsTrigger></TabsList>
 <TabsContent value="balances" className="space-y-4"><Card><CardContent className="flex flex-wrap items-center justify-between gap-3 pt-6"><div><p className="font-medium">Valorización de existencias</p><p className="text-sm text-muted-foreground">Incluye productos sin saldo y señala cuáles no manejan inventario.</p></div><Select value={valuationBasis} onValueChange={value=>setValuationBasis(value as "unit"|"average")}><SelectTrigger className="w-56"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unit">Precio costo</SelectItem><SelectItem value="average">Costo promedio</SelectItem></SelectContent></Select></CardContent></Card><BalanceTable items={balances.data?.items??[]} loading={balances.isLoading} valuationBasis={valuationBasis}/><Pager page={pages.balances} pageSize={pageSize} total={balances.data?.totalPages??0} totalItems={balances.data?.totalCount??0} setPage={page=>setPages(current=>({...current,balances:page}))} setPageSize={setPageSize}/></TabsContent>
 <TabsContent value="movements" className="space-y-4"><SimpleTable headers={["Fecha","Producto","Bodega","Movimiento","Cantidad","Saldo","Documento"]} rows={(movements.data?.items??[]).map(x=>[formatDateTime(x.occurredAt),`${x.productCode} · ${x.productName}`,x.warehouseName,humanLabel(x.movementType,movementLabels),<Signed key={x.inventoryMovementId} value={x.quantityChange}/>,fmt(x.quantityAfter),x.documentNumber??humanLabel(x.documentType,documentLabels)])} loading={movements.isLoading}/><Pager page={pages.movements} pageSize={pageSize} total={movements.data?.totalPages??0} totalItems={movements.data?.totalCount??0} setPage={page=>setPages(current=>({...current,movements:page}))} setPageSize={setPageSize}/></TabsContent>
 <TabsContent value="operations" className="space-y-4">
  <div className="flex flex-wrap gap-2">{[["all","Todas"],["StockCount","Inventarios"],["InventoryAdjustment","Movimientos de mercancía"],["GoodsReceipt","Recepciones"],["WarehouseTransfer","Traslados"],["ProductConversion","Conversiones"],["Damage","Averías"]].map(([value,label])=><Button key={value} size="sm" variant={operationType===value?"default":"outline"} onClick={()=>changeOperationType(value)}>{label}</Button>)}</div>
  {operationType!=="StockCount"&&operationFilters}
  {operationType==="StockCount"?<div className="space-y-4"><Tabs value={inventoryView} onValueChange={setInventoryView} className="space-y-4"><TabsList className="grid h-auto w-full grid-cols-2 rounded-2xl p-1"><TabsTrigger value="documents" className="rounded-xl py-2.5">Documentos de inventario</TabsTrigger><TabsTrigger value="drafts" className="rounded-xl py-2.5">Borradores</TabsTrigger></TabsList><TabsContent value="documents" className="space-y-4">{operationFilters}{standardOperationHistory}</TabsContent><TabsContent value="drafts" className="space-y-4"><InventoryPhysicalCountWorkspace businessId={businessId} warehouses={warehouses} permissions={permissions} onReconciled={setReconciliationResult} onEditDraft={value=>{setEditingPhysicalCountDraft(value);setCreatingOperation(true)}}/></TabsContent></Tabs></div>:operationType==="ProductConversion"?<><SimpleTable headers={["Fecha","Documento","Bodega","Entrada equivalente","Salida equivalente","Merma","Tolerancia","Estado"]} rows={(operations.data?.items??[]).map(x=>[formatDateTime(x.occurredAt),x.documentNumber??"Borrador",x.warehouseName,x.conversionInputEquivalent==null?"—":fmt(x.conversionInputEquivalent),x.conversionOutputEquivalent==null?"—":fmt(x.conversionOutputEquivalent),x.conversionLossPercent==null?"—":`${fmt(x.conversionLossQuantity??0)} · ${fmt(x.conversionLossPercent)} %`,x.conversionMaximumLossPercent==null?"—":`${fmt(x.conversionMaximumLossPercent)} %`,humanLabel(x.status,statusLabels)])} loading={operations.isLoading} onRowClick={index=>void openOperationDetail(operations.data?.items[index])}/><Pager page={pages.operations} pageSize={pageSize} total={operations.data?.totalPages??0} totalItems={operations.data?.totalCount??0} setPage={page=>setPages(current=>({...current,operations:page}))} setPageSize={setPageSize}/></>:standardOperationHistory}
 </TabsContent></Tabs>
 {creatingOperation&&<Dialog open onOpenChange={v=>{if(!v){setCreatingOperation(false);setEditingPhysicalCountDraft(undefined)}}}><DialogContent className="flex max-h-[94dvh] max-w-6xl flex-col overflow-y-auto"><DialogHeader><DialogTitle>{editingPhysicalCountDraft?"Editar borrador":"Nueva operación"}</DialogTitle><DialogDescription>{editingPhysicalCountDraft?"Continúa el conteo o reconteo exactamente donde quedó guardado.":"Comienza con un conteo físico o cambia de operación sin cerrar esta ventana."}</DialogDescription></DialogHeader><InventoryOperationWorkspace businessId={businessId} warehouses={warehouses} permissions={permissions} initialKind={editingPhysicalCountDraft?"count":defaultInventoryOperationKind} physicalCountDraft={editingPhysicalCountDraft} onCancel={()=>{setCreatingOperation(false);setEditingPhysicalCountDraft(undefined)}} onCompleted={destination=>{setCreatingOperation(false);setEditingPhysicalCountDraft(undefined);setActiveTab("operations");setOperationType("StockCount");setInventoryView(destination??"documents");void Promise.all([queryClient.invalidateQueries({queryKey:["inventory-physical-counts"]}),queryClient.invalidateQueries({queryKey:["inventory-physical-count-drafts"]}),queryClient.invalidateQueries({queryKey:["inventory-operations"]})])}}/></DialogContent></Dialog>}
 <InventoryReconciliationDialog open={Boolean(reconciliationResult)} businessId={businessId} value={reconciliationResult} onClose={()=>setReconciliationResult(undefined)}/>
 {detailLoading&&<Dialog open onOpenChange={()=>setDetailLoading(false)}><DialogContent><div className="flex items-center justify-center gap-2 p-10 text-muted-foreground"><RefreshCw className="h-5 w-5 animate-spin"/>Cargando detalle…</div></DialogContent></Dialog>}<InventoryDetailDialog detail={detail} onClose={()=>setDetail(undefined)}/></div>
}
function FilterSelect({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <label className="space-y-1.5 text-sm"><span className="text-muted-foreground">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(([optionValue,optionLabel])=><SelectItem key={optionValue} value={optionValue}>{optionLabel}</SelectItem>)}</SelectContent></Select></label>}
function BalanceTable({items,loading,valuationBasis}:{items:InventoryBalanceItem[];loading:boolean;valuationBasis:"unit"|"average"}){return <SimpleTable headers={["Producto","Manejo","Bodega","Cantidad",valuationBasis==="unit"?"Precio costo":"Costo promedio","Valorización","Actualizado"]} rows={items.map(x=>{const cost=valuationBasis==="unit"?x.unitCost:x.averageUnitCost;return [`${x.productCode} · ${x.productName}`,x.managesInventory?"Maneja inventario":"No maneja",x.warehouseName,fmt(x.quantityOnHand),cost==null?"Restringido":formatCurrency(cost),cost==null?"Restringido":formatCurrency(x.quantityOnHand*cost),x.updatedAt?formatDateTime(x.updatedAt):"Sin movimientos"]})} loading={loading}/>}
function SimpleTable({headers,rows,loading,onRowClick}:{headers:string[];rows:React.ReactNode[][];loading:boolean;onRowClick?:(index:number)=>void}){return <Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-sm"><thead className="border-b bg-muted/50"><tr>{headers.map(h=><th key={h} className="px-4 py-3 text-left text-xs font-medium uppercase tracking-wide text-muted-foreground">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={headers.length} className="p-10 text-center">Cargando…</td></tr>:rows.length===0?<tr><td colSpan={headers.length} className="p-10 text-center text-muted-foreground">No hay información para los filtros seleccionados.</td></tr>:rows.map((row,i)=><tr key={i} onClick={()=>onRowClick?.(i)} className={`border-b last:border-0 ${onRowClick?"cursor-pointer transition-colors hover:bg-muted/40":""}`}>{row.map((cell,j)=><td key={j} className="px-4 py-3 align-middle">{cell}</td>)}</tr>)}</tbody></table></CardContent></Card>}
function Signed({value}:{value:number}){return <span className={value<0?"font-semibold text-red-600":"font-semibold text-emerald-600"}>{value>0?"+":""}{fmt(value)}</span>}
function InventoryDetailDialog({detail,onClose}:{detail?:InventoryOperationDetail;onClose:()=>void}){
 if(!detail)return null;
 const isCount=detail.documentType==="StockCount";
 const isConversion=detail.documentType==="ProductConversion";
 const isTransfer=detail.documentType==="WarehouseTransfer";
 const countValue=isCount?detail.lines.reduce((total,line)=>total+(line.processedUnitCost??0)*Math.abs(line.quantity??0),0):null;
 return <Dialog open onOpenChange={value=>!value&&onClose()}><DialogContent className="flex max-h-[92dvh] max-w-5xl flex-col overflow-hidden p-0">
  <DialogHeader className="border-b px-6 py-5"><DialogTitle>{detail.documentNumber??"Documento en preparación"}</DialogTitle><DialogDescription>{documentLabels[detail.documentType]??detail.documentType} · documento inmutable y trazable</DialogDescription></DialogHeader>
  <div className="space-y-5 overflow-y-auto px-6 py-5">
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
    <DetailCard label="Tipo" value={documentLabels[detail.documentType]??detail.documentType}/>
    <DetailCard label="Estado" value={humanLabel(detail.status,statusLabels)}/>
    <DetailCard label="Bodega" value={detail.destinationWarehouseName?`${detail.warehouseName} → ${detail.destinationWarehouseName}`:detail.warehouseName}/>
    <DetailCard label="Fecha" value={formatDateTime(detail.occurredAt)}/>
    <DetailCard label="Motivo" value={detail.reasonDescription||humanLabel(detail.reasonCode,reasonLabels)}/>
    <DetailCard label="Líneas" value={String(detail.lines.length)}/>
    <DetailCard label={isCount?"Valor del conteo":"Valor"} value={isCount?formatCurrency(countValue??0):detail.totalValueChange==null?"Restringido":formatCurrency(detail.totalValueChange)}/>
    <DetailCard label="Procesado" value={detail.processedAt?formatDateTime(detail.processedAt):"Pendiente"}/>
   </div>
   {isConversion&&<div className="grid gap-3 rounded-2xl border border-emerald-200 bg-emerald-50/50 p-4 sm:grid-cols-5">
    <DetailCard label="Entrada equivalente" value={detail.conversionInputEquivalent==null?"—":fmt(detail.conversionInputEquivalent)}/>
    <DetailCard label="Salida equivalente" value={detail.conversionOutputEquivalent==null?"—":fmt(detail.conversionOutputEquivalent)}/>
    <DetailCard label="Merma" value={detail.conversionLossQuantity==null?"—":fmt(detail.conversionLossQuantity)}/>
    <DetailCard label="Merma %" value={detail.conversionLossPercent==null?"—":`${fmt(detail.conversionLossPercent)} %`}/>
    <DetailCard label="Máximo" value={detail.conversionMaximumLossPercent==null?"—":`${fmt(detail.conversionMaximumLossPercent)} %`}/>
   </div>}
   <div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[850px] text-sm">
    <thead className="bg-muted/60 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3 text-left">Producto</th><th className="px-4 py-3 text-left">Movimiento</th>{isCount&&<th className="px-4 py-3 text-right">Existencia sistema</th>}<th className="px-4 py-3 text-right">{isCount?"Preconteo":"Saldo base"}</th><th className="px-4 py-3 text-right">{isCount?"Cantidad contada":"Cantidad"}</th>{isTransfer&&<><th className="px-4 py-3 text-right">Salió</th><th className="px-4 py-3 text-right">Entró</th></>}{isCount&&<th className="px-4 py-3 text-right">Diferencia</th>}<th className="px-4 py-3 text-right">Valor unitario</th><th className="px-4 py-3 text-right">Valor total</th></tr></thead>
    <tbody className="divide-y">{detail.lines.map(line=><tr key={line.lineNumber}>
     <td className="px-4 py-3"><p>{line.productName}</p><p className="text-xs text-muted-foreground">{line.productCode} · Línea {line.lineNumber}{isConversion&&line.conversionFactor!=null?` · factor ${fmt(line.conversionFactor)} · equivalente ${fmt(line.conversionEquivalentQuantity??0)}`:""}</p></td>
     <td className="px-4 py-3">{directionLabel(line.direction)}</td>
     {isCount&&<td className="px-4 py-3 text-right tabular-nums">{line.systemQuantityAtBase==null?"—":fmt(line.systemQuantityAtBase)}</td>}
     <td className="px-4 py-3 text-right tabular-nums">{isCount?(line.preCountQuantity==null?"—":fmt(line.preCountQuantity)):(line.systemQuantityAtBase==null?"—":fmt(line.systemQuantityAtBase))}</td>
     <td className="px-4 py-3 text-right tabular-nums">{line.quantity==null?"—":fmt(line.quantity)}</td>
     {isTransfer&&<><td className="px-4 py-3 text-right tabular-nums">{fmt(line.dispatchedQuantity??0)}</td><td className="px-4 py-3 text-right tabular-nums">{fmt(line.receivedQuantity??0)}</td></>}
     {isCount&&<td className={`px-4 py-3 text-right font-semibold tabular-nums ${countDifference(line)>0?"text-emerald-700":countDifference(line)<0?"text-red-700":"text-muted-foreground"}`}>{countDifference(line)>0?"+":""}{fmt(countDifference(line))}</td>}
     <td className="px-4 py-3 text-right tabular-nums">{line.processedUnitCost==null?"Restringido":formatCurrency(line.processedUnitCost)}</td>
     <td className="px-4 py-3 text-right font-medium tabular-nums">{(isCount?line.processedUnitCost:line.processedValue)==null?"Restringido":formatCurrency(isCount?Math.abs(line.quantity??0)*(line.processedUnitCost??0):line.processedValue??0)}</td>
    </tr>)}</tbody>
   </table></div>
   {detail.notes&&<div className="rounded-2xl border bg-muted/30 p-4"><p className="text-xs font-medium uppercase text-muted-foreground">Observaciones</p><p className="mt-1">{detail.notes}</p></div>}
  </div>
  <DialogFooter className="border-t px-6 py-4"><Button onClick={onClose}>Cerrar</Button></DialogFooter>
 </DialogContent></Dialog>;
}
function DetailCard({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-muted/20 p-4"><p className="text-xs font-medium uppercase text-muted-foreground">{label}</p><p className="mt-1 text-sm">{value}</p></div>}
function countDifference(line:InventoryOperationDetail["lines"][number]){return (line.quantity??0)-(line.preCountQuantity??0);}
function directionLabel(value:string){return ({COUNT:"Conteo",ADJUSTMENT:"Ajuste",TRANSFER:"Traslado",INPUT:"Consumo",OUTPUT:"Producción",DAMAGE:"Avería",RECEIPT:"Recepción de mercancía"} as Record<string,string>)[value]??value;}

function Metric({icon:Icon,label,value}:{icon:typeof Boxes;label:string;value:string}){return <Card><CardContent className="flex items-center gap-3 pt-6"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-700"><Icon className="h-5 w-5"/></div><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p></div></CardContent></Card>}
function Pager({page,pageSize,total,totalItems,setPage,setPageSize}:{page:number;pageSize:number;total:number;totalItems:number;setPage:(n:number)=>void;setPageSize:(n:number)=>void}){return <DataTablePagination pageIndex={Math.max(0,page-1)} pageSize={pageSize} pageCount={total} totalItems={totalItems} onPageChange={index=>setPage(index+1)} onPageSizeChange={size=>{setPageSize(size);setPage(1)}}/>}
function Empty({text}:{text:string}){return <div className="p-10 text-center text-muted-foreground">{text}</div>}
