"use client";

import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {PackageCheck,Target,TrendingUp,UsersRound} from "lucide-react";
import {salesReportingApi} from "@/services/api/sales-reporting";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {DatePicker} from "@/components/ui/date-picker";
import {PageError} from "@/components/ui/page-error";
import {PageLoading} from "@/components/ui/page-loading";

const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const number=new Intl.NumberFormat("es-CO",{maximumFractionDigits:1});
const iso=(date:Date)=>date.toISOString().slice(0,10);
const today=new Date();

function useRange(){const [from,setFrom]=useState(iso(new Date(today.getFullYear(),today.getMonth(),1)));const [to,setTo]=useState(iso(today));return {from,to,setFrom,setTo};}
function Header({eyebrow,title,description,from,to,setFrom,setTo,updated}:{eyebrow:string;title:string;description:string;from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void;updated:string|null}){
  return <><header className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-teal-950 to-cyan-700 p-7 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">{eyebrow}</p><h1 className="mt-2 text-3xl font-black tracking-tight">{title}</h1><p className="mt-2 max-w-3xl text-sm text-cyan-50/80">{description}</p><p className="mt-5 text-xs text-cyan-100/70">Proyección: {updated?new Date(updated).toLocaleString("es-CO"):"sin datos procesados"}</p></header><Card className="rounded-3xl"><CardContent className="grid gap-4 p-4 sm:grid-cols-2"><label className="space-y-1 text-sm font-medium">Desde<DatePicker value={from} onChange={setFrom}/></label><label className="space-y-1 text-sm font-medium">Hasta<DatePicker value={to} onChange={setTo}/></label></CardContent></Card></>;
}
function Stat({label,value,detail,icon:Icon}:{label:string;value:string;detail:string;icon:typeof Target}){return <Card className="rounded-2xl border-0 bg-slate-950 text-white shadow-lg"><CardContent className="p-5"><div className="flex items-center justify-between text-cyan-200"><span className="text-xs font-bold uppercase tracking-wider">{label}</span><Icon className="h-5 w-5"/></div><strong className="mt-4 block text-3xl">{value}</strong><small className="mt-1 block text-slate-300">{detail}</small></CardContent></Card>}
function Bar({value,tone="bg-teal-500"}:{value:number;tone?:string}){return <div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${tone}`} style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div>}

export function SupplierImpactReport(){const range=useRange();const query=useQuery({queryKey:["supplier-impact",range.from,range.to],queryFn:()=>salesReportingApi.supplierImpact(range.from,range.to)});if(query.isLoading)return <PageLoading/>;if(query.isError)return <PageError onRetry={()=>void query.refetch()}/>;const d=query.data!;return <div className="space-y-6"><Header eyebrow="Sell-in × sell-out" title="Impacto de proveedores" description="Relaciona compras netas con venta, utilidad y clientes impactados por los productos de cada proveedor. Un proveedor autenticado recibe exclusivamente su propia fila y sus productos." {...range} updated={d.projectedThrough}/><div className="grid gap-3 md:grid-cols-4"><Stat label="Compras netas" value={money.format(d.netPurchases)} detail="recepciones menos devoluciones" icon={PackageCheck}/><Stat label="Venta neta" value={money.format(d.netSales)} detail="sell-out atribuido" icon={TrendingUp}/><Stat label="Clientes impactados" value={d.impactedCustomers.toLocaleString("es-CO")} detail={`de ${d.coveredCustomers} clientes cubiertos`} icon={UsersRound}/><Stat label="Rotación comercial" value={d.netPurchases===0?"—":`${number.format(d.netSales*100/d.netPurchases)}%`} detail="venta neta / compra neta" icon={Target}/></div><Card className="rounded-3xl"><CardHeader><CardTitle>Portafolio por proveedor</CardTitle><CardDescription>Compara el período actual contra el rango inmediatamente anterior de igual duración.</CardDescription></CardHeader><CardContent className="space-y-3">{d.suppliers.map(row=><div className="grid gap-4 rounded-2xl border p-4 lg:grid-cols-[1.4fr_repeat(5,1fr)] lg:items-center" key={row.supplierId}><div><strong>{row.supplierName}</strong><p className="text-xs text-muted-foreground">{row.impactedCustomers} clientes impactados · {number.format(row.penetrationPercent)}% penetración</p><Bar value={row.penetrationPercent} tone="bg-cyan-500"/></div><Datum label="Venta neta" value={money.format(row.netSales)}/><Datum label="Compra neta" value={money.format(row.netPurchases)}/><Datum label="Utilidad" value={money.format(row.grossProfit)}/><Datum label="Crec. venta" value={growth(row.salesGrowthPercent)}/><Datum label="Crec. compra" value={growth(row.purchaseGrowthPercent)}/></div>)}{!d.suppliers.length&&<Empty text="No hay compras o ventas atribuidas a proveedores en este período."/>}</CardContent></Card></div>}
function Datum({label,value}:{label:string;value:string}){return <div><small className="text-muted-foreground">{label}</small><strong className="block">{value}</strong></div>}
function growth(value:number|null){return value===null?"Sin base":`${value>=0?"+":""}${number.format(value)}%`}
function Empty({text}:{text:string}){return <p className="p-10 text-center text-sm text-muted-foreground">{text}</p>}
