// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MimosBabySpa.Infrastructure.Data;

#nullable disable

namespace MimosBabySpa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260125165320_AddMimosEntityExtractionConfig")]
    partial class AddMimosEntityExtractionConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Business", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BusinessId");

                    b.HasIndex("TenantId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessConfiguration", b =>
                {
                    b.Property<Guid>("BusinessConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("BusinessConfigurationId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "Key")
                        .IsUnique();

                    b.ToTable("BusinessConfigurations");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessResource", b =>
                {
                    b.Property<Guid>("BusinessResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BusinessResourceId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "ResourceName")
                        .IsUnique();

                    b.ToTable("BusinessResources");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessWhatsAppNumber", b =>
                {
                    b.Property<Guid>("BusinessWhatsAppNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WhatsAppAccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WhatsAppPhoneNumberId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BusinessWhatsAppNumberId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("WhatsAppPhoneNumberId")
                        .IsUnique();

                    b.ToTable("BusinessWhatsAppNumbers");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BabyAge")
                        .HasColumnType("int");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastIntent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RecommendedPlan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConversationId");

                    b.HasIndex("State");

                    b.HasIndex("BusinessId", "UserNumber");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ConversationContext", b =>
                {
                    b.Property<Guid>("ConversationContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ConversationContextId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ConversationId", "Field");

                    b.ToTable("ConversationContexts");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ConversationSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AppliedTactic")
                        .HasColumnType("int");

                    b.Property<bool>("AvailabilityConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClosingAttempts")
                        .HasColumnType("int");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConversationSummary")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentGoalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrentIntent")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("DesiredDate")
                        .HasColumnType("date");

                    b.Property<string>("DesiredService")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly?>("DesiredTime")
                        .HasColumnType("time");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastBotResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastClosingAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastIntent")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastInteractionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUserMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ObjectionsHandledJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ObjectionsRaisedJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int?>("PreviousStage")
                        .HasColumnType("int");

                    b.Property<int>("StageAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("StageEnteredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("BusinessId", "CustomerPhoneNumber", "IsActive");

                    b.ToTable("ConversationSessions");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ConversationStateEntity", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ConversationId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.ToTable("ConversationStates");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.CustomerProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("AverageDecisionTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("AveragePurchaseValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ChurnRisk")
                        .HasColumnType("float");

                    b.Property<string>("CommonObjections")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("ConversationsBeforeFirstPurchase")
                        .HasColumnType("int");

                    b.Property<double>("ConversionProbability")
                        .HasColumnType("float");

                    b.Property<string>("CustomAttributes")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FirstContactAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastContactAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPurchaseAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastSuccessfulStage")
                        .HasColumnType("int");

                    b.Property<decimal?>("LifetimeValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreferredDays")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreferredPaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredServices")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<TimeSpan?>("PreferredTimeOfDay")
                        .HasColumnType("time");

                    b.Property<string>("RecommendedPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Segment")
                        .HasColumnType("int");

                    b.Property<string>("ServiceInterestScore")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("SuccessfulResponses")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("TotalConversations")
                        .HasColumnType("int");

                    b.Property<int>("TotalPurchases")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProfileId");

                    b.HasIndex("Segment");

                    b.HasIndex("BusinessId", "PhoneNumber")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "Name");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.EmployeeService", b =>
                {
                    b.Property<Guid>("EmployeeServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeServiceId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("EmployeeId", "ServiceId")
                        .IsUnique();

                    b.ToTable("EmployeeServices");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LeadId");

                    b.HasIndex("BusinessId", "UserNumber");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CalendarEventId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReservationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("BusinessId", "ReservationDateTime");

                    b.HasIndex("EmployeeId", "ReservationDateTime");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ReservationMetadata", b =>
                {
                    b.Property<Guid>("ReservationMetadataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ReservationMetadataId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("ReservationId", "Field");

                    b.ToTable("ReservationMetadata");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.SalesInteraction", b =>
                {
                    b.Property<Guid>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BotResponse")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DetectedIntent")
                        .HasColumnType("int");

                    b.Property<DateTime>("InteractionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ObjectionDetected")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int?>("TacticApplied")
                        .HasColumnType("int");

                    b.Property<int>("Tone")
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("InteractionId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SessionId");

                    b.HasIndex("BusinessId", "Stage", "InteractionAt");

                    b.ToTable("SalesInteractions");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ServiceId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "ServiceName")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ServiceCoexistenceRule", b =>
                {
                    b.Property<Guid>("ServiceCoexistenceRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanCoexist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId2")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceCoexistenceRuleId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ServiceId1");

                    b.HasIndex("ServiceId2");

                    b.HasIndex("BusinessId", "ServiceId1", "ServiceId2")
                        .IsUnique();

                    b.ToTable("ServiceCoexistenceRules");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ServiceResourceUsage", b =>
                {
                    b.Property<Guid>("ServiceResourceUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceResourceUsageId");

                    b.HasIndex("BusinessResourceId");

                    b.HasIndex("ServiceId", "BusinessResourceId")
                        .IsUnique();

                    b.ToTable("ServiceResourceUsages");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.SystemConfiguration", b =>
                {
                    b.Property<int>("SystemConfigurationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("SystemConfigurationId");

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Business", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Businesses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessConfiguration", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("Configurations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessResource", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessWhatsAppNumber", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("WhatsAppNumbers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("Conversations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ConversationContext", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Contexts")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ConversationStateEntity", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Conversation", "Conversation")
                        .WithOne()
                        .HasForeignKey("MimosBabySpa.Domain.Entities.ConversationStateEntity", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Employee", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.EmployeeService", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeServices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Lead", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("Leads")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Message", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("Reservations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MimosBabySpa.Domain.Entities.Employee", "Employee")
                        .WithMany("Reservations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Conversation");

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ReservationMetadata", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Service", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ServiceCoexistenceRule", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Service", "Service1")
                        .WithMany("CoexistenceRulesAsService1")
                        .HasForeignKey("ServiceId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Service", "Service2")
                        .WithMany("CoexistenceRulesAsService2")
                        .HasForeignKey("ServiceId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Service1");

                    b.Navigation("Service2");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ServiceResourceUsage", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.BusinessResource", "BusinessResource")
                        .WithMany()
                        .HasForeignKey("BusinessResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Service", "Service")
                        .WithMany("ResourceUsages")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessResource");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Business", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("Conversations");

                    b.Navigation("Leads");

                    b.Navigation("Reservations");

                    b.Navigation("WhatsAppNumbers");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeServices");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Service", b =>
                {
                    b.Navigation("CoexistenceRulesAsService1");

                    b.Navigation("CoexistenceRulesAsService2");

                    b.Navigation("ResourceUsages");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Businesses");
                });
#pragma warning restore 612, 618
        }
    }
}
