// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MimosBabySpa.Infrastructure.Data;

#nullable disable

namespace MimosBabySpa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260123173321_RemoveServiceNameFromReservation")]
    partial class RemoveServiceNameFromReservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Business", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BusinessId");

                    b.HasIndex("TenantId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessConfiguration", b =>
                {
                    b.Property<Guid>("BusinessConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("BusinessConfigurationId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "Key")
                        .IsUnique();

                    b.ToTable("BusinessConfigurations");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessResource", b =>
                {
                    b.Property<Guid>("BusinessResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BusinessResourceId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "ResourceName")
                        .IsUnique();

                    b.ToTable("BusinessResources");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessWhatsAppNumber", b =>
                {
                    b.Property<Guid>("BusinessWhatsAppNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WhatsAppAccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WhatsAppPhoneNumberId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BusinessWhatsAppNumberId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("WhatsAppPhoneNumberId")
                        .IsUnique();

                    b.ToTable("BusinessWhatsAppNumbers");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BabyAge")
                        .HasColumnType("int");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastIntent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RecommendedPlan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConversationId");

                    b.HasIndex("State");

                    b.HasIndex("BusinessId", "UserNumber");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ConversationContext", b =>
                {
                    b.Property<Guid>("ConversationContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ConversationContextId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ConversationId", "Field");

                    b.ToTable("ConversationContexts");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LeadId");

                    b.HasIndex("BusinessId", "UserNumber");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CalendarEventId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReservationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("ServiceId");

                    b.HasIndex("BusinessId", "ReservationDateTime");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ServiceId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "ServiceName")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ServiceCoexistenceRule", b =>
                {
                    b.Property<Guid>("ServiceCoexistenceRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanCoexist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId2")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceCoexistenceRuleId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ServiceId1");

                    b.HasIndex("ServiceId2");

                    b.HasIndex("BusinessId", "ServiceId1", "ServiceId2")
                        .IsUnique();

                    b.ToTable("ServiceCoexistenceRules");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ServiceResourceUsage", b =>
                {
                    b.Property<Guid>("ServiceResourceUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceResourceUsageId");

                    b.HasIndex("BusinessResourceId");

                    b.HasIndex("ServiceId", "BusinessResourceId")
                        .IsUnique();

                    b.ToTable("ServiceResourceUsages");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.SystemConfiguration", b =>
                {
                    b.Property<int>("SystemConfigurationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("SystemConfigurationId");

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Business", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Businesses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessConfiguration", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("Configurations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessResource", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.BusinessWhatsAppNumber", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("WhatsAppNumbers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("Conversations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ConversationContext", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Contexts")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Lead", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("Leads")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Message", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany("Reservations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Service", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ServiceCoexistenceRule", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Service", "Service1")
                        .WithMany("CoexistenceRulesAsService1")
                        .HasForeignKey("ServiceId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Service", "Service2")
                        .WithMany("CoexistenceRulesAsService2")
                        .HasForeignKey("ServiceId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Service1");

                    b.Navigation("Service2");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.ServiceResourceUsage", b =>
                {
                    b.HasOne("MimosBabySpa.Domain.Entities.BusinessResource", "BusinessResource")
                        .WithMany()
                        .HasForeignKey("BusinessResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MimosBabySpa.Domain.Entities.Service", "Service")
                        .WithMany("ResourceUsages")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessResource");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Business", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("Conversations");

                    b.Navigation("Leads");

                    b.Navigation("Reservations");

                    b.Navigation("WhatsAppNumbers");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Service", b =>
                {
                    b.Navigation("CoexistenceRulesAsService1");

                    b.Navigation("CoexistenceRulesAsService2");

                    b.Navigation("ResourceUsages");
                });

            modelBuilder.Entity("MimosBabySpa.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Businesses");
                });
#pragma warning restore 612, 618
        }
    }
}
