"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, ClipboardList, Plus, RefreshCw, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ProductPicker } from "@/components/products/product-picker";
import { inventoryApi, type InventoryPhysicalCountDetail, type InventoryPhysicalCountList, type InventoryProductItem } from "@/services/api/inventory";
import { productsApi } from "@/services/api/products";
import { formatDateTime } from "@/lib/utils";

type Warehouse = { id:string;name:string };
type DraftList = { id:string;name:string;products:InventoryProductItem[] };
const statusLabels:Record<string,string>={Draft:"Borrador",PreCounting:"Preconteo",Counting:"Conteo",Review:"Revisión",Closing:"Procesando",Closed:"Cerrado",Cancelled:"Cancelado"};
const fmt=(value:number)=>new Intl.NumberFormat("es-CO",{maximumFractionDigits:6}).format(value);

export function InventoryPhysicalCountWorkspace({businessId,warehouses,warehouseId,search,permissions}:{businessId:string;warehouses:Warehouse[];warehouseId?:string;search?:string;permissions:Set<string>}){
 const client=useQueryClient();
 const [page,setPage]=useState(1);const [detail,setDetail]=useState<InventoryPhysicalCountDetail>();
 const query=useQuery({queryKey:["inventory-physical-counts",businessId,warehouseId,search,page],queryFn:()=>inventoryApi.physicalCounts({warehouseId,search,page,pageSize:50}),refetchInterval:q=>q.state.data?.items.some(x=>x.status==="Closing")?2000:false});
 const canManage=permissions.has("inventory.physical-counts.manage");
 async function open(id:string){try{setDetail(await client.fetchQuery({queryKey:["inventory-physical-count",businessId,id],queryFn:()=>inventoryApi.physicalCount(id)}))}catch{toast.error("No fue posible abrir el inventario físico.")}}
 async function changed(value:InventoryPhysicalCountDetail){setDetail(value);await Promise.all([query.refetch(),client.invalidateQueries({queryKey:["inventory-operations"]})])}
 return <div className="space-y-4">
  <div><h2 className="text-xl font-semibold">Inventarios físicos</h2><p className="text-sm text-muted-foreground">Preconteos y conteos coordinados por listas de productos. Para crear uno usa <strong>Nueva operación</strong>.</p></div>
  <Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-sm"><thead className="border-b bg-muted/50 text-xs uppercase text-muted-foreground"><tr>{["Apertura","Bodega","Alcance","Equipos/listas","Progreso","Diferencias","Estado","Documento"].map(x=><th key={x} className="px-4 py-3 text-left">{x}</th>)}</tr></thead><tbody>{query.isLoading?<tr><td colSpan={8} className="p-10 text-center">Cargando…</td></tr>:(query.data?.items.length??0)===0?<tr><td colSpan={8} className="p-10 text-center text-muted-foreground">No hay inventarios físicos para los filtros seleccionados.</td></tr>:query.data?.items.map(item=><tr key={item.inventoryPhysicalCountId} className="cursor-pointer border-b hover:bg-muted/40" onClick={()=>void open(item.inventoryPhysicalCountId)}><td className="px-4 py-3">{formatDateTime(item.createdAt)}</td><td className="px-4 py-3">{item.warehouseName}</td><td className="px-4 py-3">{item.scopeType==="General"?"General":"Parcial"}</td><td className="px-4 py-3">{item.listCount}</td><td className="px-4 py-3"><strong>{item.countedCount}/{item.productCount}</strong><span className="block text-xs text-muted-foreground">{item.preCountedCount} precontados</span></td><td className="px-4 py-3">{item.differenceCount}</td><td className="px-4 py-3">{statusLabels[item.status]??item.status}</td><td className="px-4 py-3">{item.finalDocumentNumber??"—"}</td></tr>)}</tbody></table></CardContent></Card>
  {(query.data?.totalPages??0)>1&&<div className="flex justify-end gap-2"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Anterior</Button><Button variant="outline" disabled={page>=(query.data?.totalPages??0)} onClick={()=>setPage(x=>x+1)}>Siguiente</Button></div>}
  <PhysicalCountDetailDialog detail={detail} businessId={businessId} canManage={canManage} canCapture={permissions.has("inventory.physical-counts.capture")} onClose={()=>setDetail(undefined)} onChanged={value=>void changed(value)}/>
 </div>
}

export function PhysicalCountCreationForm({businessId,warehouses,onCancel,onCreated}:{businessId:string;warehouses:Warehouse[];onCancel:()=>void;onCreated:(value:InventoryPhysicalCountDetail)=>void}){
 const [warehouse,setWarehouse]=useState(warehouses.length===1?warehouses[0].id:"");const [scope,setScope]=useState<"General"|"Partial">("Partial");const [reason,setReason]=useState("");const [notes,setNotes]=useState("");const [lists,setLists]=useState<DraftList[]>([{id:crypto.randomUUID(),name:"Lista 1",products:[]}]);
 const reasons=useQuery({queryKey:["inventory-reasons",businessId,"StockCount"],queryFn:()=>inventoryApi.reasons({operationType:"StockCount"})});
 const categories=useQuery({queryKey:["product-categories",businessId],queryFn:()=>productsApi.listCategories(businessId,false)});
 const [category,setCategory]=useState("");const [busyCategory,setBusyCategory]=useState(false);
 const selected=new Set(lists.flatMap(x=>x.products.map(p=>p.productId)));
 async function addCategory(){if(!warehouse||!category)return;setBusyCategory(true);try{const ids=new Set([category]);let changed=true;while(changed){changed=false;for(const item of categories.data??[])if(item.parentProductCategoryId&&ids.has(item.parentProductCategoryId)&&!ids.has(item.productCategoryId)){ids.add(item.productCategoryId);changed=true}}const found:InventoryProductItem[]=[];for(const id of ids){let page=1;do{const result=await inventoryApi.products({warehouseId:warehouse,productCategoryId:id,page,pageSize:200});found.push(...result.items);if(page>=result.totalPages)break;page++}while(true)}const unique=found.filter((p,index)=>!selected.has(p.productId)&&found.findIndex(x=>x.productId===p.productId)===index);const label=(categories.data??[]).find(x=>x.productCategoryId===category)?.name??"Categoría";if(!unique.length){toast.info("La categoría no tiene productos disponibles o ya fueron asignados.");return}setLists(current=>[...current,{id:crypto.randomUUID(),name:label,products:unique}]);setCategory("")}catch{toast.error("No fue posible cargar los productos de la categoría.")}finally{setBusyCategory(false)}}
 const create=useMutation({mutationFn:()=>inventoryApi.createPhysicalCount({inventoryPhysicalCountId:crypto.randomUUID(),businessId,warehouseId:warehouse,scopeType:scope,reasonCode:reason,notes:notes.trim()||null,lists:lists.filter(x=>x.name.trim()&&x.products.length).map(x=>({listId:x.id,name:x.name.trim(),assignedUserId:null,productIds:x.products.map(p=>p.productId)}))}),onSuccess:onCreated,onError:(e:Error)=>toast.error(e.message||"No fue posible crear el inventario físico.")});
 function reset(){setLists([{id:crypto.randomUUID(),name:"Lista 1",products:[]}]);setReason("");setNotes("");onCancel()}
 return <div className="space-y-4"><div className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-4"><h3 className="font-semibold text-emerald-950">Conteo físico</h3><p className="text-sm text-emerald-900">La primera lista ya está lista. Agrega más únicamente si varios equipos o grupos contarán productos diferentes.</p></div><div className="space-y-4">
  <div className="grid gap-3 md:grid-cols-3"><Field label="Bodega"><Select value={warehouse} onValueChange={value=>{setWarehouse(value);setLists([{id:crypto.randomUUID(),name:"Lista 1",products:[]}])}}><SelectTrigger><SelectValue placeholder="Selecciona"/></SelectTrigger><SelectContent>{warehouses.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Alcance"><Select value={scope} onValueChange={v=>setScope(v as "General"|"Partial")}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="General">General</SelectItem><SelectItem value="Partial">Parcial</SelectItem></SelectContent></Select></Field><Field label="Motivo"><Select value={reason} onValueChange={setReason}><SelectTrigger><SelectValue placeholder="Selecciona"/></SelectTrigger><SelectContent>{reasons.data?.map(x=><SelectItem key={x.inventoryReasonId} value={x.code}>{x.name}</SelectItem>)}</SelectContent></Select></Field></div>
  <div className="flex flex-wrap items-end gap-2"><Field label="Agregar productos por categoría"><Select value={category} onValueChange={setCategory}><SelectTrigger className="w-72"><SelectValue placeholder="Selecciona categoría"/></SelectTrigger><SelectContent>{categories.data?.map(x=><SelectItem key={x.productCategoryId} value={x.productCategoryId}>{x.path}</SelectItem>)}</SelectContent></Select></Field><Button type="button" variant="outline" disabled={!warehouse||!category||busyCategory} onClick={()=>void addCategory()}>{busyCategory?<RefreshCw className="mr-2 h-4 w-4 animate-spin"/>:<Plus className="mr-2 h-4 w-4"/>}Agregar como lista</Button><Button type="button" variant="outline" disabled={!warehouse} onClick={()=>setLists(x=>[...x,{id:crypto.randomUUID(),name:`Lista ${x.length+1}`,products:[]}])}><Plus className="mr-2 h-4 w-4"/>Agregar otra lista</Button></div>
  <div className="space-y-3">{lists.map((list,index)=><Card key={list.id}><CardHeader className="pb-3"><div className="flex items-center gap-2"><Input value={list.name} onChange={e=>setLists(current=>current.map(x=>x.id===list.id?{...x,name:e.target.value}:x))}/><span className="whitespace-nowrap text-sm text-muted-foreground">{list.products.length} productos</span><Button size="icon" variant="ghost" disabled={lists.length===1} onClick={()=>setLists(x=>x.filter(y=>y.id!==list.id))}><Trash2 className="h-4 w-4"/></Button></div></CardHeader><CardContent className="space-y-2"><ProductPicker businessId={businessId} warehouseId={warehouse} selectedProductIds={new Set(list.products.map(x=>x.productId))} excludedProductIds={new Set([...selected].filter(id=>!list.products.some(p=>p.productId===id)))} disabled={!warehouse} onSelect={product=>setLists(current=>current.map((x,i)=>i===index?{...x,products:[...x.products,product]}:x))}/>{list.products.length>0&&<div className="flex max-h-28 flex-wrap gap-1 overflow-y-auto">{list.products.map(product=><button key={product.productId} className="rounded-full border px-2 py-1 text-xs hover:bg-red-50" onClick={()=>setLists(current=>current.map(x=>x.id===list.id?{...x,products:x.products.filter(p=>p.productId!==product.productId)}:x))}>{product.productCode} · {product.productName} ×</button>)}</div>}</CardContent></Card>)}</div>
  <Field label="Observaciones"><Textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000}/></Field>
  </div><div className="flex justify-end gap-2 border-t pt-4"><Button variant="outline" onClick={reset}>Cancelar</Button><Button disabled={!warehouse||!reason||!lists.some(x=>x.products.length)||create.isPending} onClick={()=>create.mutate()}>{create.isPending?"Creando…":"Crear conteo físico"}</Button></div></div>
}

function PhysicalCountDetailDialog({detail,businessId,canManage,canCapture,onClose,onChanged}:{detail?:InventoryPhysicalCountDetail;businessId:string;canManage:boolean;canCapture:boolean;onClose:()=>void;onChanged:(value:InventoryPhysicalCountDetail)=>void}){
 const start=useMutation({mutationFn:()=>inventoryApi.startPhysicalCount(detail!.inventoryPhysicalCountId),onSuccess:onChanged,onError:(e:Error)=>toast.error(e.message)});const close=useMutation({mutationFn:()=>inventoryApi.closePhysicalCount(detail!.inventoryPhysicalCountId,businessId),onSuccess:value=>{onChanged(value);toast.success(`${value.finalDocumentNumber} fue enviado al motor`)},onError:(e:Error)=>toast.error(e.message)});
 if(!detail)return null;const lines=detail.lists.flatMap(x=>x.lines);const counted=lines.filter(x=>x.countedQuantity!=null).length;const precounted=lines.filter(x=>x.preCountQuantity!=null).length;
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="flex max-h-[94dvh] max-w-6xl flex-col overflow-hidden p-0"><DialogHeader className="border-b px-6 py-5"><DialogTitle>Inventario físico · {detail.warehouseName}</DialogTitle><DialogDescription>{detail.scopeType==="General"?"General":"Parcial"} · {statusLabels[detail.status]??detail.status} · abierto {formatDateTime(detail.createdAt)}</DialogDescription></DialogHeader><div className="space-y-5 overflow-y-auto px-6 py-5"><div className="grid gap-3 sm:grid-cols-4"><Metric label="Productos" value={String(lines.length)}/><Metric label="Precontados" value={`${precounted}/${lines.length}`}/><Metric label="Contados" value={`${counted}/${lines.length}`}/><Metric label="Diferencias" value={String(lines.filter(x=>(x.approvedDifference??0)!==0).length)}/></div>
  {detail.status==="Draft"&&<Card><CardContent className="flex items-center justify-between gap-4 pt-6"><div><h3 className="font-semibold">Listas listas para iniciar</h3><p className="text-sm text-muted-foreground">Al iniciar se bloquea la composición y comienza el preconteo.</p></div>{canManage&&<Button disabled={start.isPending} onClick={()=>start.mutate()}>Iniciar preconteo</Button>}</CardContent></Card>}
  {(detail.status==="PreCounting"||detail.status==="Counting")&&detail.lists.map(list=><CaptureListCard key={`${list.listId}-${detail.status}-${list.status}`} countId={detail.inventoryPhysicalCountId} businessId={businessId} list={list} stage={detail.status==="PreCounting"?"pre-count":"count"} canCapture={canCapture} onChanged={onChanged}/>)}
  {(detail.status==="Review"||detail.status==="Closing"||detail.status==="Closed")&&<><Card><CardHeader><CardTitle>Consolidado</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[850px] text-sm"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr>{["Producto","Lista","Sistema base","Preconteo","Conteo","Esperado al contar","Diferencia"].map(x=><th key={x} className="px-4 py-3 text-left">{x}</th>)}</tr></thead><tbody>{detail.lists.flatMap(list=>list.lines.map(line=><tr key={line.productId} className="border-t"><td className="px-4 py-3">{line.productCode} · {line.productName}</td><td className="px-4 py-3">{list.name}</td><td className="px-4 py-3">{fmt(line.systemQuantityAtBase)}</td><td className="px-4 py-3">{fmt(line.preCountQuantity??0)}</td><td className="px-4 py-3">{fmt(line.countedQuantity??0)}</td><td className="px-4 py-3">{fmt(line.expectedQuantityAtCount??0)}</td><td className={`px-4 py-3 font-semibold ${(line.approvedDifference??0)<0?"text-red-700":(line.approvedDifference??0)>0?"text-emerald-700":""}`}>{(line.approvedDifference??0)>0?"+":""}{fmt(line.approvedDifference??0)}</td></tr>))}</tbody></table></CardContent></Card>{detail.status==="Review"&&canManage&&<div className="flex justify-end"><Button disabled={close.isPending} onClick={()=>close.mutate()}><CheckCircle2 className="mr-2 h-4 w-4"/>{close.isPending?"Enviando…":"Enviar cierre al motor"}</Button></div>}{detail.finalDocumentNumber&&<p className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">Documento definitivo: <strong>{detail.finalDocumentNumber}</strong></p>}</>}
 </div><DialogFooter className="border-t px-6 py-4"><Button variant="outline" onClick={onClose}>Cerrar ventana</Button></DialogFooter></DialogContent></Dialog>
}

function CaptureListCard({countId,businessId,list,stage,canCapture,onChanged}:{countId:string;businessId:string;list:InventoryPhysicalCountList;stage:"pre-count"|"count";canCapture:boolean;onChanged:(value:InventoryPhysicalCountDetail)=>void}){
 const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(list.lines.map(line=>[line.productId,String(stage==="pre-count"?line.preCountQuantity??"":line.countedQuantity??"")])));const submitted=stage==="pre-count"?list.status==="PreCounted":list.status==="Counted";
 const save=useMutation({mutationFn:(submit:boolean)=>inventoryApi.savePhysicalCapture(countId,list.listId,stage,{businessId,submit,lines:list.lines.filter(line=>values[line.productId]!=="").map(line=>({productId:line.productId,quantity:Number(values[line.productId])}))}),onSuccess:(value,submit)=>{onChanged(value);toast.success(submit?`${stage==="pre-count"?"Preconteo":"Conteo"} enviado`:"Avance guardado")},onError:(e:Error)=>toast.error(e.message)});const complete=list.lines.every(line=>values[line.productId]!==""&&Number(values[line.productId])>=0);
 return <Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2 text-base"><ClipboardList className="h-4 w-4"/>{list.name}</CardTitle><span className="text-sm text-muted-foreground">{submitted?"Enviada":`${list.lines.length} productos`}</span></div></CardHeader><CardContent className="space-y-3"><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[650px] text-sm"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr><th className="px-3 py-2 text-left">Producto</th>{stage==="count"&&<th className="px-3 py-2 text-right">Preconteo</th>}<th className="px-3 py-2 text-right">{stage==="pre-count"?"Preconteo":"Conteo"}</th></tr></thead><tbody>{list.lines.map(line=><tr key={line.productId} className="border-t"><td className="px-3 py-2">{line.productCode} · {line.productName}</td>{stage==="count"&&<td className="px-3 py-2 text-right">{fmt(line.preCountQuantity??0)}</td>}<td className="px-3 py-2"><Input className="ml-auto w-36 text-right" inputMode="decimal" disabled={submitted||!canCapture} value={values[line.productId]??""} onChange={e=>setValues(x=>({...x,[line.productId]:e.target.value}))}/></td></tr>)}</tbody></table></div>{!submitted&&canCapture&&<div className="flex justify-end gap-2"><Button variant="outline" disabled={save.isPending||!Object.values(values).some(x=>x!=="")} onClick={()=>save.mutate(false)}>Guardar avance</Button><Button disabled={save.isPending||!complete} onClick={()=>save.mutate(true)}>Enviar {stage==="pre-count"?"preconteo":"conteo"}</Button></div>}</CardContent></Card>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1 text-sm"><span className="font-medium">{label}</span>{children}</label>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-muted/20 p-4"><p className="text-xs uppercase text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>}
