"use client";

import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Plus, RefreshCw, Save } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { ProductPicker } from "@/components/products/product-picker";
import { inventoryApi, type InventoryPhysicalCountDetail, type InventoryProductItem, type InventoryReconciliationDetail, type InventoryReconciliationProduct } from "@/services/api/inventory";
import { productsApi } from "@/services/api/products";
import { formatCurrency, formatDateTime } from "@/lib/utils";

type Warehouse = { id:string;name:string };
type ReconciliationSection = "Counted"|"Uncounted";
const draftStatusLabels:Record<string,string>={InProgress:"En progreso",Ready:"Listo para conciliar"};
const fmt=(value:number)=>new Intl.NumberFormat("es-CO",{maximumFractionDigits:6}).format(value);

export function InventoryPhysicalCountWorkspace({businessId,warehouseId,search,permissions}:{businessId:string;warehouses:Warehouse[];warehouseId?:string;search?:string;permissions:Set<string>}){
 const client=useQueryClient();
 const [selected,setSelected]=useState<{count:InventoryPhysicalCountDetail;draftId:string}>();
 const query=useQuery({queryKey:["inventory-physical-count-drafts",businessId,warehouseId,search],queryFn:()=>inventoryApi.physicalCountDrafts({warehouseId,search})});
 async function resume(countId:string,draftId:string){try{const count=await client.fetchQuery({queryKey:["inventory-physical-count",businessId,countId],queryFn:()=>inventoryApi.physicalCount(countId)});setSelected({count,draftId})}catch{toast.error("No fue posible recuperar el borrador.")}}
 async function changed(count:InventoryPhysicalCountDetail){setSelected(current=>current?{count,draftId:current.draftId}:undefined);await Promise.all([query.refetch(),client.invalidateQueries({queryKey:["inventory-operations"]})])}
 return <div className="space-y-4">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Borradores de inventario</h2><p className="text-sm text-muted-foreground">Recupera un trabajo guardado y continúa exactamente donde quedó.</p></div><Button variant="outline" size="sm" onClick={()=>void query.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Actualizar</Button></div>
  <Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-sm"><thead className="border-b bg-muted/50 text-xs uppercase text-muted-foreground"><tr>{["Borrador","Inventario","Bodega","Avance","Propietario","Actualizado","Estado",""] .map(label=><th key={label} className="px-4 py-3 text-left">{label}</th>)}</tr></thead><tbody>{query.isLoading?<EmptyRow columns={8} text="Cargando borradores…"/>:(query.data??[]).length===0?<EmptyRow columns={8} text="No hay borradores de inventario para estos filtros."/>:(query.data??[]).map(draft=><tr key={draft.draftId} className="border-b"><td className="px-4 py-3 font-medium">{draft.name}</td><td className="px-4 py-3">{draft.scopeType==="General"?"General":"Parcial"}</td><td className="px-4 py-3">{draft.warehouseName}</td><td className="px-4 py-3">{draft.countedProductCount}/{draft.productCount}</td><td className="px-4 py-3 font-mono text-xs">{draft.ownerUserId.slice(0,8)}</td><td className="px-4 py-3">{formatDateTime(draft.updatedAt)}</td><td className="px-4 py-3">{draftStatusLabels[draft.status]??draft.status}</td><td className="px-4 py-3 text-right"><Button size="sm" variant="outline" onClick={()=>void resume(draft.inventoryPhysicalCountId,draft.draftId)}>Continuar</Button></td></tr>)}</tbody></table></CardContent></Card>
  <DraftWorkspaceDialog value={selected} businessId={businessId} canCapture={permissions.has("inventory.physical-counts.capture")} onClose={()=>setSelected(undefined)} onChanged={value=>void changed(value)}/>
 </div>;
}

export function PhysicalCountCreationForm({businessId,warehouses,onCancel,onCreated}:{businessId:string;warehouses:Warehouse[];onCancel:()=>void;onCreated:(value:InventoryPhysicalCountDetail)=>void}){
 const [warehouse,setWarehouse]=useState(warehouses.length===1?warehouses[0].id:"");
 const [scope,setScope]=useState<"General"|"Partial">("Partial");
 const [reason,setReason]=useState("");const [notes,setNotes]=useState("");const [draftName,setDraftName]=useState("Conteo inicial");const [products,setProducts]=useState<InventoryProductItem[]>([]);
 const reasons=useQuery({queryKey:["inventory-reasons",businessId,"StockCount"],queryFn:()=>inventoryApi.reasons({operationType:"StockCount"})});
 const categories=useQuery({queryKey:["product-categories",businessId],queryFn:()=>productsApi.listCategories(businessId,false)});
 const [category,setCategory]=useState("");const [busyCategory,setBusyCategory]=useState(false);const selected=new Set(products.map(product=>product.productId));
 async function addCategory(){if(!warehouse||!category)return;setBusyCategory(true);try{const categoryIds=new Set([category]);let changed=true;while(changed){changed=false;for(const item of categories.data??[])if(item.parentProductCategoryId&&categoryIds.has(item.parentProductCategoryId)&&!categoryIds.has(item.productCategoryId)){categoryIds.add(item.productCategoryId);changed=true}}const found:InventoryProductItem[]=[];for(const id of categoryIds){let page=1;do{const result=await inventoryApi.products({warehouseId:warehouse,productCategoryId:id,page,pageSize:200});found.push(...result.items);if(page>=result.totalPages)break;page++}while(true)}setProducts(current=>[...current,...found.filter((product,index)=>!selected.has(product.productId)&&found.findIndex(item=>item.productId===product.productId)===index)]);setCategory("")}catch{toast.error("No fue posible cargar la categoría.")}finally{setBusyCategory(false)}}
 const create=useMutation({mutationFn:()=>inventoryApi.createPhysicalCount({inventoryPhysicalCountId:crypto.randomUUID(),businessId,warehouseId:warehouse,scopeType:scope,reasonCode:reason,notes:notes.trim()||null,initialDraftName:draftName.trim(),productIds:scope==="General"?[]:products.map(product=>product.productId)}),onSuccess:onCreated,onError:(error:Error)=>toast.error(error.message||"No fue posible crear el inventario.")});
 return <div className="space-y-5"><div className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-4"><h3 className="font-semibold text-emerald-950">Nuevo inventario físico</h3><p className="text-sm text-emerald-900">Abre el alcance y comienza de inmediato con un borrador recuperable.</p></div>
  <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Field label="Bodega"><Select value={warehouse} onValueChange={value=>{setWarehouse(value);setProducts([])}}><SelectTrigger><SelectValue placeholder="Selecciona"/></SelectTrigger><SelectContent>{warehouses.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Alcance"><Select value={scope} onValueChange={value=>{setScope(value as "General"|"Partial");setProducts([])}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="General">General</SelectItem><SelectItem value="Partial">Parcial</SelectItem></SelectContent></Select></Field><Field label="Motivo"><Select value={reason} onValueChange={setReason}><SelectTrigger><SelectValue placeholder="Selecciona"/></SelectTrigger><SelectContent>{reasons.data?.map(item=><SelectItem key={item.inventoryReasonId} value={item.code}>{item.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Nombre del borrador"><Input value={draftName} onChange={event=>setDraftName(event.target.value)} maxLength={120}/></Field></div>
  {scope==="General"?<div className="rounded-xl border bg-muted/20 p-4"><p className="font-medium">Se incluirán automáticamente todos los productos que manejan inventario.</p><p className="text-sm text-muted-foreground">No necesitas cargar ni mantener una lista manual.</p></div>:<Card><CardHeader><CardTitle className="text-base">Productos incluidos</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap items-end gap-2"><Field label="Agregar por categoría"><Select value={category} onValueChange={setCategory}><SelectTrigger className="w-72"><SelectValue placeholder="Selecciona categoría"/></SelectTrigger><SelectContent>{categories.data?.map(item=><SelectItem key={item.productCategoryId} value={item.productCategoryId}>{item.path}</SelectItem>)}</SelectContent></Select></Field><Button type="button" variant="outline" disabled={!category||busyCategory} onClick={()=>void addCategory()}><Plus className="mr-2 h-4 w-4"/>Agregar</Button></div><ProductPicker businessId={businessId} warehouseId={warehouse} selectedProductIds={selected} disabled={!warehouse} onSelect={product=>setProducts(current=>current.some(item=>item.productId===product.productId)?current:[...current,product])}/><div className="flex max-h-32 flex-wrap gap-1 overflow-y-auto">{products.map(product=><button type="button" key={product.productId} className="rounded-full border px-2 py-1 text-xs hover:bg-red-50" onClick={()=>setProducts(current=>current.filter(item=>item.productId!==product.productId))}>{product.productCode} · {product.productName} ×</button>)}</div></CardContent></Card>}
  <Field label="Observaciones"><Textarea value={notes} onChange={event=>setNotes(event.target.value)} maxLength={1000}/></Field>
  <div className="flex justify-end gap-2 border-t pt-4"><Button variant="outline" onClick={onCancel}>Cancelar</Button><Button disabled={!warehouse||!reason||!draftName.trim()||(scope==="Partial"&&products.length===0)||create.isPending} onClick={()=>create.mutate()}>{create.isPending?"Creando…":"Abrir conteo"}</Button></div>
 </div>;
}

export function InventoryReconciliationDialog({open,businessId,warehouseId,onClose}:{open:boolean;businessId:string;warehouseId?:string;onClose:()=>void}){
 const client=useQueryClient();const [countId,setCountId]=useState("");const [selectedDrafts,setSelectedDrafts]=useState<Set<string>>(new Set());const [result,setResult]=useState<InventoryReconciliationDetail>();const [section,setSection]=useState<ReconciliationSection>("Counted");const [valuation,setValuation]=useState<"cost"|"average">("cost");const [draftName,setDraftName]=useState("");const [confirmZero,setConfirmZero]=useState(false);
 const drafts=useQuery({queryKey:["inventory-physical-count-drafts",businessId,warehouseId,"reconcile"],queryFn:()=>inventoryApi.physicalCountDrafts({warehouseId}),enabled:open});
 const candidates=drafts.data??[];
 useEffect(()=>{if(!open){setCountId("");setSelectedDrafts(new Set());setResult(undefined);setDraftName("");setConfirmZero(false)}},[open]);
 const prepare=useMutation({mutationFn:()=>inventoryApi.prepareReconciliation(countId,{businessId,drafts:candidates.filter(draft=>selectedDrafts.has(draft.draftId)).map(draft=>({draftId:draft.draftId,version:draft.version}))}),onSuccess:value=>{setResult(value);setSection("Counted");toast.success("Borradores conciliados por producto.")},onError:(error:Error)=>toast.error(error.message)});
 const save=useMutation({mutationFn:()=>inventoryApi.saveReconciliationDraft(countId,result!.reconciliationId,{businessId,section,draftId:crypto.randomUUID(),name:draftName.trim()}),onSuccess:async()=>{toast.success(section==="Counted"?"Consolidado guardado como borrador.":"No contados guardados en un borrador para continuar.");setDraftName("");await Promise.all([client.invalidateQueries({queryKey:["inventory-physical-count"]}),client.invalidateQueries({queryKey:["inventory-physical-count-drafts"]})])},onError:(error:Error)=>toast.error(error.message)});
 const apply=useMutation({mutationFn:()=>inventoryApi.applyReconciliation(countId,result!.reconciliationId,{businessId,section}),onSuccess:async()=>{toast.success(section==="Counted"?"Conteo conciliado enviado para aplicar.":"Inventario en cero enviado para aplicar.");setResult(await inventoryApi.reconciliation(countId));await Promise.all([client.invalidateQueries({queryKey:["inventory-operations"]}),client.invalidateQueries({queryKey:["inventory-physical-counts"]}),client.invalidateQueries({queryKey:["inventory-physical-count-drafts"]})])},onError:(error:Error)=>toast.error(error.message)});
 const products=result?.products.filter(product=>product.status===section)??[];
 const readyCount=candidates.filter(draft=>draft.status==="Ready").length;
 function selectDraft(draftId:string,inventoryPhysicalCountId:string,checked:boolean){const next=new Set(selectedDrafts);if(checked){if(countId&&countId!==inventoryPhysicalCountId)return;next.add(draftId);setCountId(inventoryPhysicalCountId)}else{next.delete(draftId);if(next.size===0)setCountId("")}setSelectedDrafts(next)}
 return <Dialog open={open} onOpenChange={value=>!value&&onClose()}><DialogContent className="flex max-h-[94dvh] max-w-7xl flex-col overflow-hidden p-0"><DialogHeader className="border-b px-6 py-5"><DialogTitle>Conciliación de inventario</DialogTitle><DialogDescription>{result?"Revisa los productos agrupados antes de guardar o aplicar.":"Selecciona los borradores que se deben agrupar en esta conciliación."}</DialogDescription></DialogHeader><div className="space-y-5 overflow-y-auto px-6 py-5">
  {!result?<><Card><CardHeader><CardTitle className="text-base">Todos los borradores · {readyCount} listos</CardTitle><p className="text-sm text-muted-foreground">Puedes agrupar borradores del mismo inventario. Al escoger el primero, los de otros inventarios quedan visibles pero no seleccionables.</p></CardHeader><CardContent className="space-y-2">{drafts.isLoading?<p className="text-sm text-muted-foreground">Cargando…</p>:candidates.length===0?<p className="text-sm text-muted-foreground">No hay borradores de inventario.</p>:candidates.map(draft=>{const unavailable=draft.status!=="Ready"||(!!countId&&countId!==draft.inventoryPhysicalCountId);return <label key={draft.draftId} className={`flex items-center justify-between gap-4 rounded-xl border p-4 ${unavailable?"opacity-60":"cursor-pointer hover:bg-muted/30"}`}><span className="flex items-center gap-3"><input type="checkbox" disabled={unavailable} checked={selectedDrafts.has(draft.draftId)} onChange={event=>selectDraft(draft.draftId,draft.inventoryPhysicalCountId,event.target.checked)}/><span><strong>{draft.name}</strong><span className="block text-xs text-muted-foreground">{draft.warehouseName} · {draft.scopeType==="General"?"General":"Parcial"} · {draft.countedProductCount}/{draft.productCount} contados</span><span className="block text-xs text-muted-foreground">Actualizado {formatDateTime(draft.updatedAt)}</span></span></span><span className="text-xs">{draftStatusLabels[draft.status]??draft.status}</span></label>})}</CardContent></Card><div className="flex justify-end"><Button disabled={!countId||selectedDrafts.size===0||prepare.isPending} onClick={()=>prepare.mutate()}><ClipboardCheck className="mr-2 h-4 w-4"/>{prepare.isPending?"Conciliando…":"Conciliar seleccionados"}</Button></div></>:<><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{result.drafts.length} borradores agrupados</p><p className="text-sm text-muted-foreground">Las cantidades repetidas del mismo producto fueron sumadas.</p></div><div className="flex gap-2"><Select value={valuation} onValueChange={value=>setValuation(value as "cost"|"average")}><SelectTrigger className="w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="cost">Precio costo</SelectItem><SelectItem value="average">Costo promedio</SelectItem></SelectContent></Select><Button variant="outline" onClick={()=>setResult(undefined)}>Cambiar selección</Button></div></div>
  <Tabs value={section} onValueChange={value=>{setSection(value as ReconciliationSection);setDraftName("");setConfirmZero(false)}}><TabsList className="grid w-full grid-cols-2"><TabsTrigger value="Counted">Contados · {result.products.filter(product=>product.status==="Counted").length}</TabsTrigger><TabsTrigger value="Uncounted">No contados · {result.products.filter(product=>product.status==="Uncounted").length}</TabsTrigger></TabsList><TabsContent value="Counted"><ReconciliationTable products={products} valuation={valuation}/></TabsContent><TabsContent value="Uncounted"><ReconciliationTable products={products} valuation={valuation}/></TabsContent></Tabs>
  <Card><CardContent className="space-y-4 pt-6"><div><p className="font-medium">{section==="Counted"?"Guardar el resultado para revisarlo después":"Guardar todos los no contados para continuar"}</p><p className="text-sm text-muted-foreground">{section==="Counted"?"Crea un borrador poblado con las cantidades sumadas.":"Crea un borrador poblado con todos estos productos y cantidades pendientes."}</p></div><div className="flex flex-wrap gap-2"><Input className="min-w-64 flex-1" value={draftName} onChange={event=>setDraftName(event.target.value)} placeholder={section==="Counted"?"Nombre del borrador consolidado":"Nombre del borrador de no contados"}/><Button variant="outline" disabled={!draftName.trim()||products.length===0||save.isPending} onClick={()=>save.mutate()}><Save className="mr-2 h-4 w-4"/>Guardar como borrador</Button></div><div className="border-t pt-4">{section==="Uncounted"&&<label className="mb-3 flex items-start gap-2 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><input className="mt-1" type="checkbox" checked={confirmZero} onChange={event=>setConfirmZero(event.target.checked)}/><span><strong>Confirmo que deseo poner en cero todos los productos no contados.</strong><span className="block">Esta acción genera un inventario normal y ajusta su existencia a cero.</span></span></label>}<div className="flex justify-end"><Button variant={section==="Uncounted"?"destructive":"default"} disabled={products.length===0||apply.isPending||(section==="Uncounted"&&!confirmZero)} onClick={()=>apply.mutate()}>{section==="Uncounted"?<AlertTriangle className="mr-2 h-4 w-4"/>:<CheckCircle2 className="mr-2 h-4 w-4"/>}{apply.isPending?"Aplicando…":section==="Uncounted"?"Aplicar todos en cero":"Aplicar contados"}</Button></div></div></CardContent></Card></>}
 </div><DialogFooter className="border-t px-6 py-4"><Button variant="outline" onClick={onClose}>Cerrar</Button></DialogFooter></DialogContent></Dialog>;
}

function DraftWorkspaceDialog({value,businessId,canCapture,onClose,onChanged}:{value?:{count:InventoryPhysicalCountDetail;draftId:string};businessId:string;canCapture:boolean;onClose:()=>void;onChanged:(value:InventoryPhysicalCountDetail)=>void}){
 const draft=value?.count.drafts.find(item=>item.draftId===value.draftId);const [name,setName]=useState("");const [verification,setVerification]=useState(false);const [initialValues,setInitialValues]=useState<Record<string,string>>({});const [verificationValues,setVerificationValues]=useState<Record<string,string>>({});const [reasons,setReasons]=useState<Record<string,string>>({});
 useEffect(()=>{if(!draft)return;setName(draft.name);setVerification(draft.lines.some(line=>line.verificationQuantity!==null));setInitialValues(Object.fromEntries(draft.lines.map(line=>[line.productId,line.initialQuantity===null?"":String(line.initialQuantity)])));setVerificationValues(Object.fromEntries(draft.lines.map(line=>[line.productId,line.verificationQuantity===null?"":String(line.verificationQuantity)])));setReasons(Object.fromEntries(draft.lines.map(line=>[line.productId,line.pendingReason??""])))},[draft]);
 const save=useMutation({mutationFn:(ready:boolean)=>inventoryApi.savePhysicalCountDraft(value!.count.inventoryPhysicalCountId,draft!.draftId,{businessId,version:draft!.version,name,readyForReconciliation:ready,lines:draft!.lines.map(line=>({productId:line.productId,initialQuantity:numberOrNull(initialValues[line.productId]),verificationQuantity:verification?numberOrNull(verificationValues[line.productId]):null,pendingReason:numberOrNull(initialValues[line.productId])===null?(reasons[line.productId]||null):null}))}),onSuccess:(result,ready)=>{onChanged(result);toast.success(ready?"Borrador listo para conciliar.":"Borrador guardado.")},onError:(error:Error)=>toast.error(error.message)});
 if(!value||!draft)return null;const counted=draft.lines.filter(line=>initialValues[line.productId]!=="").length;
 return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="flex max-h-[94dvh] max-w-6xl flex-col overflow-hidden p-0"><DialogHeader className="border-b px-6 py-5"><DialogTitle>Continuar conteo · {value.count.warehouseName}</DialogTitle><DialogDescription>{value.count.scopeType==="General"?"Inventario general":"Inventario parcial"} · guardado {formatDateTime(draft.updatedAt)}</DialogDescription></DialogHeader><div className="space-y-4 overflow-y-auto px-6 py-5"><div className="flex flex-wrap items-end gap-3"><Field label="Nombre del borrador"><Input className="w-72" value={name} onChange={event=>setName(event.target.value)}/></Field><label className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm"><input type="checkbox" checked={verification} onChange={event=>setVerification(event.target.checked)}/>Agregar conteo de verificación</label><span className="text-sm text-muted-foreground">{counted}/{draft.lines.length} contados</span></div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[850px] text-sm"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3 text-left">Producto</th><th className="px-4 py-3 text-right">Conteo inicial</th>{verification&&<th className="px-4 py-3 text-right">Conteo de verificación</th>}<th className="px-4 py-3 text-left">Motivo pendiente</th></tr></thead><tbody>{draft.lines.map(line=><tr key={line.productId} className="border-t"><td className="px-4 py-3">{line.productCode} · {line.productName}</td><td className="px-4 py-3"><Input className="ml-auto w-36 text-right" inputMode="decimal" disabled={!canCapture} value={initialValues[line.productId]??""} onChange={event=>setInitialValues(current=>({...current,[line.productId]:event.target.value}))}/></td>{verification&&<td className="px-4 py-3"><Input aria-label={`Verificación ${line.productName}`} className="ml-auto w-36 text-right" inputMode="decimal" disabled={!canCapture||initialValues[line.productId]===""} value={verificationValues[line.productId]??""} onChange={event=>setVerificationValues(current=>({...current,[line.productId]:event.target.value}))}/></td>}<td className="px-4 py-3"><Input disabled={!canCapture||initialValues[line.productId]!==""} value={reasons[line.productId]??""} onChange={event=>setReasons(current=>({...current,[line.productId]:event.target.value}))} placeholder={initialValues[line.productId]===""?"Opcional":"—"}/></td></tr>)}</tbody></table></div></div><DialogFooter className="border-t px-6 py-4"><Button variant="outline" onClick={onClose}>Cerrar</Button>{canCapture&&<><Button variant="outline" disabled={!name.trim()||save.isPending} onClick={()=>save.mutate(false)}>Guardar borrador</Button><Button disabled={!name.trim()||counted===0||save.isPending} onClick={()=>save.mutate(true)}>Listo para conciliar</Button></>}</DialogFooter></DialogContent></Dialog>;
}

function ReconciliationTable({products,valuation}:{products:InventoryReconciliationProduct[];valuation:"cost"|"average"}){return <div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full min-w-[950px] text-sm"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3 text-left">Producto</th><th className="px-4 py-3 text-left">Aportes</th><th className="px-4 py-3 text-right">Cantidad conciliada</th><th className="px-4 py-3 text-right">Existencia sistema</th><th className="px-4 py-3 text-right">Diferencia</th><th className="px-4 py-3 text-right">{valuation==="cost"?"Precio costo":"Costo promedio"}</th><th className="px-4 py-3 text-right">Valorización</th></tr></thead><tbody>{products.length===0?<EmptyRow columns={7} text="No hay productos en esta sección."/>:products.map(product=>{const cost=valuation==="cost"?product.unitCost:product.averageUnitCost;const quantity=product.proposedQuantity??0;return <tr key={product.productId} className="border-t"><td className="px-4 py-3"><strong>{product.productName}</strong><span className="block text-xs text-muted-foreground">{product.productCode}</span></td><td className="px-4 py-3">{product.sources.length===0?"Sin conteo":product.sources.map(source=>`${source.draftName}: ${fmt(source.finalQuantity)}`).join(" + ")}</td><td className="px-4 py-3 text-right font-semibold">{product.proposedQuantity===null?"No contado":fmt(product.proposedQuantity)}</td><td className="px-4 py-3 text-right">{fmt(product.systemQuantity)}</td><td className="px-4 py-3 text-right">{product.proposedQuantity===null?"—":fmt(product.proposedQuantity-product.systemQuantity)}</td><td className="px-4 py-3 text-right">{cost===null?"Restringido":formatCurrency(cost)}</td><td className="px-4 py-3 text-right font-medium">{cost===null?"Restringido":formatCurrency(quantity*cost)}</td></tr>})}</tbody></table></div>}
function numberOrNull(value:string|undefined){return value===undefined||value.trim()===""?null:Number(value)}
function EmptyRow({columns,text}:{columns:number;text:string}){return <tr><td colSpan={columns} className="p-10 text-center text-muted-foreground">{text}</td></tr>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1.5 text-sm"><span className="font-medium">{label}</span>{children}</label>}
