"use client";
import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {CheckCircle2,RefreshCw,Route,ShoppingCart,Users} from "lucide-react";
import {salesReportingApi} from "@/services/api/sales-reporting";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {PageError} from "@/components/ui/page-error";
import {PageLoading} from "@/components/ui/page-loading";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {DatePicker} from "@/components/ui/date-picker";

const iso=(date:Date)=>date.toISOString().slice(0,10),now=new Date(),monthAgo=new Date(now.getTime()-29*86400000);
export default function VisitsReportPage(){
 const [from,setFrom]=useState(iso(monthAgo)),[to,setTo]=useState(iso(now)),[status,setStatus]=useState("all"),[page,setPage]=useState(1);
 const query=useQuery({queryKey:["commercial-visits",from,to,status,page],queryFn:()=>salesReportingApi.visits({from,to,status:status==="all"?undefined:status as "Visited"|"Skipped",page,pageSize:50})});
 if(query.isLoading)return <PageLoading/>;if(query.isError||!query.data)return <PageError onRetry={()=>void query.refetch()}/>;const data=query.data;
 return <div className="space-y-6"><header className="rounded-3xl bg-gradient-to-br from-slate-950 via-teal-950 to-cyan-800 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-200">Motor de reporting comercial</p><div className="mt-2 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-black">Visitas comerciales</h1><p className="mt-2 text-sm text-cyan-50/80">Visitas realizadas, resultados sin pedido y efectividad comercial desde hechos proyectados.</p></div><Button className="bg-white text-slate-950" onClick={()=>void query.refetch()} disabled={query.isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${query.isFetching?"animate-spin":""}`}/>Actualizar</Button></div></header>
 <Card className="rounded-3xl"><CardContent className="grid gap-3 p-4 md:grid-cols-4"><label className="text-sm"><span className="mb-1 block font-medium">Desde</span><DatePicker value={from} max={to||undefined} onChange={value=>{setFrom(value);setPage(1)}}/></label><label className="text-sm"><span className="mb-1 block font-medium">Hasta</span><DatePicker value={to} min={from||undefined} onChange={value=>{setTo(value);setPage(1)}}/></label><label className="text-sm"><span className="mb-1 block font-medium">Resultado</span><Select value={status} onValueChange={v=>{setStatus(v);setPage(1)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos</SelectItem><SelectItem value="Visited">Visitados</SelectItem><SelectItem value="Skipped">Omitidos</SelectItem></SelectContent></Select></label></CardContent></Card>
 <div className="grid gap-3 md:grid-cols-3"><Metric title="Resultados registrados" value={data.totalCount} icon={Users}/><Metric title="Visitas realizadas" value={data.visitedCount} icon={CheckCircle2}/><Metric title="Efectividad" value={`${data.effectivenessPercent}%`} detail={`${data.orderedCount} con pedido`} icon={ShoppingCart}/></div>
 <Card className="overflow-hidden rounded-3xl"><CardHeader><CardTitle>Detalle proyectado</CardTitle><CardDescription>Cada fila conserva vendedor, ruta, zona, cliente y resultado al momento de la visita.</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted/50 text-left"><tr><th className="p-3">Fecha</th><th>Vendedor</th><th>Ruta</th><th>Cliente</th><th>Resultado</th><th className="pr-3">Detalle</th></tr></thead><tbody>{data.items.map(row=><tr className="border-t" key={row.routeVisitId}><td className="p-3">{new Date(row.occurredAt).toLocaleString("es-CO")}</td><td>{row.sellerName}</td><td>{row.routeName}<small className="block text-muted-foreground">{row.zoneName??"Sin zona"}</small></td><td>{row.customerName}</td><td><Badge variant={row.hasOrder?"secondary":"outline"}>{row.hasOrder?"Con pedido":row.status==="Visited"?"Visitado sin pedido":"Omitido"}</Badge></td><td className="max-w-80 pr-3 text-muted-foreground">{row.visitObservation??row.skipReason??"—"}</td></tr>)}</tbody></table>{!data.items.length&&<p className="p-10 text-center text-muted-foreground">No hay visitas proyectadas en este rango.</p>}</div><div className="flex items-center justify-between border-t p-4"><span className="text-sm text-muted-foreground">{data.totalCount} resultados</span><div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</Button><Button variant="outline" disabled={page*50>=data.totalCount} onClick={()=>setPage(p=>p+1)}>Siguiente</Button></div></div></CardContent></Card></div>;
}
function Metric({title,value,detail,icon:Icon}:{title:string;value:string|number;detail?:string;icon:typeof Route}){return <Card className="rounded-2xl"><CardContent className="p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase text-muted-foreground">{title}</span><Icon className="h-5 w-5 text-teal-700"/></div><strong className="mt-3 block text-3xl">{value}</strong>{detail&&<small className="text-muted-foreground">{detail}</small>}</CardContent></Card>}
