"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { ArrowDown, ArrowUp, CalendarDays, Download, MapPinned, Pencil, Plus, Printer, Route, Search, Trash2, UserRound } from "lucide-react";
import { toast } from "sonner";
import { DataTable } from "@/components/tables/data-table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useAddRouteStops, useCreateRoute, useCreateRouteZone, useRemoveRouteStop, useReorderRouteStops, useRouteCandidates, useRouteDetail, useRouteOptions, useRoutes, useSetRouteStatus, useUpdateRoute } from "@/hooks/use-routes";
import type { RouteCandidateSite, RouteScheduleInput, SalesRouteListItem, SalesRouteStop } from "@/services/api/routes";
import { routesApi } from "@/services/api/routes";
import { useAuthStore } from "@/stores/auth-store";
import { useBusinessContextStore } from "@/stores/business-context-store";

const days=[{id:1,short:"Lun",name:"Lunes"},{id:2,short:"Mar",name:"Martes"},{id:3,short:"Mié",name:"Miércoles"},{id:4,short:"Jue",name:"Jueves"},{id:5,short:"Vie",name:"Viernes"},{id:6,short:"Sáb",name:"Sábado"},{id:7,short:"Dom",name:"Domingo"}];
const dayName=(value:number)=>days.find(day=>day.id===value)?.short??String(value);

export default function RoutesPage(){
  const permissions=useAuthStore(state=>new Set(state.user?.permissions??[]));
  const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[search,setSearch]=useState("");
  const [sellerId,setSellerId]=useState("all"),[zoneId,setZoneId]=useState("all"),[day,setDay]=useState("all"),[status,setStatus]=useState("active");
  const [selectedRoute,setSelectedRoute]=useState<string>(),[createOpen,setCreateOpen]=useState(false);
  const options=useRouteOptions();
  const query=useRoutes({page,pageSize,search:search.trim()||undefined,sellerId:sellerId==="all"?undefined:sellerId,zoneId:zoneId==="all"?undefined:zoneId,dayOfWeek:day==="all"?undefined:Number(day),isActive:status==="all"?undefined:status==="active"});
  const columns=useMemo<ColumnDef<SalesRouteListItem>[]>(()=>[
    {accessorKey:"name",header:"Ruta",cell:({row})=><div><p className="font-semibold">{row.original.name}</p><p className="text-xs text-muted-foreground">{row.original.code}</p></div>},
    {accessorKey:"sellerName",header:"Vendedor",cell:({row})=><div><p>{row.original.sellerName}</p><p className="text-xs text-muted-foreground">{row.original.zoneName??"Sin zona"}</p></div>},
    {id:"days",header:"Días",cell:({row})=><div className="flex flex-wrap gap-1">{row.original.days.map(value=><Badge key={value} variant="outline">{dayName(value)}</Badge>)}</div>},
    {accessorKey:"stopCount",header:"Establecimientos",cell:({row})=><span className="font-medium tabular-nums">{row.original.stopCount}</span>},
    {accessorKey:"preparationStatus",header:"Preparación",cell:({row})=><Badge variant={row.original.preparationStatus==="Ready"?"secondary":"outline"}>{row.original.preparationStatus==="Ready"?"Lista":"Borrador"}</Badge>},
    {accessorKey:"isActive",header:"Estado",cell:({row})=><Badge variant={row.original.isActive?"default":"outline"}>{row.original.isActive?"Activa":"Inactiva"}</Badge>},
    {id:"actions",header:"",cell:({row})=><Button size="sm" variant="ghost" onClick={(event)=>{event.stopPropagation();setSelectedRoute(row.original.routeId)}}><Pencil className="mr-2 h-4 w-4"/>Abrir</Button>}
  ],[]);
  return <div className="space-y-6">
    <header className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-sm font-medium text-primary">Operación comercial</p><h1 className="text-3xl font-semibold tracking-tight">Rutas comerciales</h1><p className="mt-1 max-w-3xl text-muted-foreground">Organiza recorridos por vendedor y día, asignando el establecimiento exacto de cada cliente.</p></div><Button disabled={!permissions.has("routes.create")} onClick={()=>setCreateOpen(true)}><Plus className="mr-2 h-4 w-4"/>Nueva ruta</Button></header>
    <section className="grid gap-3 md:grid-cols-3"><Summary icon={Route} label="Rutas encontradas" value={String(query.data?.totalCount??0)}/><Summary icon={MapPinned} label="Establecimientos visibles" value={String(query.data?.items.reduce((sum,item)=>sum+item.stopCount,0)??0)}/><Summary icon={CalendarDays} label="Programación" value="Por día y orden"/></section>
    <section className="grid gap-3 rounded-2xl border bg-card p-4 xl:grid-cols-[minmax(14rem,1fr)_14rem_14rem_10rem_10rem]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder="Ruta, código, vendedor o zona"/></label><Filter value={sellerId} onChange={value=>{setSellerId(value);setPage(1)}} placeholder="Vendedor" allLabel="Todos los vendedores" items={(options.data?.sellers??[]).map(item=>({value:item.sellerId,label:item.name}))}/><Filter value={zoneId} onChange={value=>{setZoneId(value);setPage(1)}} placeholder="Zona" allLabel="Todas las zonas" items={(options.data?.zones.filter(item=>item.isActive)??[]).map(item=>({value:item.zoneId,label:item.name}))}/><Filter value={day} onChange={value=>{setDay(value);setPage(1)}} placeholder="Día" allLabel="Todos los días" items={days.map(item=>({value:String(item.id),label:item.name}))}/><Filter value={status} onChange={value=>{setStatus(value);setPage(1)}} placeholder="Estado" allLabel="Todos" items={[{value:"active",label:"Activas"},{value:"inactive",label:"Inactivas"}]}/></section>
    <DataTable columns={columns} data={query.data?.items??[]} isLoading={query.isLoading} page={query.data?.page} pageSize={query.data?.pageSize} pageCount={query.data?.totalPages} totalItems={query.data?.totalCount} enableRowSelection={false} onRowClick={item=>setSelectedRoute(item.routeId)} onPaginationChange={(newPage,newSize)=>{setPage(newPage);setPageSize(newSize)}}/>
    <RouteWorkspace open={createOpen||!!selectedRoute} routeId={selectedRoute} permissions={permissions} onCreated={routeId=>{setCreateOpen(false);setSelectedRoute(routeId)}} onClose={()=>{setCreateOpen(false);setSelectedRoute(undefined)}}/>
  </div>;
}

function RouteWorkspace({open,routeId,permissions,onCreated,onClose}:{open:boolean;routeId?:string;permissions:Set<string>;onCreated:(id:string)=>void;onClose:()=>void}){
  const businessId=useBusinessContextStore(state=>state.selectedBusinessId);
  const options=useRouteOptions(),detail=useRouteDetail(routeId),create=useCreateRoute(),update=useUpdateRoute(),status=useSetRouteStatus();
  const [tab,setTab]=useState("general"),[code,setCode]=useState(""),[name,setName]=useState(""),[seller,setSeller]=useState(""),[zone,setZone]=useState("none"),[notes,setNotes]=useState("");
  const [schedule,setSchedule]=useState<Record<number,{selected:boolean;runOrder:string;time:string}>>(()=>Object.fromEntries(days.map(day=>[day.id,{selected:day.id<=5,runOrder:"1",time:""}])));
  const loaded=useRef<string>();
  useEffect(()=>{if(!open)setTab("general")},[open]);
  useEffect(()=>{
    const value=detail.data;if(!value||loaded.current===value.rowVersion)return;loaded.current=value.rowVersion;
    setCode(value.code);setName(value.name);setSeller(value.sellerId);setZone(value.zoneId??"none");setNotes(value.notes??"");
    setSchedule(Object.fromEntries(days.map(day=>{const found=value.schedules.find(item=>item.dayOfWeek===day.id);return [day.id,{selected:!!found,runOrder:String(found?.runOrder??1),time:found?.plannedStartTime?.slice(0,5)??""}]})));
  },[detail.data]);
  useEffect(()=>{if(!routeId&&options.data?.sellers.length&&!seller)setSeller(options.data.sellers[0].sellerId)},[options.data,routeId,seller]);
  const schedules=():RouteScheduleInput[]=>days.filter(day=>schedule[day.id].selected).map(day=>({dayOfWeek:day.id,runOrder:Number(schedule[day.id].runOrder)||1,plannedStartTime:schedule[day.id].time||null}));
  const save=async()=>{
    if(!businessId||!code.trim()||!name.trim()||!seller)return toast.error("Completa código, nombre y vendedor.");
    if(!schedules().length)return toast.error("Selecciona al menos un día.");
    try{
      if(routeId&&detail.data){await update.mutateAsync({routeId,request:{code,name,sellerId:seller,zoneId:zone==="none"?null:zone,notes:notes||null,schedules:schedules(),rowVersion:detail.data.rowVersion}});toast.success("Ruta actualizada");await detail.refetch()}
      else{const result=await create.mutateAsync({businessId,code,name,sellerId:seller,zoneId:zone==="none"?null:zone,notes:notes||null,schedules:schedules()});toast.success("Ruta creada. Ya puedes construir el recorrido.");onCreated(result.routeId);setTab("stops")}
    }catch(error){toast.error(message(error,"No fue posible guardar la ruta."))}
  };
  const changeStatus=async()=>{
    if(!routeId||!detail.data)return;
    try{
      const refreshed=await detail.refetch();
      const current=refreshed.data??detail.data;
      await status.mutateAsync({routeId,isActive:!current.isActive,rowVersion:current.rowVersion});
      toast.success(current.isActive?"Ruta desactivada":"Ruta activada");
      await detail.refetch();
    }catch(error){toast.error(message(error,"No fue posible cambiar el estado."))}
  };
  const canSave=!routeId?permissions.has("routes.create"):permissions.has("routes.update");
  return <Dialog open={open} onOpenChange={value=>!value&&onClose()}><DialogContent className="flex max-h-[94vh] max-w-6xl flex-col overflow-hidden"><DialogHeader><DialogTitle>{routeId?(detail.data?.name??"Ruta comercial"):"Nueva ruta comercial"}</DialogTitle><DialogDescription>{routeId?"Configura el calendario y construye un recorrido ordenado por establecimientos.":"Define primero la identidad, el vendedor y los días de trabajo."}</DialogDescription></DialogHeader>
    <Tabs value={tab} onValueChange={setTab} className="min-h-0 flex-1 overflow-hidden"><TabsList><TabsTrigger value="general">Configuración</TabsTrigger><TabsTrigger value="stops" disabled={!routeId}>Recorrido {detail.data?`(${detail.data.stops.length})`:""}</TabsTrigger></TabsList>
      <TabsContent value="general" className="max-h-[66vh] space-y-5 overflow-y-auto pr-2"><div className="grid gap-4 md:grid-cols-2"><Field label="Código"><Input value={code} maxLength={32} onChange={event=>setCode(event.target.value.toUpperCase())} placeholder="RUTA-NORTE"/></Field><Field label="Nombre"><Input value={name} maxLength={160} onChange={event=>setName(event.target.value)} placeholder="Ruta norte"/></Field><Field label="Vendedor"><Select value={seller} onValueChange={setSeller}><SelectTrigger><SelectValue placeholder="Selecciona un vendedor"/></SelectTrigger><SelectContent>{options.data?.sellers.map(item=><SelectItem key={item.sellerId} value={item.sellerId}>{item.name} · {item.code}</SelectItem>)}</SelectContent></Select></Field><Field label="Zona comercial"><Select value={zone} onValueChange={setZone}><SelectTrigger><SelectValue placeholder="Sin zona"/></SelectTrigger><SelectContent><SelectItem value="none">Sin zona</SelectItem>{options.data?.zones.filter(item=>item.isActive).map(item=><SelectItem key={item.zoneId} value={item.zoneId}>{item.name}</SelectItem>)}</SelectContent></Select></Field></div>
        <ZoneCreator businessId={businessId} onCreated={setZone} canCreate={permissions.has("route-zones.manage")}/>
        <Field label="Notas operativas"><Textarea value={notes} maxLength={500} onChange={event=>setNotes(event.target.value)} placeholder="Indicaciones útiles para preparar el recorrido"/></Field>
        <section className="rounded-2xl border p-4"><div className="mb-4"><h3 className="font-semibold">Calendario de atención</h3><p className="text-sm text-muted-foreground">Una ruta puede trabajar varios días. El orden permite programar más de una ruta para el vendedor en el mismo día.</p></div><div className="grid gap-3 lg:grid-cols-2">{days.map(day=>{const value=schedule[day.id];return <div key={day.id} className="grid grid-cols-[auto_minmax(7rem,1fr)_6rem_7rem] items-center gap-3 rounded-xl border p-3"><Checkbox checked={value.selected} onCheckedChange={checked=>setSchedule(current=>({...current,[day.id]:{...current[day.id],selected:checked===true}}))}/><Label>{day.name}</Label><Input aria-label={`Orden ${day.name}`} type="number" min={1} value={value.runOrder} disabled={!value.selected} onChange={event=>setSchedule(current=>({...current,[day.id]:{...current[day.id],runOrder:event.target.value}}))}/><Input aria-label={`Hora ${day.name}`} type="time" value={value.time} disabled={!value.selected} onChange={event=>setSchedule(current=>({...current,[day.id]:{...current[day.id],time:event.target.value}}))}/></div>})}</div></section>
      </TabsContent>
      <TabsContent value="stops" className="min-h-0"><RouteStops routeId={routeId} detail={detail} permissions={permissions}/></TabsContent>
    </Tabs>
    <DialogFooter className="border-t pt-4"><Button variant="outline" onClick={onClose}>Cerrar</Button>{routeId&&detail.data&&<Button variant="outline" disabled={!permissions.has(detail.data.isActive?"routes.deactivate":"routes.activate")||status.isPending} onClick={changeStatus}>{detail.data.isActive?"Desactivar":"Activar"}</Button>}<Button disabled={!canSave||create.isPending||update.isPending||tab!=="general"} onClick={save}>{routeId?"Guardar cambios":"Crear ruta"}</Button></DialogFooter>
  </DialogContent></Dialog>;
}

function RouteStops({routeId,detail,permissions}:{routeId?:string;detail:ReturnType<typeof useRouteDetail>;permissions:Set<string>}){
  const [candidateOpen,setCandidateOpen]=useState(false),[removeId,setRemoveId]=useState<string>();const remove=useRemoveRouteStop(),reorder=useReorderRouteStops();const refs=useRef<Array<HTMLButtonElement|null>>([]);
  const data=detail.data;if(!routeId||!data)return <div className="py-16 text-center text-muted-foreground">Guarda la ruta para construir el recorrido.</div>;
  const move=async(index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=data.stops.length)return;const order=data.stops.map(stop=>stop.routeStopId);[order[index],order[target]]=[order[target],order[index]];try{await reorder.mutateAsync({routeId,orderedStopIds:order,rowVersion:data.rowVersion});await detail.refetch();window.setTimeout(()=>refs.current[target]?.focus(),0)}catch(error){toast.error(message(error,"No fue posible reordenar el recorrido."))}};
  const removeConfirmed=async()=>{if(!removeId)return;try{await remove.mutateAsync({routeId,stopId:removeId,rowVersion:data.rowVersion});setRemoveId(undefined);await detail.refetch();toast.success("Establecimiento retirado del recorrido")}catch(error){toast.error(message(error,"No fue posible retirar el establecimiento."))}};
  const print=async()=>{try{await routesApi.export(routeId);window.print()}catch(error){toast.error(message(error,"No tienes acceso para imprimir este recorrido."))}};
  const download=async()=>{try{const exported=await routesApi.export(routeId);const rows=[["Orden","Cliente","Establecimiento","Dirección","Ciudad","Barrio","Teléfono"],...exported.stops.map(stop=>[String(stop.sequence),stop.customerName,stop.siteName,stop.addressLine,stop.cityName,stop.neighborhood??"",stop.phone??""])];const csv=rows.map(row=>row.map(value=>`"${value.replaceAll('"','""')}"`).join(",")).join("\r\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}));link.download=`${exported.code}-recorrido.csv`;link.click();URL.revokeObjectURL(link.href)}catch(error){toast.error(message(error,"No fue posible exportar el recorrido."))}};
  return <div className="flex max-h-[66vh] min-h-[28rem] flex-col gap-4 overflow-hidden pt-2"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">Recorrido ordenado</h3><p className="text-sm text-muted-foreground">Flechas navegan. Alt + flecha mueve la parada sin editar números manualmente.</p></div><div className="flex gap-2"><Button variant="outline" disabled={!permissions.has("routes.export")||!data.stops.length} onClick={print}><Printer className="mr-2 h-4 w-4"/>Imprimir</Button><Button variant="outline" disabled={!permissions.has("routes.export")||!data.stops.length} onClick={download}><Download className="mr-2 h-4 w-4"/>CSV</Button><Button disabled={!permissions.has("routes.stops.manage")} onClick={()=>setCandidateOpen(true)}><Plus className="mr-2 h-4 w-4"/>Agregar establecimientos</Button></div></div>
    <div className="min-h-0 flex-1 overflow-y-auto rounded-2xl border"><div className="sticky top-0 z-10 grid grid-cols-[4rem_minmax(12rem,1.2fr)_minmax(14rem,1.5fr)_7rem] gap-3 border-b bg-muted/95 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground"><span>Orden</span><span>Cliente</span><span>Establecimiento</span><span className="text-right">Acciones</span></div>{!data.stops.length?<div className="grid min-h-72 place-items-center p-8 text-center"><div><MapPinned className="mx-auto h-10 w-10 text-primary"/><p className="mt-3 font-semibold">Construye el primer recorrido</p><p className="mt-1 text-sm text-muted-foreground">Agrega establecimientos; no se asigna solamente el cliente, sino su dirección concreta.</p></div></div>:data.stops.map((stop,index)=><button key={stop.routeStopId} ref={element=>{refs.current[index]=element}} type="button" className="grid w-full grid-cols-[4rem_minmax(12rem,1.2fr)_minmax(14rem,1.5fr)_7rem] items-center gap-3 border-b px-4 py-3 text-left outline-none transition hover:bg-muted/50 focus:bg-primary/5 focus:ring-2 focus:ring-inset focus:ring-primary" onKeyDown={event=>{if(event.key==="ArrowDown"){event.preventDefault();event.altKey?move(index,1):refs.current[Math.min(index+1,data.stops.length-1)]?.focus()}if(event.key==="ArrowUp"){event.preventDefault();event.altKey?move(index,-1):refs.current[Math.max(index-1,0)]?.focus()}if(event.key==="Delete"&&permissions.has("routes.stops.manage")){event.preventDefault();setRemoveId(stop.routeStopId)}}}><span className="text-lg font-semibold tabular-nums">{stop.sequence}</span><span><strong className="block">{stop.customerName}</strong><small className="text-muted-foreground">{stop.identification??"Sin identificación"}</small></span><span><strong className="block">{stop.siteName}</strong><small className="block text-muted-foreground">{stop.addressLine} · {stop.cityName}{stop.neighborhood?` · ${stop.neighborhood}`:""}</small></span><span className="flex justify-end gap-1"><Button asChild size="icon" variant="ghost"><span onClick={event=>{event.stopPropagation();move(index,-1)}}><ArrowUp className="h-4 w-4"/></span></Button><Button asChild size="icon" variant="ghost"><span onClick={event=>{event.stopPropagation();move(index,1)}}><ArrowDown className="h-4 w-4"/></span></Button><Button asChild size="icon" variant="ghost"><span onClick={event=>{event.stopPropagation();setRemoveId(stop.routeStopId)}}><Trash2 className="h-4 w-4"/></span></Button></span></button>)}</div>
    <CandidateDialog open={candidateOpen} routeId={routeId} rowVersion={data.rowVersion} onClose={()=>setCandidateOpen(false)} onSaved={async()=>{setCandidateOpen(false);await detail.refetch()}}/>
    <Dialog open={!!removeId} onOpenChange={(value:boolean)=>!value&&setRemoveId(undefined)}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>¿Retirar este establecimiento?</DialogTitle><DialogDescription>La parada saldrá del recorrido activo y el resto se renumerará automáticamente. El historial se conserva.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setRemoveId(undefined)}>Cancelar</Button><Button variant="destructive" onClick={removeConfirmed}>Retirar</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function CandidateDialog({open,routeId,rowVersion,onClose,onSaved}:{open:boolean;routeId:string;rowVersion:string;onClose:()=>void;onSaved:()=>void}){
  const [search,setSearch]=useState(""),[page,setPage]=useState(1),[selected,setSelected]=useState<Record<string,RouteCandidateSite>>({});const query=useRouteCandidates(open?routeId:undefined,search,page),add=useAddRouteStops();
  const submit=async()=>{const values=Object.values(selected);if(!values.length)return;try{await add.mutateAsync({routeId,rowVersion,stops:values.map(item=>({customerId:item.customerId,partySiteId:item.partySiteId,visitNote:null}))});toast.success(`${values.length} establecimiento${values.length===1?"":"s"} agregado${values.length===1?"":"s"}`);setSelected({});onSaved()}catch(error){toast.error(message(error,"No fue posible agregar los establecimientos."))}};
  return <Dialog open={open} onOpenChange={value=>!value&&onClose()}><DialogContent className="flex max-h-[88vh] max-w-4xl flex-col overflow-hidden"><DialogHeader><DialogTitle>Agregar establecimientos</DialogTitle><DialogDescription>Busca por cliente, documento, dirección o teléfono. Los conflictos de calendario se explican antes de guardar.</DialogDescription></DialogHeader><label className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input autoFocus className="pl-9" value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder="Buscar establecimientos"/></label><div className="min-h-0 flex-1 space-y-2 overflow-y-auto">{query.isLoading?<p className="py-12 text-center text-muted-foreground">Buscando...</p>:query.data?.items.map(item=>{const disabled=item.isAlreadyInRoute||item.hasScheduleConflict;return <label key={item.partySiteId} className={`flex items-start gap-3 rounded-xl border p-3 ${disabled?"bg-muted/40 opacity-70":"cursor-pointer hover:border-primary/50"}`}><Checkbox checked={!!selected[item.partySiteId]} disabled={disabled} onCheckedChange={checked=>setSelected(current=>{const next={...current};if(checked===true)next[item.partySiteId]=item;else delete next[item.partySiteId];return next})}/><span className="min-w-0 flex-1"><strong className="block">{item.customerName} · {item.siteName}</strong><span className="block text-sm text-muted-foreground">{item.addressLine} · {item.cityName}{item.neighborhood?` · ${item.neighborhood}`:""}</span>{item.isAlreadyInRoute&&<span className="text-xs text-primary">Ya pertenece a esta ruta.</span>}{item.conflictDescription&&<span className="block text-xs text-destructive">{item.conflictDescription}</span>}</span></label>})}{!query.isLoading&&!query.data?.items.length&&<p className="py-12 text-center text-muted-foreground">No se encontraron establecimientos.</p>}</div><div className="flex items-center justify-between text-sm text-muted-foreground"><span>{query.data?.totalCount??0} resultados · {Object.keys(selected).length} seleccionados</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Anterior</Button><Button size="sm" variant="outline" disabled={!query.data||page>=query.data.totalPages} onClick={()=>setPage(value=>value+1)}>Siguiente</Button></div></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancelar</Button><Button disabled={!Object.keys(selected).length||add.isPending} onClick={submit}>Agregar al recorrido</Button></DialogFooter></DialogContent></Dialog>;
}

function ZoneCreator({businessId,onCreated,canCreate}:{businessId:string|null;onCreated:(zoneId:string)=>void;canCreate:boolean}){
  const [open,setOpen]=useState(false),[code,setCode]=useState(""),[name,setName]=useState("");const create=useCreateRouteZone();
  const submit=async()=>{if(!businessId||!code.trim()||!name.trim())return toast.error("Completa código y nombre de la zona.");try{const result=await create.mutateAsync({businessId,code,name});onCreated(result.zoneId);setOpen(false);setCode("");setName("");toast.success("Zona comercial creada")}catch(error){toast.error(message(error,"No fue posible crear la zona."))}};
  return <div className="flex justify-end"><Button type="button" size="sm" variant="ghost" disabled={!canCreate} onClick={()=>setOpen(true)}><Plus className="mr-2 h-4 w-4"/>Crear zona comercial</Button>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Nueva zona comercial</DialogTitle><DialogDescription>Agrupa recorridos con una clasificación propia del negocio.</DialogDescription></DialogHeader>
      <Field label="Código"><Input value={code} maxLength={32} onChange={event=>setCode(event.target.value.toUpperCase())} placeholder="NORTE"/></Field>
      <Field label="Nombre"><Input value={name} maxLength={160} onChange={event=>setName(event.target.value)} placeholder="Zona norte"/></Field>
      <DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={create.isPending} onClick={submit}>Crear zona</Button></DialogFooter>
    </DialogContent></Dialog>
  </div>;
}

function Filter({value,onChange,placeholder,allLabel,items}:{value:string;onChange:(value:string)=>void;placeholder:string;allLabel:string;items:Array<{value:string;label:string}>}){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent><SelectItem value="all">{allLabel}</SelectItem>{items.map(item=><SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function Summary({icon:Icon,label,value}:{icon:typeof Route;label:string;value:string}){return <Card><CardContent className="flex items-center gap-3 p-4"><span className="rounded-xl bg-primary/10 p-2 text-primary"><Icon className="h-5 w-5"/></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{value}</p></div></CardContent></Card>}
function message(error:unknown,fallback:string){if(error&&typeof error==="object"&&"message" in error&&typeof error.message==="string")return error.message;return fallback}
