SET NOCOUNT ON;

MERGE reporting.PayrollReportDefinitions AS target
USING (VALUES
 (N'payroll-summary',N'Resumen de nómina',N'Devengado, deducciones, neto, pago y estado electrónico por trabajador.',N'PayrollSummary',
 N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"identification","label":"Identificación","format":"text","align":"left"},{"key":"periodStart","label":"Desde","format":"date","align":"left"},{"key":"periodEnd","label":"Hasta","format":"date","align":"left"},{"key":"workedDays","label":"Días","format":"number","align":"right"},{"key":"earnings","label":"Devengado","format":"currency","align":"right"},{"key":"deductions","label":"Deducciones","format":"currency","align":"right"},{"key":"netPayable","label":"Neto","format":"currency","align":"right"},{"key":"paymentStatus","label":"Pago","format":"text","align":"left"},{"key":"electronicStatus","label":"DIAN","format":"text","align":"left"}]',10),
 (N'payroll-receipt',N'Comprobante individual de nómina',N'Desprendible imprimible por trabajador con conceptos y totales definitivos.',N'PayrollReceipt',
  N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"identification","label":"Identificación","format":"text","align":"left"},{"key":"contractNumber","label":"Contrato","format":"text","align":"left"},{"key":"periodStart","label":"Desde","format":"date","align":"left"},{"key":"periodEnd","label":"Hasta","format":"date","align":"left"},{"key":"paymentDate","label":"Pago","format":"date","align":"left"},{"key":"workedDays","label":"Días","format":"number","align":"right"},{"key":"conceptCode","label":"Código","format":"text","align":"left"},{"key":"conceptName","label":"Concepto","format":"text","align":"left"},{"key":"nature","label":"Naturaleza","format":"text","align":"left"},{"key":"quantity","label":"Cantidad","format":"number","align":"right"},{"key":"amount","label":"Valor","format":"currency","align":"right"},{"key":"earnings","label":"Devengado total","format":"currency","align":"right"},{"key":"deductions","label":"Deducciones total","format":"currency","align":"right"},{"key":"netPayable","label":"Neto","format":"currency","align":"right"}]',15),
 (N'concept-detail',N'Detalle por concepto',N'Todas las líneas definitivas de devengos, deducciones, aportes y provisiones.',N'ConceptDetail',
  N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"periodStart","label":"Desde","format":"date","align":"left"},{"key":"periodEnd","label":"Hasta","format":"date","align":"left"},{"key":"conceptCode","label":"Código","format":"text","align":"left"},{"key":"conceptName","label":"Concepto","format":"text","align":"left"},{"key":"nature","label":"Naturaleza","format":"text","align":"left"},{"key":"quantity","label":"Cantidad","format":"number","align":"right"},{"key":"baseAmount","label":"Base","format":"currency","align":"right"},{"key":"rate","label":"Tarifa","format":"number","align":"right"},{"key":"amount","label":"Valor","format":"currency","align":"right"}]',20),
 (N'deductions',N'Deducciones por trabajador y concepto',N'Deducciones definitivas, incluidas las respaldadas por acuerdos y autoridad.',N'Deductions',
  N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"periodStart","label":"Desde","format":"date","align":"left"},{"key":"periodEnd","label":"Hasta","format":"date","align":"left"},{"key":"conceptCode","label":"Código","format":"text","align":"left"},{"key":"conceptName","label":"Deducción","format":"text","align":"left"},{"key":"baseAmount","label":"Base","format":"currency","align":"right"},{"key":"amount","label":"Valor","format":"currency","align":"right"}]',30),
 (N'employer-contributions',N'Aportes patronales y parafiscales',N'Cargas del empleador por trabajador y concepto.',N'EmployerContributions',
  N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"periodStart","label":"Desde","format":"date","align":"left"},{"key":"periodEnd","label":"Hasta","format":"date","align":"left"},{"key":"conceptCode","label":"Código","format":"text","align":"left"},{"key":"conceptName","label":"Aporte","format":"text","align":"left"},{"key":"baseAmount","label":"Base","format":"currency","align":"right"},{"key":"rate","label":"Tarifa","format":"number","align":"right"},{"key":"amount","label":"Valor","format":"currency","align":"right"}]',40),
 (N'provisions',N'Provisiones y prestaciones',N'Provisiones definitivas de prestaciones por trabajador.',N'Provisions',
  N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"periodStart","label":"Desde","format":"date","align":"left"},{"key":"periodEnd","label":"Hasta","format":"date","align":"left"},{"key":"conceptCode","label":"Código","format":"text","align":"left"},{"key":"conceptName","label":"Provisión","format":"text","align":"left"},{"key":"baseAmount","label":"Base","format":"currency","align":"right"},{"key":"amount","label":"Valor","format":"currency","align":"right"}]',50),
 (N'labor-cost',N'Costo laboral total',N'Devengado más aportes patronales y provisiones.',N'LaborCost',
  N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"periodStart","label":"Desde","format":"date","align":"left"},{"key":"periodEnd","label":"Hasta","format":"date","align":"left"},{"key":"earnings","label":"Devengado","format":"currency","align":"right"},{"key":"employerContributions","label":"Aportes","format":"currency","align":"right"},{"key":"provisions","label":"Provisiones","format":"currency","align":"right"},{"key":"totalLaborCost","label":"Costo total","format":"currency","align":"right"}]',60),
 (N'payments',N'Pagos de nómina',N'Lotes confirmados, medio de pago y referencia por trabajador.',N'Payments',
  N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"identification","label":"Identificación","format":"text","align":"left"},{"key":"paymentDate","label":"Fecha","format":"date","align":"left"},{"key":"paymentMethod","label":"Medio","format":"text","align":"left"},{"key":"paymentReference","label":"Referencia","format":"text","align":"left"},{"key":"amount","label":"Valor","format":"currency","align":"right"},{"key":"status","label":"Estado","format":"text","align":"left"}]',70),
 (N'electronic-status',N'Estado de nómina electrónica',N'Documento por trabajador, estado fiscal y TrackId devuelto por DIAN.',N'ElectronicStatus',
  N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"identification","label":"Identificación","format":"text","align":"left"},{"key":"period","label":"Período","format":"text","align":"left"},{"key":"documentKind","label":"Documento","format":"text","align":"left"},{"key":"payrollStatus","label":"Nómina","format":"text","align":"left"},{"key":"fiscalStatus","label":"Fiscal","format":"text","align":"left"},{"key":"trackId","label":"TrackId DIAN","format":"text","align":"left"},{"key":"createdAt","label":"Generado","format":"datetime","align":"left"}]',80),
 (N'income-withholding',N'Ingresos y retenciones',N'Base anual verificable para el Certificado de Ingresos y Retenciones (Formulario 220).',N'IncomeAndWithholding',
  N'[{"key":"employeeName","label":"Trabajador","format":"text","align":"left"},{"key":"identification","label":"Identificación","format":"text","align":"left"},{"key":"periodStart","label":"Desde","format":"date","align":"left"},{"key":"periodEnd","label":"Hasta","format":"date","align":"left"},{"key":"employmentIncome","label":"Ingresos laborales","format":"currency","align":"right"},{"key":"withholding","label":"Retención","format":"currency","align":"right"},{"key":"totalDeductions","label":"Deducciones","format":"currency","align":"right"}]',90)
) AS source(Code,Name,Description,DatasetCode,ColumnsJson,SortOrder)
ON target.Code=source.Code
WHEN MATCHED THEN UPDATE SET Name=source.Name,Description=source.Description,
  DatasetCode=source.DatasetCode,ColumnsJson=source.ColumnsJson,SortOrder=source.SortOrder,IsActive=1
WHEN NOT MATCHED THEN INSERT(Code,Name,Description,DatasetCode,ColumnsJson,SortOrder,IsActive)
  VALUES(source.Code,source.Name,source.Description,source.DatasetCode,source.ColumnsJson,source.SortOrder,1);
