"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertCircle, ArrowRightLeft, Banknote, Check, CheckCircle2, ChevronDown, ChevronUp, Clock3, CreditCard, Landmark, Loader2, ReceiptText, Scale, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { DatePicker } from "@/components/ui/date-picker";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useReferenceOptions } from "@/hooks/use-reference-options";
import { workSessionDifferencesApi, type ClosurePaymentVerification, type ReconcileClosureRequest, type WorkSessionClosure } from "@/services/api/work-session-differences";
import { workSessionPaymentMethodName } from "@/services/pos/pos-work-session-close";

const money = new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 });
const isoDate = (value: Date) => value.toISOString().slice(0, 10);
const result = (difference: number | null) => difference == null ? "Sin conteo" : difference > 0 ? `Sobrante ${money.format(difference)}` : difference < 0 ? `Faltante ${money.format(Math.abs(difference))}` : "Cuadra";
const accountingStatusLabels: Record<string, string> = { AccountingDisabled: "No requiere asiento", AccountingPendingConfiguration: "Falta configuración contable", NotRequired: "No requiere asiento", Pending: "Pendiente de contabilizar", Processing: "Contabilizando", Posted: "Contabilizado", Failed: "Error contable" };
const accountingStatusName = (value: string) => accountingStatusLabels[value] ?? "Pendiente de contabilizar";

export default function CashClosuresPage() {
  const today = useMemo(() => new Date(), []);
  const monthStart = useMemo(() => new Date(today.getFullYear(), today.getMonth(), 1), [today]);
  const [from, setFrom] = useState(isoDate(monthStart));
  const [to, setTo] = useState(isoDate(today));
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<WorkSessionClosure | null>(null);
  const closures = useQuery({ queryKey: ["work-session-closures", from, to, page], queryFn: () => workSessionDifferencesApi.listClosures(from, to, undefined, page, 50), enabled: Boolean(from && to && from <= to) });
  const rows = closures.data?.items ?? [];
  const pending = rows.filter(row => row.reconciliationStatus === "Pending").length;

  return <div className="space-y-5">
    <header className="rounded-3xl bg-gradient-to-r from-slate-950 via-teal-950 to-cyan-700 p-6 text-white shadow-lg"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-200">Control y conciliación</p><h1 className="mt-2 text-3xl font-black">Cierres de sesión</h1><p className="mt-2 max-w-3xl text-sm text-teal-50/80">Revisa el efectivo y confirma cada comprobante de tarjeta o transferencia antes de conciliar.</p></header>
    <div className="grid gap-4 sm:grid-cols-3"><Summary title="Cierres en esta página" value={String(rows.length)} icon={<Scale className="h-5 w-5" />} /><Summary title="Pendientes" value={String(pending)} icon={<Clock3 className="h-5 w-5 text-amber-600" />} /><Summary title="Conciliados" value={String(rows.length - pending)} icon={<CheckCircle2 className="h-5 w-5 text-emerald-600" />} /></div>
    <Card className="overflow-hidden rounded-3xl"><CardHeader className="gap-4 border-b sm:flex-row sm:items-end sm:justify-between"><div><CardTitle>Historial de cierres</CardTitle><p className="mt-1 text-sm text-muted-foreground">Cada cierre conserva el cuadre y su resultado contable.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Desde</Label><DatePicker value={from} onChange={value => { setFrom(value); setPage(1); }} className="sm:w-52" /></div><div className="space-y-1.5"><Label>Hasta</Label><DatePicker value={to} onChange={value => { setTo(value); setPage(1); }} className="sm:w-52" /></div></div></CardHeader><CardContent className="p-0">
      {closures.isLoading && <div className="flex items-center justify-center gap-2 p-10 text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin" />Consultando cierres…</div>}{closures.isError && <p className="p-8 text-center text-sm text-destructive">No fue posible consultar los cierres.</p>}{!closures.isLoading && !rows.length && <p className="p-10 text-center text-sm text-muted-foreground">No hay cierres en el periodo.</p>}
      {!!rows.length && <div className="overflow-x-auto"><table className="w-full min-w-[1040px] text-sm"><thead className="bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-4 text-left">Periodo</th><th className="px-4 py-4 text-left">Responsable / sede</th><th className="px-4 py-4 text-right">Ventas</th><th className="px-4 py-4 text-right">Devoluciones</th><th className="px-4 py-4 text-left">Resultado</th><th className="px-4 py-4 text-left">Estado</th><th className="px-5 py-4 text-center">Acción</th></tr></thead><tbody>{rows.map(row => <tr key={row.workSessionClosureId} className="border-t align-middle hover:bg-muted/20"><td className="whitespace-nowrap px-5 py-4 font-medium">{new Date(row.openedAt).toLocaleString("es-CO")}<small className="mt-1 block font-normal text-muted-foreground">hasta {new Date(row.closedAt).toLocaleString("es-CO")}</small></td><td className="px-4 py-4"><strong>{row.userName}</strong><small className="mt-1 block text-muted-foreground">{row.businessName} · {row.warehouseName}</small></td><td className="px-4 py-4 text-right font-semibold">{money.format(row.totalSales)}<small className="mt-1 block font-normal text-muted-foreground">{row.salesCount} ventas · {row.creditSalesCount} a crédito</small></td><td className="px-4 py-4 text-right font-semibold">{money.format(row.totalRefunds)}<small className="mt-1 block font-normal text-muted-foreground">{row.returnCount} devoluciones</small></td><td className="px-4 py-4">{row.paymentTotals.filter(item => item.requiresCount).map(item => <small key={item.paymentMethodCode} className={`block font-semibold ${item.difference && item.difference < 0 ? "text-red-700" : item.difference && item.difference > 0 ? "text-emerald-700" : "text-slate-600"}`}>{workSessionPaymentMethodName(item.paymentMethodCode)}: {result(item.difference)}</small>)}</td><td className="px-4 py-4"><Status value={row.reconciliationStatus} /><small className="mt-2 block text-muted-foreground">{accountingStatusName(row.accountingStatus)}</small></td><td className="px-5 py-4 text-center"><Button size="sm" variant={row.reconciliationStatus === "Pending" ? "default" : "outline"} onClick={() => setSelected(row)}>{row.reconciliationStatus === "Pending" ? "Conciliar" : "Ver cierre"}</Button></td></tr>)}</tbody></table></div>}
      {!!closures.data && <div className="flex items-center justify-between border-t p-4"><small className="text-muted-foreground">{closures.data.totalItems} cierres</small><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page === 1} onClick={() => setPage(value => value - 1)}>Anterior</Button><Button variant="outline" size="sm" disabled={page * 50 >= closures.data.totalItems} onClick={() => setPage(value => value + 1)}>Siguiente</Button></div></div>}
    </CardContent></Card>{selected && <ReconciliationDialog closure={selected} onClose={() => setSelected(null)} />}
  </div>;
}

type VerificationStatus = "Verified" | "Missing";

function ReconciliationDialog({ closure, onClose }: { closure: WorkSessionClosure; onClose: () => void }) {
  const queryClient = useQueryClient();
  const countable = closure.paymentTotals.filter(item => item.requiresCount);
  const editable = closure.reconciliationStatus === "Pending";
  const verificationQuery = useQuery({ queryKey: ["work-session-payment-verifications", closure.workSessionClosureId], queryFn: () => workSessionDifferencesApi.listPaymentVerifications(closure.workSessionClosureId) });
  const verificationItems = useMemo(() => verificationQuery.data ?? [], [verificationQuery.data]);
  const byMethod = useMemo(() => verificationItems.reduce<Record<string, ClosurePaymentVerification[]>>((groups, item) => { (groups[item.paymentMethodCode] ??= []).push(item); return groups; }, {}), [verificationItems]);
  const [verified, setVerified] = useState<Record<string, string>>(() => Object.fromEntries(countable.map(item => [item.paymentMethodCode, String(item.countedAmount ?? item.netAmount)])));
  const [confirmed, setConfirmed] = useState<Record<string, boolean>>(() => Object.fromEntries(countable.map(item => [item.paymentMethodCode, false])));
  const [verificationStatus, setVerificationStatus] = useState<Record<string, VerificationStatus>>({});
  const [expandedMethods, setExpandedMethods] = useState<Record<string, boolean>>({});
  const [reclassifications, setReclassifications] = useState<ReconcileClosureRequest["reclassifications"]>([]);
  const [note, setNote] = useState("");
  const reasons = useReferenceOptions("cash-reconciliation-reason", editable);
  const [reasonCode, setReasonCode] = useState("COUNT_DIFFERENCE");
  useEffect(() => setReclassifications([]), [verificationStatus]);
  const methodItems = (code: string) => byMethod[code] ?? [];
  const methodVerifiedAmount = (code: string) => { const items = methodItems(code); return items.length ? items.filter(item => verificationStatus[item.verificationKey] === "Verified").reduce((sum, item) => sum + item.amount, 0) : Number(verified[code] ?? 0); };
  const methodIsConfirmed = (code: string) => { const items = methodItems(code); return items.length ? items.every(item => verificationStatus[item.verificationKey] !== undefined) : confirmed[code]; };
  const differences = Object.fromEntries(countable.map(item => [item.paymentMethodCode, methodVerifiedAmount(item.paymentMethodCode) - item.netAmount]));
  const adjustedDifferences = { ...differences }; for (const item of reclassifications) { adjustedDifferences[item.fromPaymentMethodCode] = (adjustedDifferences[item.fromPaymentMethodCode] ?? 0) + item.amount; adjustedDifferences[item.toPaymentMethodCode] = (adjustedDifferences[item.toPaymentMethodCode] ?? 0) - item.amount; }
  const mutation = useMutation({ mutationFn: () => workSessionDifferencesApi.reconcile(closure.workSessionClosureId, { lines: countable.map(item => ({ paymentMethodCode: item.paymentMethodCode, verifiedAmount: methodVerifiedAmount(item.paymentMethodCode), isConfirmed: methodIsConfirmed(item.paymentMethodCode), reasonCode: adjustedDifferences[item.paymentMethodCode] === 0 ? null : reasonCode })), paymentVerifications: verificationItems.map(item => ({ verificationKey: item.verificationKey, status: verificationStatus[item.verificationKey]! })), reclassifications, note: note.trim() || null }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["work-session-closures"] }); onClose(); } });
  const shortage = countable.find(item => differences[item.paymentMethodCode] < 0); const surplus = countable.find(item => differences[item.paymentMethodCode] > 0);
  const suggestReclassification = () => { if (shortage && surplus) setReclassifications([{ fromPaymentMethodCode: shortage.paymentMethodCode, toPaymentMethodCode: surplus.paymentMethodCode, amount: Math.min(Math.abs(differences[shortage.paymentMethodCode]), differences[surplus.paymentMethodCode]) }]); };
  const valid = !verificationQuery.isLoading && !verificationQuery.isError && countable.every(item => { const amount = methodVerifiedAmount(item.paymentMethodCode); return Number.isFinite(amount) && amount >= 0 && methodIsConfirmed(item.paymentMethodCode); });

  return <Dialog open onOpenChange={open => !open && onClose()}><DialogContent className="max-h-[94vh] max-w-4xl overflow-y-auto p-0"><DialogHeader className="border-b bg-gradient-to-r from-slate-950 to-teal-900 p-6 text-left text-white"><DialogTitle className="text-xl text-white">{editable ? "Conciliar cierre" : "Detalle del cierre"}</DialogTitle><DialogDescription className="text-slate-200">{closure.userName} · {closure.businessName} · {new Date(closure.closedAt).toLocaleString("es-CO")}</DialogDescription></DialogHeader><div className="space-y-5 px-6 pb-2">
    {verificationQuery.isLoading && <div className="flex items-center justify-center gap-2 rounded-2xl bg-muted p-5 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />Cargando comprobantes…</div>}{verificationQuery.isError && <div className="flex items-center gap-2 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle className="h-5 w-5" />No fue posible cargar los comprobantes. No se habilitará la conciliación.</div>}
    {countable.map(item => { const items = methodItems(item.paymentMethodCode); const difference = differences[item.paymentMethodCode]; return <section key={item.paymentMethodCode} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-teal-100 p-2 text-teal-800"><PaymentIcon code={item.paymentMethodCode} /></div><div><strong className="text-base">{workSessionPaymentMethodName(item.paymentMethodCode)}</strong><p className="text-sm text-muted-foreground">Esperado {money.format(item.netAmount)} · reportado al cerrar {money.format(item.countedAmount ?? 0)}</p></div></div><div className={`text-left sm:text-right ${difference < 0 ? "text-red-700" : difference > 0 ? "text-emerald-700" : "text-slate-700"}`}><span className="block text-xs font-semibold uppercase tracking-wide">Resultado</span><strong>{result(difference)}</strong></div></div>
      {items.length ? <div className="p-4"><button type="button" className="flex w-full items-center justify-between gap-3 rounded-xl border bg-white p-3 text-left transition hover:bg-slate-50" onClick={() => setExpandedMethods(current => ({ ...current, [item.paymentMethodCode]: !current[item.paymentMethodCode] }))}><span><strong>{items.length} comprobante{items.length === 1 ? "" : "s"}</strong><small className="mt-1 block text-muted-foreground">{items.filter(value => verificationStatus[value.verificationKey]).length} revisados · {money.format(methodVerifiedAmount(item.paymentMethodCode))} confirmados</small></span><span className="inline-flex items-center gap-2 text-sm font-semibold text-teal-800">{expandedMethods[item.paymentMethodCode] ? "Ocultar detalle" : "Ver y conciliar detalle"}{expandedMethods[item.paymentMethodCode] ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</span></button>{expandedMethods[item.paymentMethodCode] && <div className="mt-3"><p className="mb-3 text-sm text-muted-foreground">Confirma cada comprobante. Si no está físicamente, márcalo como no encontrado.</p><div className="space-y-2">{items.map(value => <VerificationRow key={value.verificationKey} item={value} status={verificationStatus[value.verificationKey]} disabled={!editable} onChange={status => setVerificationStatus(current => ({ ...current, [value.verificationKey]: status }))} />)}</div><div className="mt-3 flex justify-end text-sm"><span className="rounded-xl bg-teal-50 px-3 py-2 text-teal-900">Total confirmado: <strong>{money.format(methodVerifiedAmount(item.paymentMethodCode))}</strong></span></div></div>}</div> : <div className="grid gap-4 p-4 sm:grid-cols-[1fr_190px_auto] sm:items-end"><p className="text-sm text-muted-foreground">{item.paymentMethodCode === "Cash" ? "Cuenta el efectivo físico e ingresa el total encontrado." : "No hay comprobantes individuales asociados; verifica el total."}</p><div className="space-y-1.5"><Label>Total verificado</Label><Input inputMode="numeric" disabled={!editable} value={verified[item.paymentMethodCode]} onChange={event => setVerified(current => ({ ...current, [item.paymentMethodCode]: event.target.value.replace(/\D/g, "") }))} /></div><label className="flex h-10 items-center gap-2 rounded-xl border px-3"><Checkbox disabled={!editable} checked={confirmed[item.paymentMethodCode]} onCheckedChange={value => setConfirmed(current => ({ ...current, [item.paymentMethodCode]: value === true }))} />Revisado</label></div>}
    </section>; })}
    {editable && shortage && surplus && <div className="rounded-2xl border border-indigo-200 bg-indigo-50 p-5 text-indigo-950"><div className="flex flex-col items-center gap-3 text-center"><ArrowRightLeft className="h-6 w-6" /><div><strong>Hay un faltante y un sobrante que se pueden cruzar</strong><p className="mt-1 text-sm text-indigo-800">Faltan {money.format(Math.abs(differences[shortage.paymentMethodCode]))} en {workSessionPaymentMethodName(shortage.paymentMethodCode)} y sobran {money.format(differences[surplus.paymentMethodCode])} en {workSessionPaymentMethodName(surplus.paymentMethodCode)}.</p></div>{!reclassifications.length && <Button type="button" variant="outline" onClick={suggestReclassification}>Cruzar diferencias</Button>}</div>{reclassifications.map((item, index) => <div key={index} className="mx-auto mt-4 flex max-w-xl items-center justify-between gap-3 rounded-xl bg-white p-3 text-sm font-semibold shadow-sm"><span>{workSessionPaymentMethodName(item.fromPaymentMethodCode)} → {workSessionPaymentMethodName(item.toPaymentMethodCode)} · {money.format(item.amount)}</span><button type="button" className="inline-flex items-center gap-1 text-red-700" onClick={() => setReclassifications([])}><X className="h-4 w-4" />Quitar</button></div>)}</div>}
    {editable && Object.values(adjustedDifferences).some(value => value !== 0) && <div className="space-y-2"><Label>Motivo de la diferencia</Label><Select value={reasonCode} onValueChange={setReasonCode}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{(reasons.data ?? []).map(item => <SelectItem key={item.code} value={item.code}>{item.label}</SelectItem>)}</SelectContent></Select></div>}
    <div className="space-y-2"><Label>Observación</Label><Textarea disabled={!editable} value={note} onChange={event => setNote(event.target.value)} maxLength={500} placeholder="Agrega una nota si hace falta explicar el cierre." /></div>{mutation.isError && <p className="rounded-xl bg-red-50 p-3 text-sm text-destructive">No fue posible conciliar. Revisa los comprobantes, diferencias y motivos.</p>}
  </div><footer className="flex items-center justify-center gap-3 border-t bg-slate-50 p-5"><Button variant="outline" onClick={onClose}>Cerrar</Button>{editable && <Button disabled={!valid || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Conciliando…</> : <><CheckCircle2 className="mr-2 h-4 w-4" />Confirmar conciliación</>}</Button>}</footer></DialogContent></Dialog>;
}

function VerificationRow({ item, status, disabled, onChange }: { item: ClosurePaymentVerification; status?: VerificationStatus; disabled: boolean; onChange: (status: VerificationStatus) => void }) { const reference = item.approvalNumber || item.reference || "Sin referencia"; return <div className="grid gap-3 rounded-xl border p-3 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><ReceiptText className="h-4 w-4 text-slate-500" /><strong>{item.movementType === "Refund" ? "Devolución" : item.movementType === "Movement" ? "Movimiento" : "Venta"} {item.documentNumber}</strong>{item.cardFranchiseCode && <Badge variant="secondary">{item.cardFranchiseCode}</Badge>}</div><p className="mt-1 truncate text-xs text-muted-foreground">Referencia: {reference} · {new Date(item.occurredAt).toLocaleString("es-CO")}</p></div><strong className={item.amount < 0 ? "text-red-700" : "text-slate-950"}>{money.format(item.amount)}</strong><div className="flex gap-2"><Button type="button" size="sm" variant={status === "Verified" ? "default" : "outline"} disabled={disabled} onClick={() => onChange("Verified")}><Check className="mr-1 h-4 w-4" />Verificado</Button><Button type="button" size="sm" variant={status === "Missing" ? "destructive" : "outline"} disabled={disabled} onClick={() => onChange("Missing")}><X className="mr-1 h-4 w-4" />No encontrado</Button></div></div>; }
function PaymentIcon({ code }: { code: string }) { if (code === "Cash") return <Banknote className="h-5 w-5" />; if (code === "Transfer") return <Landmark className="h-5 w-5" />; return <CreditCard className="h-5 w-5" />; }
function Summary({ title, value, icon }: { title: string; value: string; icon: ReactNode }) { return <Card className="rounded-3xl"><CardContent className="flex items-center gap-3 p-5"><div className="rounded-2xl bg-muted p-3">{icon}</div><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{title}</p><strong className="text-xl">{value}</strong></div></CardContent></Card>; }
function Status({ value }: { value: WorkSessionClosure["reconciliationStatus"] }) { return <Badge variant={value === "Pending" ? "destructive" : "secondary"}>{value === "Pending" ? "Pendiente" : value === "Reconciled" ? "Conciliado" : value === "ReconciledWithDifferences" ? "Conciliado con diferencias" : "Parcial"}</Badge>; }
