<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auraly.Contracts.Routes\Auraly.Contracts.Routes.csproj" />
    <ProjectReference Include="..\Auraly.Domain.Routes\Auraly.Domain.Routes.csproj" />
    <ProjectReference Include="..\Auraly.Application.Routes\Auraly.Application.Routes.csproj" />
    <ProjectReference Include="..\..\Sales\Auraly.Application.Sales\Auraly.Application.Sales.csproj" />
    <ProjectReference Include="..\..\Sales\Auraly.Contracts.Sales\Auraly.Contracts.Sales.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Auraly.BuildingBlocks.Domain\Auraly.BuildingBlocks.Domain.csproj" />
  </ItemGroup>
</Project>
