<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Auraly.Contracts.Orders\Auraly.Contracts.Orders.csproj" />
    <ProjectReference Include="..\Auraly.Domain.Orders\Auraly.Domain.Orders.csproj" />
    <ProjectReference Include="..\..\Sales\Auraly.Application.Sales\Auraly.Application.Sales.csproj" />
    <ProjectReference Include="..\..\Sales\Auraly.Contracts.Sales\Auraly.Contracts.Sales.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
