<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auraly.Contracts.Purchasing\Auraly.Contracts.Purchasing.csproj" />
    <ProjectReference Include="..\..\DocumentProcessing\Auraly.Application.DocumentProcessing\Auraly.Application.DocumentProcessing.csproj" />
    <ProjectReference Include="..\Auraly.Domain.Purchasing\Auraly.Domain.Purchasing.csproj" />
  </ItemGroup>
</Project>
