"use client";

import {useEffect,useRef,useState} from "react";
import {Check,ChevronRight,CloudOff,Map,MapPin,Minus,Navigation,PackagePlus,Plus,Route,Search,ShoppingCart,SkipForward,Truck} from "lucide-react";
import {toast} from "sonner";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {RouteLocationMap} from "@/components/maps/route-location-map";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {dailyRouteSnapshotKey,loadDailyRouteSnapshots,queueRouteVisit,saveDailyRouteSnapshot} from "@/lib/daily-route-store";
import {firstPendingRouteStop,isoScheduleDay,pendingRouteStops} from "@/lib/daily-route-planning";
import {loadSellerCatalog,loadSellerDraft,queueSellerOrder,removeSellerDraft,saveSellerCatalog,saveSellerDraft} from "@/lib/seller-order-offline-store";
import {routesApi,type SalesRouteDetail,type SalesRouteStop,type SalesRouteVisit} from "@/services/api/routes";
import {sellerOrdersApi,type SellerCatalogItem,type SellerOrderRequest} from "@/services/api/seller-orders";
import {loadSalesWorkspaceOptions,rememberSalesWorkspace,type SalesWorkspaceOption} from "@/services/pos/online-pos-client";

const money=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const dateKey=()=>new Date().toISOString().slice(0,10);

export function DailyRouteApp({businessId,onAdministrative}:{businessId:string;onAdministrative:()=>void}){
  const [workspaces,setWorkspaces]=useState<SalesWorkspaceOption[]>([]),[warehouseId,setWarehouseId]=useState("");
  const [runs,setRuns]=useState<Array<{route:SalesRouteDetail;visits:SalesRouteVisit[]}>>([]),[activeRouteId,setActiveRouteId]=useState("");
  const [tab,setTab]=useState<"route"|"map">("route"),[loading,setLoading]=useState(true),[active,setActive]=useState<SalesRouteStop|null>(null),[skip,setSkip]=useState<SalesRouteStop|null>(null);
  const activeRun=runs.find((run)=>run.route.routeId===activeRouteId)??runs[0],route=activeRun?.route??null,visits=activeRun?.visits??[];
  useEffect(()=>{void loadSalesWorkspaceOptions().then(values=>{const scoped=values.filter(item=>item.businessId===businessId);setWorkspaces(scoped);setWarehouseId(current=>current||scoped[0]?.warehouseId||"")}).catch(error=>toast.error(message(error,"No fue posible consultar las bodegas.")))},[businessId]);
  useEffect(()=>{if(!warehouseId)return;let mounted=true;const load=async()=>{setLoading(true);try{
    const day=todayScheduleDay();
    const page=await routesApi.page({page:1,pageSize:100,dayOfWeek:day,isActive:true,preparationStatus:"Ready"});
    if(!page.items.length)throw new Error("No tienes rutas listas para hoy.");
    const loaded=await Promise.all(page.items.map(async(item)=>{const [detail,todayVisits]=await Promise.all([routesApi.detail(item.routeId),routesApi.visits(item.routeId,dateKey())]);return {route:detail,visits:todayVisits}}));
    loaded.sort((left,right)=>routeRunOrder(left.route,day)-routeRunOrder(right.route,day)||left.route.name.localeCompare(right.route.name,"es"));
    if(!mounted)return;setRuns(loaded);setActiveRouteId(current=>loaded.some(run=>run.route.routeId===current)?current:(loaded.find(hasPendingStops)??loaded[0]).route.routeId);
    await Promise.all(loaded.map(run=>saveDailyRouteSnapshot({key:dailyRouteSnapshotKey(businessId,warehouseId,dateKey(),run.route.routeId),businessId,warehouseId,date:dateKey(),route:run.route,visits:run.visits,synchronizedAt:new Date().toISOString()})));
    void prefetchRouteCatalogs(businessId,warehouseId,loaded.flatMap(run=>run.route.stops)).catch(()=>undefined);rememberSalesWorkspace({businessId,warehouseId});
  }catch(error){const cached=await loadDailyRouteSnapshots(businessId,warehouseId,dateKey());if(cached.length&&mounted){const loaded=cached.map(value=>({route:value.route,visits:value.visits}));setRuns(loaded);setActiveRouteId((loaded.find(hasPendingStops)??loaded[0]).route.routeId);toast.info("Rutas cargadas sin conexión")}else if(mounted)toast.error(message(error,"No fue posible cargar las rutas de hoy."))}finally{if(mounted)setLoading(false)}};void load();return()=>{mounted=false}},[businessId,warehouseId]);
  const next=firstPendingRouteStop(route?.stops??[],visits);
  const totalStops=runs.reduce((sum,run)=>sum+run.route.stops.length,0),totalDone=runs.reduce((sum,run)=>sum+new Set(run.visits.map(visit=>visit.routeStopId)).size,0);
  const record=async(stop:SalesRouteStop,status:"Visited"|"Skipped",orderId:string|null,reason:string|null,observation:string|null=null)=>{if(!route)return;const request={routeStopId:stop.routeStopId,visitDate:dateKey(),status,skipReason:reason,visitObservation:observation,orderId,occurredAt:new Date().toISOString(),idempotencyKey:crypto.randomUUID()};let visit:SalesRouteVisit;if(navigator.onLine)visit=await routesApi.recordVisit(route.routeId,request);else{await queueRouteVisit({idempotencyKey:request.idempotencyKey,routeId:route.routeId,businessId,warehouseId,request,queuedAt:new Date().toISOString(),attempts:0});visit={routeVisitId:`local-${request.idempotencyKey}`,routeStopId:stop.routeStopId,visitDate:request.visitDate,status,skipReason:reason,visitObservation:observation,orderId,occurredAt:request.occurredAt,recordedBy:"offline"}}const newVisits=[...visits.filter(item=>item.routeStopId!==stop.routeStopId),visit];setRuns(current=>current.map(run=>run.route.routeId===route.routeId?{...run,visits:newVisits}:run));await saveDailyRouteSnapshot({key:dailyRouteSnapshotKey(businessId,warehouseId,dateKey(),route.routeId),businessId,warehouseId,date:dateKey(),route,visits:newVisits,synchronizedAt:new Date().toISOString()});if(route.stops.every(item=>newVisits.some(value=>value.routeStopId===item.routeStopId))){const index=runs.findIndex(run=>run.route.routeId===route.routeId);const following=[...runs.slice(index+1),...runs.slice(0,index)].find(hasPendingStops);if(following){setActiveRouteId(following.route.routeId);toast.success(`Ruta completada. Continúa con ${following.route.name}.`)}}};
  return <div className="mx-auto max-w-7xl space-y-4 pb-24"><section className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-teal-950 to-emerald-700 p-6 text-white shadow-xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-teal-200">Ruta del día · {runs.length} recorrido{runs.length===1?"":"s"}</p><h1 className="mt-1 text-3xl font-black">{route?.name??"Preparando recorridos"}</h1><p className="mt-2 text-sm text-teal-50/80">Se respeta el orden configurado y se avanza automáticamente.</p></div><span className="rounded-2xl bg-white/10 p-3"><Route className="h-7 w-7"/></span></div><div className="mt-5 grid grid-cols-3 gap-2"><Metric label="Clientes hoy" value={totalStops}/><Metric label="Completados" value={totalDone}/><Metric label="Pendientes" value={totalStops-totalDone}/></div></section>
    <div className="grid gap-3 rounded-2xl border bg-card p-3 md:grid-cols-[1fr_1fr_auto]"><Select value={warehouseId} onValueChange={setWarehouseId}><SelectTrigger><SelectValue placeholder="Selecciona la bodega de venta"/></SelectTrigger><SelectContent>{workspaces.map(item=><SelectItem key={item.warehouseId} value={item.warehouseId}>{item.warehouseCode} · {item.warehouseName}</SelectItem>)}</SelectContent></Select><Select value={route?.routeId??""} onValueChange={setActiveRouteId} disabled={!runs.length}><SelectTrigger><SelectValue placeholder="Ruta de hoy"/></SelectTrigger><SelectContent>{runs.map(run=><SelectItem key={run.route.routeId} value={run.route.routeId}>{routeRunOrder(run.route,todayScheduleDay())}. {run.route.name} · {run.visits.length}/{run.route.stops.length}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={onAdministrative}>Ver todos los pedidos</Button></div>
    {!navigatorOnline()&&<div className="flex items-center gap-2 rounded-2xl bg-amber-50 p-3 text-sm font-medium text-amber-900"><CloudOff className="h-4 w-4"/>Modo sin conexión: los pedidos se guardan localmente y se enviarán solos.</div>}
    <div className="grid grid-cols-2 gap-2 rounded-2xl bg-muted p-1"><Tab active={tab==="route"} icon={Truck} onClick={()=>setTab("route")}>Recorrido</Tab><Tab active={tab==="map"} icon={Map} onClick={()=>setTab("map")}>Mapa</Tab></div>
    {loading&&<p className="p-12 text-center text-muted-foreground">Sincronizando rutas, clientes y visitas…</p>}
    {!loading&&route&&tab==="route"&&<div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="space-y-3">{route.stops.map((stop,index)=>{const visit=visits.find(item=>item.routeStopId===stop.routeStopId);return <button key={stop.routeStopId} onClick={()=>setActive(stop)} className={`flex w-full items-center gap-3 rounded-3xl border p-4 text-left transition ${visit?"border-emerald-200 bg-emerald-50/50":"bg-card hover:border-teal-300 hover:shadow-md"}`}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl font-black ${visit?"bg-emerald-500 text-white":"bg-slate-950 text-white"}`}>{visit?<Check className="h-5 w-5"/>:index+1}</span><span className="min-w-0 flex-1"><strong className="block truncate">{stop.customerName}</strong><small className="block truncate text-muted-foreground">{stop.addressLine} · {stop.cityName}</small><small className="text-teal-700">{visit?.status==="Skipped"?`Sin pedido · ${visit.skipReason}${visit.visitObservation?` · ${visit.visitObservation}`:""}`:visit?.orderId?"Pedido tomado":"Pendiente"}</small></span><ChevronRight className="h-5 w-5"/></button>})}</div><div className="lg:sticky lg:top-4 lg:self-start"><Card className="overflow-hidden rounded-[2rem] border-teal-200"><CardContent className="p-6">{next?<><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Siguiente cliente</p><h2 className="mt-2 text-2xl font-black">{next.customerName}</h2><p className="mt-2 flex gap-2 text-sm text-muted-foreground"><MapPin className="h-4 w-4 shrink-0"/>{next.addressLine}, {next.cityName}</p>{next.phone&&<p className="mt-1 text-sm">{next.phone}</p>}<div className="mt-6 grid gap-2"><Button className="h-12 bg-teal-600 hover:bg-teal-700" onClick={()=>setActive(next)}><ShoppingCart className="mr-2 h-5 w-5"/>Nuevo pedido</Button><Button variant="outline" onClick={()=>setSkip(next)}><SkipForward className="mr-2 h-4 w-4"/>Sin pedido</Button><a target="_blank" rel="noreferrer" href={directionsHref(next)} className="inline-flex h-10 items-center justify-center rounded-md border text-sm font-medium"><Navigation className="mr-2 h-4 w-4"/>Cómo llegar</a></div></>:<div className="py-8 text-center"><Check className="mx-auto h-12 w-12 rounded-full bg-emerald-500 p-2 text-white"/><h2 className="mt-4 text-xl font-black">Ruta completada</h2><p className="text-sm text-muted-foreground">Selecciona otro recorrido pendiente o revisa el mapa.</p></div>}</CardContent></Card></div></div>}
    {!loading&&route&&tab==="map"&&<RouteMap route={route} visits={visits} onOpen={setActive}/>}
    {active&&route&&<OrderDialog businessId={businessId} warehouseId={warehouseId} route={route} stop={active} onClose={()=>setActive(null)} onCreated={async(orderId)=>{await record(active,"Visited",orderId,null);setActive(null)}}/>}
    {skip&&<SkipDialog stop={skip} onClose={()=>setSkip(null)} onConfirm={async(reason,observation)=>{await record(skip,"Skipped",null,reason,observation);setSkip(null)}}/>}
  </div>;
}

function todayScheduleDay(){return isoScheduleDay(new Date().getDay())}
function routeRunOrder(route:SalesRouteDetail,day:number){return route.schedules.find(schedule=>schedule.dayOfWeek===day)?.runOrder??Number.MAX_SAFE_INTEGER}
function hasPendingStops(run:{route:SalesRouteDetail;visits:SalesRouteVisit[]}){return pendingRouteStops(run.route.stops,run.visits).length>0}

async function prefetchRouteCatalogs(businessId:string,warehouseId:string,stops:SalesRouteStop[]){
  if(!navigatorOnline())return;
  const customerIds=[...new Set(stops.map(stop=>stop.customerId))];
  for(const customerId of customerIds){
    let skip=0;
    do{
      const page=await sellerOrdersApi.catalog({businessId,warehouseId,customerId,search:undefined,skip,take:500});
      await saveSellerCatalog(businessId,warehouseId,customerId,page.items);
      if(!page.hasMore||page.nextOffset==null)break;
      skip=page.nextOffset;
    }while(navigatorOnline());
  }
}

function OrderDialog({businessId,warehouseId,route,stop,onClose,onCreated}:{businessId:string;warehouseId:string;route:SalesRouteDetail;stop:SalesRouteStop;onClose:()=>void;onCreated:(orderId:string)=>Promise<void>}){
  const key=`${businessId}:${warehouseId}:${route.routeId}:${stop.routeStopId}`;
  const searchRef=useRef<HTMLInputElement>(null);
  const [search,setSearch]=useState(""),[items,setItems]=useState<SellerCatalogItem[]>([]),[knownItems,setKnownItems]=useState<Record<string,SellerCatalogItem>>({}),[quantities,setQuantities]=useState<Record<string,number>>({}),[notes,setNotes]=useState(""),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[quantityItem,setQuantityItem]=useState<SellerCatalogItem|null>(null);
  const focusSearch=()=>requestAnimationFrame(()=>{searchRef.current?.focus({preventScroll:true});searchRef.current?.select()});
  useEffect(()=>{focusSearch()},[]);
  useEffect(()=>{let active=true;void loadSellerDraft(key).then(value=>{if(active&&value){setQuantities(value.quantities);setNotes(value.request.notes??"")}});return()=>{active=false}},[key]);
  useEffect(()=>{let active=true;const timer=setTimeout(()=>{setLoading(true);void sellerOrdersApi.catalog({businessId,warehouseId,customerId:stop.customerId,search,skip:0,take:100}).then(async page=>{if(active){setItems(page.items);setKnownItems(current=>({...current,...Object.fromEntries(page.items.map(item=>[item.productId,item]))}));await saveSellerCatalog(businessId,warehouseId,stop.customerId,page.items)}}).catch(async()=>{const cached=await loadSellerCatalog(businessId,warehouseId,stop.customerId);if(active){const filtered=cached.filter(item=>`${item.productCode} ${item.name}`.toLowerCase().includes(search.toLowerCase())).slice(0,100);setItems(filtered);setKnownItems(current=>({...current,...Object.fromEntries(cached.map(item=>[item.productId,item]))}))}}).finally(()=>active&&setLoading(false))},250);return()=>{active=false;clearTimeout(timer)}},[businessId,warehouseId,stop.customerId,search]);
  const selected=Object.entries(quantities).filter(([,quantity])=>quantity>0).flatMap(([productId,quantity])=>knownItems[productId]?[{item:knownItems[productId],quantity}]:[]);
  const total=selected.reduce((sum,value)=>sum+value.item.unitPrice*value.quantity,0),online=navigatorOnline();
  const request=():SellerOrderRequest=>({businessId,warehouseId,customerId:stop.customerId,partySiteId:stop.partySiteId,routeId:route.routeId,routeStopId:stop.routeStopId,capturedOffline:!online,notes:notes||null,idempotencyKey:crypto.randomUUID(),lines:Object.entries(quantities).filter(([,quantity])=>quantity>0).map(([productId,quantity])=>({productId,quantity}))});
  useEffect(()=>{if(!Object.keys(quantities).length)return;const value:SellerOrderRequest={businessId,warehouseId,customerId:stop.customerId,partySiteId:stop.partySiteId,routeId:route.routeId,routeStopId:stop.routeStopId,capturedOffline:!navigatorOnline(),notes:notes||null,idempotencyKey:`draft-${key}`,lines:Object.entries(quantities).filter(([,quantity])=>quantity>0).map(([productId,quantity])=>({productId,quantity}))};void saveSellerDraft(key,value,quantities)},[businessId,key,notes,quantities,route.routeId,stop.customerId,stop.partySiteId,stop.routeStopId,warehouseId]);
  const submit=async()=>{setSaving(true);try{const value=request();const result=online?await sellerOrdersApi.create(value):await queueSellerOrder(value,route,dateKey());await removeSellerDraft(key);toast.success(result.requiresReview?`${result.orderNumber} quedó en revisión`:`${result.orderNumber} guardado`);await onCreated(result.orderId)}catch(error){toast.error(message(error,"No fue posible guardar el pedido."))}finally{setSaving(false)}};
  const change=(item:SellerCatalogItem,delta:number)=>{setKnownItems(current=>({...current,[item.productId]:item}));setQuantities(current=>({...current,[item.productId]:Math.max(0,(current[item.productId]??0)+delta)}));focusSearch()};
  const setQuantity=(item:SellerCatalogItem,value:string)=>{setKnownItems(current=>({...current,[item.productId]:item}));setQuantities(current=>({...current,[item.productId]:Math.max(0,Number(value)||0)}))};
  const invalid=online&&selected.some(value=>value.item.manageStock&&value.quantity>value.item.quantityOnHand);
  return <><Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="flex h-[100dvh] max-h-[100dvh] w-screen max-w-none flex-col gap-3 overflow-hidden rounded-none p-0 sm:h-auto sm:max-h-[94vh] sm:max-w-4xl sm:rounded-3xl">
    <DialogHeader className="shrink-0 border-b px-4 pb-3 pt-5 text-left sm:px-6"><DialogTitle className="pr-8">Pedido · {stop.customerName}</DialogTitle><DialogDescription className="line-clamp-1">{stop.siteName} · {stop.addressLine}</DialogDescription></DialogHeader>
    <div className="shrink-0 px-3 sm:px-6"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 h-5 w-5 text-teal-700"/><Input ref={searchRef} autoFocus enterKeyHint="search" autoComplete="off" className="h-12 rounded-2xl border-teal-300 bg-teal-50/40 pl-10 pr-4 text-base shadow-sm" value={search} onFocus={event=>event.currentTarget.select()} onChange={event=>setSearch(event.target.value)} placeholder="Buscar producto por nombre"/></div><p className="mt-1.5 px-1 text-xs text-muted-foreground">Precio y existencia corresponden a la bodega seleccionada.</p></div>
    <div className="min-h-0 flex-1 overflow-y-auto px-3 pb-3 sm:px-6"><div className="grid gap-2 sm:grid-cols-2">{items.map(item=>{const quantity=quantities[item.productId]??0,short=item.manageStock&&quantity>item.quantityOnHand;return <article key={item.productId} className={`rounded-2xl border p-3 transition ${quantity>0?"border-teal-400 bg-teal-50/60 shadow-sm":"bg-card"}`}><button type="button" className="flex w-full items-start justify-between gap-3 text-left" onClick={()=>setQuantityItem(item)}><span className="min-w-0"><strong className="block leading-tight">{item.name}</strong><small className="mt-1 block text-muted-foreground">{item.productCode} · {item.unitCode}</small></span><strong className="shrink-0 text-base">{money.format(item.unitPrice)}</strong></button><div className="mt-3 flex items-center justify-between gap-2"><span className="min-w-0"><Badge variant="outline">{item.priceSource==="PriceList"?"Lista":item.priceSource==="PriceChannel"?"Canal":"Público"}</Badge><small className={`ml-2 whitespace-nowrap ${short?"font-semibold text-red-700":"text-muted-foreground"}`}>Disponible {item.quantityOnHand}</small></span><span className="flex shrink-0 items-center rounded-xl border bg-background p-0.5"><Button type="button" size="icon" variant="ghost" className="h-9 w-9 rounded-lg" aria-label={`Restar ${item.name}`} disabled={quantity<=0} onPointerDown={event=>event.preventDefault()} onClick={()=>change(item,-1)}><Minus className="h-4 w-4"/></Button><Input aria-label={`Cantidad de ${item.name}`} className="h-9 w-14 border-0 p-1 text-center text-base font-black shadow-none focus-visible:ring-1" inputMode="decimal" value={quantity||""} placeholder="0" onChange={event=>setQuantity(item,event.target.value)} onKeyDown={event=>{if(event.key==="Enter")focusSearch()}}/><Button type="button" size="icon" className="h-9 w-9 rounded-lg bg-teal-600 hover:bg-teal-700" aria-label={`Sumar ${item.name}`} disabled={online&&item.manageStock&&quantity>=item.quantityOnHand} onPointerDown={event=>event.preventDefault()} onClick={()=>change(item,1)}><Plus className="h-4 w-4"/></Button></span></div>{short&&<p className="mt-2 text-xs font-medium text-amber-800">{online?"Cantidad superior a la existencia disponible.":"Al sincronizar se revisará la existencia."}</p>}</article>})}</div>{loading&&<p className="p-4 text-center text-sm text-muted-foreground">Buscando productos…</p>}{!loading&&items.length===0&&<p className="p-8 text-center text-sm text-muted-foreground">No se encontraron productos.</p>}</div>
    <div className="shrink-0 border-t bg-background/95 px-3 pb-[max(0.75rem,env(safe-area-inset-bottom))] pt-3 shadow-[0_-10px_30px_-20px_rgba(15,118,110,0.7)] backdrop-blur sm:px-6"><div className="mb-3 grid grid-cols-[1fr_auto] items-center gap-3"><Input value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Nota del pedido (opcional)"/><div className="text-right"><small className="block text-muted-foreground">{selected.length} productos</small><strong className="text-xl">{money.format(total)}</strong></div></div><div className="grid grid-cols-[auto_1fr] gap-2"><Button variant="outline" onClick={onClose}>Salir</Button><Button className="h-12 bg-teal-600 text-base font-bold hover:bg-teal-700" disabled={saving||selected.length===0||invalid} onClick={submit}><PackagePlus className="mr-2 h-5 w-5"/>{saving?"Guardando…":online?"Crear pedido":"Guardar pedido"}</Button></div></div>
  </DialogContent></Dialog>{quantityItem&&<ProductQuantityDialog item={quantityItem} current={quantities[quantityItem.productId]??0} online={online} onClose={()=>{setQuantityItem(null);focusSearch()}} onConfirm={quantity=>{setQuantity(quantityItem,String(quantity));setQuantityItem(null);focusSearch()}}/>}</>;
}

function ProductQuantityDialog({item,current,online,onClose,onConfirm}:{item:SellerCatalogItem;current:number;online:boolean;onClose:()=>void;onConfirm:(quantity:number)=>void}){const [value,setValue]=useState(String(current||1));const quantity=Math.max(0,Number(value)||0),overStock=online&&item.manageStock&&quantity>item.quantityOnHand;return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="w-[calc(100%-1.5rem)] rounded-3xl p-5 sm:max-w-sm"><DialogHeader><DialogTitle>Cantidad</DialogTitle><DialogDescription>{item.name} · {money.format(item.unitPrice)} · disponible {item.quantityOnHand}</DialogDescription></DialogHeader><Input autoFocus className="h-16 rounded-2xl text-center text-3xl font-black" inputMode="decimal" value={value} onFocus={event=>event.currentTarget.select()} onChange={event=>setValue(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&quantity>0&&!overStock)onConfirm(quantity)}}/>{overStock&&<p className="text-sm font-medium text-red-700">La cantidad supera la existencia disponible.</p>}<DialogFooter className="grid grid-cols-2 gap-2 sm:grid-cols-2"><Button variant="outline" onClick={onClose}>Cancelar</Button><Button className="bg-teal-600 hover:bg-teal-700" disabled={quantity<=0||overStock} onClick={()=>onConfirm(quantity)}>Agregar</Button></DialogFooter></DialogContent></Dialog>}

function RouteMap({route,visits,onOpen}:{route:SalesRouteDetail;visits:SalesRouteVisit[];onOpen:(stop:SalesRouteStop)=>void}) {
  const status = new globalThis.Map(visits.map((visit) => [visit.routeStopId, visit.status]));
  return <RouteLocationMap
    stops={route.stops}
    onOpen={onOpen}
    statusOf={(stop) => status.get(stop.routeStopId) === "Visited" ? "visited" : status.get(stop.routeStopId) === "Skipped" ? "skipped" : "pending"}
  />;
}
function SkipDialog({stop,onClose,onConfirm}:{stop:SalesRouteStop;onClose:()=>void;onConfirm:(reason:string,observation:string)=>Promise<void>}){const [reason,setReason]=useState(""),[observation,setObservation]=useState(""),[saving,setSaving]=useState(false);return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="w-[calc(100%-1.5rem)] rounded-3xl p-5 sm:max-w-md"><DialogHeader><DialogTitle>Cerrar visita</DialogTitle><DialogDescription>{stop.customerName} · sin pedido</DialogDescription></DialogHeader><div className="grid gap-3"><Select value={reason} onValueChange={setReason}><SelectTrigger className="h-11"><SelectValue placeholder="Motivo"/></SelectTrigger><SelectContent><SelectItem value="Cliente ausente">Cliente ausente</SelectItem><SelectItem value="Establecimiento cerrado">Establecimiento cerrado</SelectItem><SelectItem value="No requiere productos">No requiere productos</SelectItem><SelectItem value="Pedido aplazado">Pedido aplazado</SelectItem><SelectItem value="Otro">Otro</SelectItem></SelectContent></Select><Textarea value={observation} onChange={event=>setObservation(event.target.value)} maxLength={1000} rows={3} placeholder="Observación"/></div><DialogFooter className="grid grid-cols-2 gap-2 sm:grid-cols-2"><Button variant="outline" onClick={onClose}>Cancelar</Button><Button disabled={!reason||!observation.trim()||saving} onClick={async()=>{setSaving(true);try{await onConfirm(reason,observation.trim())}finally{setSaving(false)}}}>{saving?"Guardando…":"Cerrar visita"}</Button></DialogFooter></DialogContent></Dialog>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-white/10 p-3 text-center"><strong className="block text-2xl">{value}</strong><small className="text-teal-100">{label}</small></div>}
function Tab({active,icon:Icon,onClick,children}:{active:boolean;icon:typeof Map;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`flex items-center justify-center rounded-xl px-3 py-2 text-sm font-semibold ${active?"bg-background shadow":"text-muted-foreground"}`}><Icon className="mr-2 h-4 w-4"/>{children}</button>}
function directionsHref(stop:SalesRouteStop){return stop.googleMapsUrl||(stop.latitude!=null&&stop.longitude!=null?`https://www.google.com/maps/dir/?api=1&destination=${stop.latitude},${stop.longitude}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${stop.addressLine}, ${stop.cityName}`)}`)}
function navigatorOnline(){return typeof navigator==="undefined"||navigator.onLine}
function message(error:unknown,fallback:string){return error&&typeof error==="object"&&"message" in error&&typeof error.message==="string"?error.message:fallback}
