"use client";

import {useEffect,useState} from "react";
import {Check,CheckCircle2,ChevronRight,ClipboardList,CloudOff,Download,Loader2,Map,MapPin,Navigation,Route,Settings2,ShoppingCart,SkipForward,Smartphone,Truck,UserPlus,Warehouse} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {RouteLocationMap} from "@/components/maps/route-location-map";
import {SellerOrderCaptureDialog} from "@/components/orders/seller-order-capture-dialog";
import {OutsideRouteCustomerDialog} from "@/components/orders/outside-route-customer-dialog";
import {SellerRouteOrdersPanel} from "@/components/orders/seller-route-orders-panel";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {dailyRouteSnapshotKey,loadDailyRouteSnapshots,queueRouteVisit,saveDailyRouteSnapshot} from "@/lib/daily-route-store";
import {canDismissWorkspaceDialog,firstPendingRouteStop,isoScheduleDay,pendingRouteStops,resolveSellerWorkspace} from "@/lib/daily-route-planning";
import {loadSellerOfflinePreparation,saveSellerCatalog,saveSellerOfflinePreparation,sellerOfflinePreparationKey,type SellerOfflinePreparation} from "@/lib/seller-order-offline-store";
import {routesApi,type SalesRouteDetail,type SalesRouteStop,type SalesRouteVisit} from "@/services/api/routes";
import {sellerOrdersApi} from "@/services/api/seller-orders";
import {loadSalesWorkspaceOptions,rememberedSalesWorkspaceKey,rememberSalesWorkspace,type SalesWorkspaceOption} from "@/services/pos/online-pos-client";

const localDateKey=(value=new Date())=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;

export function DailyRouteApp({businessId,onAdministrative}:{businessId:string;onAdministrative:()=>void}){
  const [workspaces,setWorkspaces]=useState<SalesWorkspaceOption[]>([]),[warehouseId,setWarehouseId]=useState("");
  const [workspaceOpen,setWorkspaceOpen]=useState(false),[runs,setRuns]=useState<Array<{route:SalesRouteDetail;visits:SalesRouteVisit[]}>>([]),[activeRouteId,setActiveRouteId]=useState("");
  const [tab,setTab]=useState<"route"|"map"|"orders">("route"),[loading,setLoading]=useState(true),[active,setActive]=useState<{stop:SalesRouteStop;outside:boolean}|null>(null),[skip,setSkip]=useState<SalesRouteStop|null>(null),[ordersRevision,setOrdersRevision]=useState(0),[outsideOpen,setOutsideOpen]=useState(false),[clientsOpen,setClientsOpen]=useState(false);
  const [operationalDate,setOperationalDate]=useState(localDateKey),[online,setOnline]=useState(navigatorOnline),[preparing,setPreparing]=useState(false),[preparation,setPreparation]=useState<SellerOfflinePreparation|null>(null),[preparationProgress,setPreparationProgress]=useState({current:0,total:0});
  const activeRun=runs.find((run)=>run.route.routeId===activeRouteId)??runs[0],route=activeRun?.route??null,visits=activeRun?.visits??[];
  const workspace=workspaces.find((item)=>item.warehouseId===warehouseId)??null;
  useEffect(()=>{const timer=window.setInterval(()=>setOperationalDate(localDateKey()),30000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{const connected=()=>setOnline(true),disconnected=()=>setOnline(false);window.addEventListener("online",connected);window.addEventListener("offline",disconnected);return()=>{window.removeEventListener("online",connected);window.removeEventListener("offline",disconnected)}},[]);
  useEffect(()=>{if(!warehouseId){setPreparation(null);return}let mounted=true;void loadSellerOfflinePreparation(businessId,warehouseId,operationalDate).then(value=>{if(mounted)setPreparation(value??null)});return()=>{mounted=false}},[businessId,operationalDate,warehouseId]);
  useEffect(()=>{let mounted=true;setWarehouseId("");setRuns([]);setLoading(true);void loadSalesWorkspaceOptions().then(values=>{if(!mounted)return;const scoped=values.filter(item=>item.businessId===businessId),selected=resolveSellerWorkspace(scoped,businessId,rememberedSalesWorkspaceKey());setWorkspaces(scoped);if(selected){setWarehouseId(selected.warehouseId);rememberSalesWorkspace(selected)}else{setLoading(false);setWorkspaceOpen(scoped.length>1)}}).catch(error=>{if(mounted){setLoading(false);toast.error(message(error,"No fue posible consultar las bodegas."))}});return()=>{mounted=false}},[businessId]);
  useEffect(()=>{if(!warehouseId)return;let mounted=true;const load=async()=>{setLoading(true);try{
    const day=isoScheduleDay(new Date(`${operationalDate}T12:00:00`).getDay());
    const page=await routesApi.page({page:1,pageSize:100,dayOfWeek:day,isActive:true,preparationStatus:"Ready"});
    if(!page.items.length)throw new Error("No tienes rutas listas para hoy.");
    const loaded=await Promise.all(page.items.map(async(item)=>{const [detail,todayVisits]=await Promise.all([routesApi.detail(item.routeId),routesApi.visits(item.routeId,operationalDate)]);return {route:detail,visits:todayVisits}}));
    loaded.sort((left,right)=>routeRunOrder(left.route,day)-routeRunOrder(right.route,day)||left.route.name.localeCompare(right.route.name,"es"));
    if(!mounted)return;setRuns(loaded);setActiveRouteId(current=>loaded.some(run=>run.route.routeId===current)?current:(loaded.find(hasPendingStops)??loaded[0]).route.routeId);
    await Promise.all(loaded.map(run=>saveDailyRouteSnapshot({key:dailyRouteSnapshotKey(businessId,warehouseId,operationalDate,run.route.routeId),businessId,warehouseId,date:operationalDate,route:run.route,visits:run.visits,synchronizedAt:new Date().toISOString()})));
    rememberSalesWorkspace({businessId,warehouseId});
  }catch(error){const cached=await loadDailyRouteSnapshots(businessId,warehouseId,operationalDate);if(cached.length&&mounted){const loaded=cached.map(value=>({route:value.route,visits:value.visits}));setRuns(loaded);setActiveRouteId((loaded.find(hasPendingStops)??loaded[0]).route.routeId);toast.info("Rutas cargadas sin conexión")}else if(mounted)toast.error(message(error,"No fue posible cargar las rutas de hoy."))}finally{if(mounted)setLoading(false)}};void load();return()=>{mounted=false}},[businessId,operationalDate,warehouseId]);
  const next=firstPendingRouteStop(route?.stops??[],visits);
  const totalStops=runs.reduce((sum,run)=>sum+run.route.stops.length,0),totalDone=runs.reduce((sum,run)=>sum+new Set(run.visits.map(visit=>visit.routeStopId)).size,0);
  const chooseWorkspace=(value:SalesWorkspaceOption)=>{setRuns([]);setActiveRouteId("");setPreparation(null);setWarehouseId(value.warehouseId);rememberSalesWorkspace(value);setWorkspaceOpen(false);setTab("route")};
  const prepareOffline=async()=>{if(!online){toast.error("Conéctate a internet para preparar este teléfono.");return}if(!runs.length||!warehouseId)return;setPreparing(true);try{const stops=runs.flatMap(run=>run.route.stops),customerCount=new Set(stops.map(stop=>stop.customerId)).size;setPreparationProgress({current:0,total:customerCount});await Promise.all(runs.map(run=>saveDailyRouteSnapshot({key:dailyRouteSnapshotKey(businessId,warehouseId,operationalDate,run.route.routeId),businessId,warehouseId,date:operationalDate,route:run.route,visits:run.visits,synchronizedAt:new Date().toISOString()})));const catalogEntryCount=await downloadRouteCatalogs(businessId,warehouseId,stops,(current,total)=>setPreparationProgress({current,total}));const value:SellerOfflinePreparation={key:sellerOfflinePreparationKey(businessId,warehouseId,operationalDate),businessId,warehouseId,date:operationalDate,preparedAt:new Date().toISOString(),routeCount:runs.length,customerCount,catalogEntryCount};await saveSellerOfflinePreparation(value);setPreparation(value);toast.success("Teléfono listo para trabajar sin conexión.")}catch(error){toast.error(message(error,"No fue posible completar la preparación sin conexión."))}finally{setPreparing(false)}};
  const record=async(stop:SalesRouteStop,status:"Visited"|"Skipped",orderId:string|null,reason:string|null,observation:string|null=null)=>{if(!route)return;const request={routeStopId:stop.routeStopId,visitDate:operationalDate,status,skipReason:reason,visitObservation:observation,orderId,occurredAt:new Date().toISOString(),idempotencyKey:crypto.randomUUID()};let visit:SalesRouteVisit;if(navigator.onLine)visit=await routesApi.recordVisit(route.routeId,request);else{await queueRouteVisit({idempotencyKey:request.idempotencyKey,routeId:route.routeId,businessId,warehouseId,request,queuedAt:new Date().toISOString(),attempts:0});visit={routeVisitId:`local-${request.idempotencyKey}`,routeStopId:stop.routeStopId,visitDate:request.visitDate,status,skipReason:reason,visitObservation:observation,orderId,occurredAt:request.occurredAt,recordedBy:"offline"}}const newVisits=[...visits.filter(item=>item.routeStopId!==stop.routeStopId),visit];setRuns(current=>current.map(run=>run.route.routeId===route.routeId?{...run,visits:newVisits}:run));await saveDailyRouteSnapshot({key:dailyRouteSnapshotKey(businessId,warehouseId,operationalDate,route.routeId),businessId,warehouseId,date:operationalDate,route,visits:newVisits,synchronizedAt:new Date().toISOString()});if(route.stops.every(item=>newVisits.some(value=>value.routeStopId===item.routeStopId))){const index=runs.findIndex(run=>run.route.routeId===route.routeId);const following=[...runs.slice(index+1),...runs.slice(0,index)].find(hasPendingStops);if(following){setActiveRouteId(following.route.routeId);toast.success(`Ruta completada. Continúa con ${following.route.name}.`)}}};
  return <div className="mx-auto max-w-7xl space-y-3 pb-24"><section className="rounded-3xl bg-gradient-to-r from-slate-950 via-teal-950 to-emerald-700 p-4 text-white shadow-lg"><div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-white/10"><Route className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="text-xs font-bold text-teal-200">Mi ruta de hoy</p><h1 className="truncate text-lg font-black">{route?.name??"Preparando recorridos"}</h1></div><div className="flex shrink-0 gap-1.5"><Metric label="Hechos" value={totalDone}/><Metric label="Faltan" value={totalStops-totalDone}/></div></div></section>
    <div className="grid grid-cols-2 gap-3 rounded-3xl border bg-card p-3 md:grid-cols-[minmax(15rem,.8fr)_1fr_auto_auto]"><button type="button" onClick={()=>setWorkspaceOpen(true)} className="col-span-2 flex min-h-12 items-center gap-3 rounded-2xl border bg-muted/40 px-3 text-left transition hover:border-teal-300 md:col-span-1"><span className="rounded-xl bg-teal-50 p-2 text-teal-700"><Warehouse className="h-5 w-5"/></span><span className="min-w-0 flex-1"><small className="block text-muted-foreground">Bodega configurada</small><strong className="block truncate">{workspace?`${workspace.warehouseCode} · ${workspace.warehouseName}`:"Configurar bodega"}</strong></span><Settings2 className="h-4 w-4 text-muted-foreground"/></button>{runs.length>1?<Select value={route?.routeId??""} onValueChange={setActiveRouteId}><SelectTrigger className="col-span-2 h-12 rounded-2xl md:col-span-1"><SelectValue placeholder="Recorrido de hoy"/></SelectTrigger><SelectContent>{runs.map(run=><SelectItem key={run.route.routeId} value={run.route.routeId}>{routeRunOrder(run.route,todayScheduleDay())}. {run.route.name} · {run.visits.length}/{run.route.stops.length}</SelectItem>)}</SelectContent></Select>:<div className="col-span-2 flex h-12 items-center rounded-2xl bg-muted/40 px-4 md:col-span-1"><span className="min-w-0"><small className="block text-muted-foreground">Recorrido de hoy</small><strong className="block truncate">{route?.name??"Sin ruta asignada"}</strong></span></div>}<Button className="h-12 rounded-2xl" variant="outline" onClick={()=>setOutsideOpen(true)}><UserPlus className="mr-2 h-4 w-4"/><span className="hidden lg:inline">Fuera de ruta</span><span className="lg:hidden">Otro cliente</span></Button><Button className="h-12 rounded-2xl" variant="outline" title="Ver todos los pedidos" onClick={onAdministrative}><ClipboardList className="mr-2 h-4 w-4"/>Historial</Button></div>
    {!online&&<div className="flex items-center gap-2 rounded-2xl bg-amber-50 p-3 text-sm font-medium text-amber-900"><CloudOff className="h-4 w-4"/>Modo sin conexión: los pedidos se guardan localmente y se enviarán solos.</div>}
    {!warehouseId&&!loading&&<div className="rounded-[2rem] border border-dashed p-12 text-center"><Warehouse className="mx-auto h-12 w-12 text-teal-600"/><h2 className="mt-4 text-xl font-black">Configura tu bodega de venta</h2><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">Se recordará en este dispositivo y solo tendrás que cambiarla cuando realmente trabajes desde otra bodega.</p><Button className="mt-6 bg-teal-600" onClick={()=>setWorkspaceOpen(true)}>Elegir bodega</Button></div>}
    {route&&<div className="grid grid-cols-3 gap-1 rounded-2xl bg-muted p-1"><Tab active={tab==="route"} icon={Truck} onClick={()=>setTab("route")}>Recorrido</Tab><Tab active={tab==="map"} icon={Map} onClick={()=>setTab("map")}>Mapa</Tab><Tab active={tab==="orders"} icon={ClipboardList} onClick={()=>setTab("orders")}>Pedidos</Tab></div>}
    {warehouseId&&<OfflinePreparationCard online={online} preparing={preparing} preparation={preparation} progress={preparationProgress} disabled={!runs.length||loading} onPrepare={()=>void prepareOffline()}/>}
    {loading&&<p className="p-12 text-center text-muted-foreground">Sincronizando rutas, clientes y visitas…</p>}
    {!loading&&route&&tab==="route"&&<div className="space-y-3"><NextCustomer stop={next} onOrder={(stop)=>setActive({stop,outside:false})} onSkip={setSkip}/><section className="rounded-3xl border bg-card"><button type="button" className="flex w-full items-center justify-between p-4 text-left" onClick={()=>setClientsOpen(value=>!value)}><span><strong className="block">Todos los clientes</strong><small className="text-muted-foreground">{visits.length}/{route.stops.length} completados · toca para {clientsOpen?"ocultar":"ver el recorrido"}</small></span><ChevronRight className={`h-5 w-5 transition ${clientsOpen?"rotate-90":""}`}/></button>{clientsOpen&&<div className="grid gap-3 border-t p-3 lg:grid-cols-2">{route.stops.map((stop,index)=>{const visit=visits.find(item=>item.routeStopId===stop.routeStopId);return <button key={stop.routeStopId} onClick={()=>setActive({stop,outside:false})} className={`flex w-full items-center gap-3 rounded-3xl border p-4 text-left transition ${visit?"border-emerald-200 bg-emerald-50/50":"bg-card hover:border-teal-300 hover:shadow-md"}`}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl font-black ${visit?"bg-emerald-500 text-white":"bg-slate-950 text-white"}`}>{visit?<Check className="h-5 w-5"/>:index+1}</span><span className="min-w-0 flex-1"><strong className="block truncate">{stop.customerName}</strong><small className="block truncate text-muted-foreground">{stop.addressLine} · {stop.cityName}</small><small className="text-teal-700">{visit?.status==="Skipped"?`Sin pedido · ${visit.skipReason}${visit.visitObservation?` · ${visit.visitObservation}`:""}`:visit?.orderId?"Pedido tomado":"Pendiente"}</small></span><ChevronRight className="h-5 w-5"/></button>})}</div>}</section></div>}
    {!loading&&route&&tab==="map"&&<RouteMap route={route} visits={visits} onOpen={(stop)=>setActive({stop,outside:false})}/>}
    {!loading&&route&&tab==="orders"&&<SellerRouteOrdersPanel key={`orders-${operationalDate}-${route.routeId}`} route={route} operationalDate={operationalDate} warehouseId={warehouseId} revision={ordersRevision}/>}
    {active&&(active.outside||route)&&<SellerOrderCaptureDialog businessId={businessId} warehouseId={warehouseId} route={active.outside?null:route} stop={active.stop} onClose={()=>setActive(null)} onCreated={async(orderId)=>{if(!active.outside)await record(active.stop,"Visited",orderId,null);setOrdersRevision(value=>value+1);setTab("orders");setActive(null)}}/>}
    {skip&&<SkipDialog stop={skip} onClose={()=>setSkip(null)} onConfirm={async(reason,observation)=>{await record(skip,"Skipped",null,reason,observation);setSkip(null)}}/>}
    {outsideOpen&&<OutsideRouteCustomerDialog routeId={route?.routeId??null} onClose={()=>setOutsideOpen(false)} onSelect={(stop)=>{setOutsideOpen(false);setActive({stop,outside:true})}}/>}
    <WorkspaceDialog open={workspaceOpen} required={!warehouseId} items={workspaces} selectedId={warehouseId} onClose={()=>setWorkspaceOpen(false)} onSelect={chooseWorkspace}/>
  </div>;
}

function OfflinePreparationCard({online,preparing,preparation,progress,disabled,onPrepare}:{online:boolean;preparing:boolean;preparation:SellerOfflinePreparation|null;progress:{current:number;total:number};disabled:boolean;onPrepare:()=>void}){const ready=!!preparation,percent=progress.total?Math.round(progress.current/progress.total*100):0;return <section className={`overflow-hidden rounded-2xl border px-3 py-2 ${ready?"border-emerald-200 bg-emerald-50/60":"border-amber-200 bg-amber-50/60"}`}><div className="flex items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${ready?"bg-emerald-500 text-white":"bg-amber-100 text-amber-800"}`}>{ready?<CheckCircle2 className="h-5 w-5"/>:<Smartphone className="h-5 w-5"/>}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{ready?"Listo para trabajar sin conexión":"Trabajo sin conexión"}</strong><small className="block truncate text-muted-foreground">{ready?`${preparation.customerCount} clientes · ${preparation.catalogEntryCount} productos · ${new Date(preparation.preparedAt).toLocaleTimeString("es-CO",{hour:"2-digit",minute:"2-digit"})}`:"Descarga la ruta y el catálogo antes de salir."}</small></div><Button size="sm" className={ready?"":"bg-amber-700 hover:bg-amber-800"} variant={ready?"outline":"default"} disabled={disabled||preparing||!online} onClick={onPrepare}>{preparing?<Loader2 className="mr-1 h-4 w-4 animate-spin"/>:<Download className="mr-1 h-4 w-4"/>}{preparing?`${progress.current}/${progress.total}`:ready?"Actualizar":"Preparar"}</Button></div>{preparing&&<div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-teal-600 transition-all" style={{width:`${percent}%`}}/></div>}</section>}
function NextCustomer({stop,onOrder,onSkip}:{stop:SalesRouteStop|null;onOrder:(stop:SalesRouteStop)=>void;onSkip:(stop:SalesRouteStop)=>void}){return <Card className="overflow-hidden rounded-[2rem] border-teal-200 bg-gradient-to-br from-teal-50 via-white to-white shadow-sm"><CardContent className="p-6">{stop?<div className="grid gap-5 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Siguiente cliente</p><h2 className="mt-2 text-2xl font-black">{stop.customerName}</h2><p className="mt-2 flex gap-2 text-sm text-muted-foreground"><MapPin className="h-4 w-4 shrink-0"/>{stop.addressLine}, {stop.cityName}</p>{stop.phone&&<p className="mt-1 text-sm">{stop.phone}</p>}</div><div className="grid min-w-52 gap-2"><Button className="h-12 bg-teal-600 hover:bg-teal-700" onClick={()=>onOrder(stop)}><ShoppingCart className="mr-2 h-5 w-5"/>Tomar pedido</Button><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>onSkip(stop)}><SkipForward className="mr-1 h-4 w-4"/>Sin pedido</Button><Button asChild variant="outline"><a target="_blank" rel="noreferrer" href={directionsHref(stop)}><Navigation className="mr-1 h-4 w-4"/>Llegar</a></Button></div></div></div>:<div className="py-8 text-center"><Check className="mx-auto h-12 w-12 rounded-full bg-emerald-500 p-2 text-white"/><h2 className="mt-4 text-xl font-black">Ruta completada</h2><p className="text-sm text-muted-foreground">Puedes revisar tus pedidos o seleccionar otro recorrido.</p></div>}</CardContent></Card>}
function WorkspaceDialog({open,required,items,selectedId,onClose,onSelect}:{open:boolean;required:boolean;items:SalesWorkspaceOption[];selectedId:string;onClose:()=>void;onSelect:(item:SalesWorkspaceOption)=>void}){const dismissible=canDismissWorkspaceDialog(required,items.length);return <Dialog open={open} onOpenChange={value=>{if(!value&&dismissible)onClose()}}><DialogContent className="max-h-[92dvh] w-[calc(100%-1.5rem)] overflow-y-auto rounded-[2rem] sm:max-w-lg"><DialogHeader><DialogTitle>Bodega de venta</DialogTitle><DialogDescription>Quedará guardada en este dispositivo. Cámbiala únicamente cuando tu operación use otra bodega.</DialogDescription></DialogHeader><div className="space-y-2">{items.map(item=><button type="button" key={item.warehouseId} onClick={()=>onSelect(item)} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left transition ${selectedId===item.warehouseId?"border-teal-400 bg-teal-50 ring-2 ring-teal-100":"hover:border-teal-300"}`}><span className="rounded-xl bg-teal-100 p-2 text-teal-700"><Warehouse className="h-5 w-5"/></span><span className="min-w-0 flex-1"><strong className="block">{item.warehouseName}</strong><small className="text-muted-foreground">{item.warehouseCode} · {item.warehouseAllowsNegativeStockSales?"Permite negativos":"Valida existencias"}</small></span>{selectedId===item.warehouseId&&<Check className="h-5 w-5 text-teal-700"/>}</button>)}{!items.length&&<p className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">No tienes bodegas de venta disponibles.</p>}</div>{dismissible&&<DialogFooter><Button variant="outline" onClick={onClose}>{items.length?"Conservar actual":"Cerrar"}</Button></DialogFooter>}</DialogContent></Dialog>}

function todayScheduleDay(){return isoScheduleDay(new Date().getDay())}
function routeRunOrder(route:SalesRouteDetail,day:number){return route.schedules.find(schedule=>schedule.dayOfWeek===day)?.runOrder??Number.MAX_SAFE_INTEGER}
function hasPendingStops(run:{route:SalesRouteDetail;visits:SalesRouteVisit[]}){return pendingRouteStops(run.route.stops,run.visits).length>0}

async function downloadRouteCatalogs(businessId:string,warehouseId:string,stops:SalesRouteStop[],onProgress:(current:number,total:number)=>void){
  const customerIds=[...new Set(stops.map(stop=>stop.customerId))],entries=new Set<string>();let current=0;
  for(const customerId of customerIds){let skip=0;while(true){if(!navigatorOnline())throw new Error("Se perdió la conexión. Vuelve a intentar la preparación.");const page=await sellerOrdersApi.catalog({businessId,warehouseId,customerId,search:undefined,skip,take:500});await saveSellerCatalog(businessId,warehouseId,customerId,page.items);for(const item of page.items)entries.add(`${customerId}:${item.productId}`);if(!page.hasMore||page.nextOffset==null)break;skip=page.nextOffset}onProgress(++current,customerIds.length)}
  return entries.size;
}

function RouteMap({route,visits,onOpen}:{route:SalesRouteDetail;visits:SalesRouteVisit[];onOpen:(stop:SalesRouteStop)=>void}) {
  const status = new globalThis.Map(visits.map((visit) => [visit.routeStopId, visit.status]));
  return <RouteLocationMap
    stops={route.stops}
    onOpen={onOpen}
    statusOf={(stop) => status.get(stop.routeStopId) === "Visited" ? "visited" : status.get(stop.routeStopId) === "Skipped" ? "skipped" : "pending"}
  />;
}
function SkipDialog({stop,onClose,onConfirm}:{stop:SalesRouteStop;onClose:()=>void;onConfirm:(reason:string,observation:string)=>Promise<void>}){const [reason,setReason]=useState(""),[observation,setObservation]=useState(""),[saving,setSaving]=useState(false);return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="w-[calc(100%-1.5rem)] rounded-3xl p-5 sm:max-w-md"><DialogHeader><DialogTitle>Cerrar visita</DialogTitle><DialogDescription>{stop.customerName} · sin pedido</DialogDescription></DialogHeader><div className="grid gap-3"><Input value={reason} onChange={event=>setReason(event.target.value)} maxLength={200} placeholder="Motivo de la visita sin pedido"/><Textarea value={observation} onChange={event=>setObservation(event.target.value)} maxLength={1000} rows={3} placeholder="Observación"/></div><DialogFooter className="grid grid-cols-2 gap-2 sm:grid-cols-2"><Button variant="outline" onClick={onClose}>Cancelar</Button><Button disabled={!reason||!observation.trim()||saving} onClick={async()=>{setSaving(true);try{await onConfirm(reason,observation.trim())}finally{setSaving(false)}}}>{saving?"Guardando…":"Cerrar visita"}</Button></DialogFooter></DialogContent></Dialog>}
function Metric({label,value}:{label:string;value:number}){return <div className="min-w-14 rounded-xl bg-white/10 px-2 py-1.5 text-center"><strong className="block text-base leading-none">{value}</strong><small className="text-[10px] text-teal-100">{label}</small></div>}
function Tab({active,icon:Icon,onClick,children}:{active:boolean;icon:typeof Map;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`flex items-center justify-center rounded-xl px-3 py-2 text-sm font-semibold ${active?"bg-background shadow":"text-muted-foreground"}`}><Icon className="mr-2 h-4 w-4"/>{children}</button>}
function directionsHref(stop:SalesRouteStop){return stop.googleMapsUrl||(stop.latitude!=null&&stop.longitude!=null?`https://www.google.com/maps/dir/?api=1&destination=${stop.latitude},${stop.longitude}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${stop.addressLine}, ${stop.cityName}`)}`)}
function navigatorOnline(){return typeof navigator==="undefined"||navigator.onLine}
function message(error:unknown,fallback:string){return error&&typeof error==="object"&&"message" in error&&typeof error.message==="string"?error.message:fallback}
