name: Deploy AURALY Admin

on:
  push:
    branches:
      - deploy/auraly-admin-rc1
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and deploy DEV
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AURALY_SWA_DEV_TOKEN }}
          action: upload
          app_location: ./admin
          api_location: ''
          output_location: ''
        env:
          NEXT_PUBLIC_API_URL: https://api-auraly-dev-w5usmo6w.azurewebsites.net

  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and deploy PROD
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AURALY_SWA_PROD_TOKEN }}
          action: upload
          app_location: ./admin
          api_location: ''
          output_location: ''
        env:
          NEXT_PUBLIC_API_URL: https://api-auraly-prod-7sov4nxc.azurewebsites.net
